### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by niros001** [FaridSafi/react-native-google-places-autocomplete#100]
Hi, When i tap the search bar i got this error: Cannot read property '0' of undefined

**Comment by myaskevich** [comment]
Hi @niros001 

Please paste in some code so I could see what could be wrong here, otherwise it's quite hard to get what's going on.

**Comment by samf1981** [comment]
if you're trying this on a simulator make sure to turn off the currentLocation 

`currentLocation={false}`
