### ISSUE TITLE
Two autocomplete inputs on screen

### ISSUE THREAD

**Issue by brascene** [FaridSafi/react-native-google-places-autocomplete#101]
If I put two autocomplete inputs one under another, then first one has a trouble with its listView which does not show itself over the second input.
I've tried with setting the first input :
       listView:{position:'absolute'}
, but still not achieving the goal. 
Any ideas on this?

Thanks!

**Comment by myaskevich** [comment]
Hi @brascene 

Check out `zIndex` prop https://facebook.github.io/react-native/docs/layout-props.html#zindex

**Comment by myaskevich** [comment]
I'm closing it since it is not related to the library.

**Comment by brascene** [comment]
OK, just for info: solved with zIndex prop.

**Comment by Taakn** [comment]
@brascene Would it be possible for you to let me know how you used zIndex exactly ? Thanks so much

**Comment by Taakn** [comment]
zIndex seems to be working on iOS but not Android. Elevation either. Did you get it working @brascene ? Would you mind showing me some sample code ? Thanks so much

**Comment by andrewBIsP** [comment]
You can add one into the other
