### ISSUE TITLE
change coordinates for search

### ISSUE THREAD

**Issue by ssomnoremac** [FaridSafi/react-native-google-places-autocomplete#102]
Maybe I'm missing something but all I want to do is hardcode coordinates for where the search is centered. From the api it seems that one can do this 

    query={{
                            // available options: https://developers.google.com/places/weservice/autocomplete
                            key: '----',
                            language: 'en', // language of the results
                            types: 'establishment', // default: 'geocode'
                            location: '37.76999,-122.44696',   <----------------- added this
                        }}

based on the options in the docs, however it's not working

A quick glance at the code it seems like the "options" in queryString aren't iterated on, rather added for just the first three only. Am I correct?

**Comment by brascene** [comment]
You've put coordinates for where the search is centered, but I think you should also put a radius (in meters) in which your search will be made, e.g.:
radius: '10000'.

P.S., I'm using similar query, and I've specified another field, for my country: 
components: 'country:ba'

Here's the source: https://developers.google.com/places/web-service/autocomplete
Check component property and examples, and good luck.

**Comment by myaskevich** [comment]
Everything you specify in `query` prop is passed in to google places api query.

Feel free to reopen is you still having issues.
