### ISSUE TITLE
Styling issue on Android - It shows Underline in the text input 

### ISSUE THREAD

**Issue by RajanPN** [FaridSafi/react-native-google-places-autocomplete#103]
There is styling issue on android which shows underline in the text input. For solution the underlineColorAndroid="transparent" prop should be used ;

<TextInput
            { ...userProps }
            ref="textInput"
            autoFocus={this.props.autoFocus}
            style={[defaultStyles.textInput, this.props.styles.textInput]}
            onChangeText={onChangeText ? text => {this._onChangeText(text); onChangeText(text)} : this._onChangeText}
            value={this.state.text}
            placeholder={this.props.placeholder}
            placeholderTextColor={this.props.placeholderTextColor}
            onFocus={onFocus ? () => {this._onFocus(); onFocus()} : this._onFocus}
            clearButtonMode="while-editing"
            **underlineColorAndroid**="transparent"
          />

**Comment by myaskevich** [comment]
Hi @RajanPN 

Cool.

Could you please submit a PR and i'll merge it?

Thanks

**Comment by brascene** [comment]
This solution worked for me:
textInputProps={{underlineColorAndroid:'rgba(0,0,0,0)'}}

**Comment by myaskevich** [comment]
@RajanPN Check out `underlineColorAndroid` prop in v1.2.8
