### ISSUE TITLE
Does the node module support display for characters of Arabic and other languages?

### ISSUE THREAD

**Issue by zohaibahmeds63** [FaridSafi/react-native-google-places-autocomplete#106]
I am receiving an Arabic name for a place in JSON response. The response is perfect in Postman Chrome Extension, but while using the node module, special characters are displayed in the results list view.

Does the node module support characters of Arabic and other languages? If yes, then it would be great if anyone could share an example.

Thanks.

**Comment by myaskevich** [comment]
Hi @zohaibahmeds63 

Could you tell me which country should I try the results from in order to reproduce the issue?

**Comment by zohaibahmeds63** [comment]
Hello @myaskevich, hope you are doing fine.

(31.4629258, 74.3849804) are the coordinates that are being used in the API request.

**Comment by myaskevich** [comment]
Hi @zohaibahmeds63 

I got a couple of results from the location you specified, and it they look ok:
<img width="325" alt="screen shot 2017-03-26 at 7 26 47 pm" src="https://cloud.githubusercontent.com/assets/958221/24333057/48435e84-125a-11e7-9cdf-f312ece61151.png">

Here is the code I used:
```
            query={{
              key: config.GOOGLE_SERVER_KEY,
              type: 'address',
              location: '31.4629258,74.38498044',
              radius: 20000,
              language: 'ur'
            }}
            GooglePlacesSearchQuery={{
              location: '31.4629258,74.38498044',
              radius: 20000,
              language: 'ur'
            }}
```

Please feel free to reopen this if you still having issues.
