### ISSUE TITLE
row in demo returning error?

### ISSUE THREAD

**Issue by sooonmitch** [FaridSafi/react-native-google-places-autocomplete#107]
Firstly, sorry if this is a noob mistake or something I have done but I am trying to learn React Native for Android and have been experimenting with this lib. I have one issue, the demo you guys gave causes an error.

"undefined is not an object (evaluating 'row.terms[0]')"

```
      <GooglePlacesAutocomplete
        placeholder='Search'
        minLength={2}
        autoFocus={false}
        listViewDisplayed='auto'
        fetchDetails={true}
        renderDescription={(row) => row.terms[0].value} // ----- Here is the error line

        onPress={(data, details = null) => {
          console.log(data);
          console.log(details);
        }}
        getDefaultValue={() => {
          return '';
        }}
        query={{
          key: 'I removed key',
          language: 'en',
          types: '(cities)',
        }}
        styles={{
          container: {
            top: (window.height/40)*3,
            left: 0,
            width: window.width,
            height: (window.height/40)*3,
          },
          description: {
            fontWeight: 'bold',
          },
          predefinedPlacesDescription: {
            color: '#1faadb',
          },
        }}

        currentLocation={true}
        currentLocationLabel="Current location"
        nearbyPlacesAPI='GoogleReverseGeocoding'
        GoogleReverseGeocodingQuery={{
        }}
        GooglePlacesSearchQuery={{
        }}


        filterReverseGeocodingByTypes={['street_address']}

        predefinedPlaces={[homePlace, workPlace]}
      />
```

Again sorry if it is my mistake, still new to the whole React world. I am mostly a Java/Golang guy.

**Comment by myaskevich** [comment]
Hi @sooonmitch 

Try to change `row.terms[0].value` to `console.log(JSON.stringify(row))` and see what's in there

**Comment by sooonmitch** [comment]
I got this:
{"description":"Current location","isCurrentLocation":true,"isPredefinedPlace":true}
{"description":"Home","geometry":{"location":{"lat":48.8152937,"lng":2.4597668}},"isPredefinedPlace":true}
{"description":"Work","geometry":{"location":{"lat":48.8496818,"lng":2.2940881}},"isPredefinedPlace":true}

**Comment by myaskevich** [comment]
Thanks, I'll update the example.

The example shows a possible way of using custom description rendering.

For you to fix the issue, please imply remove this line from your component to use default rendering.
