### ISSUE TITLE
Not fully auto completing 

### ISSUE THREAD

**Issue by sooonmitch** [FaridSafi/react-native-google-places-autocomplete#108]
How come this does not autocomplete after I type 2 characters? For example, I can type

"82" and it will pop up some random addresses and stuff but after that, it goes completely blank and never fixes itself even after I type a full address.

```
      <GooglePlacesAutocomplete
        placeholder='Search'
        minLength={2}
        autoFocus={false}
        listViewDisplayed='auto'
        fetchDetails={true}

        onPress={(data, details = null) => {
          console.log(data);
          console.log(details);
        }}
        getDefaultValue={() => {
          return '';
        }}
        query={{
          key: 'I removed key',
          language: 'en',
          types: '(cities)',
        }}
        styles={{
          container: {
            top: (window.height/40)*3,
            left: 0,
            width: window.width,
            height: (window.height/40)*3,
          },
          description: {
            fontWeight: 'bold',
          },
          predefinedPlacesDescription: {
            color: '#1faadb',
          },
        }}

        currentLocation={true}
        currentLocationLabel="Current location"
        nearbyPlacesAPI='GoogleReverseGeocoding'
        GoogleReverseGeocodingQuery={{
        }}
        GooglePlacesSearchQuery={{
        }}


        filterReverseGeocodingByTypes={['street_address']}

        predefinedPlaces={[homePlace, workPlace]}
      />
```

**Comment by myaskevich** [comment]
hi @sooonmitch 

The query parameter `types` is set to `(cities)`, which means it will only search for cities.

Given there're not that much cities starting with 82... in the world, result list gets empty.

You can learn more about available place types here https://developers.google.com/places/web-service/autocomplete#place_types

**Please also note, the example shown in README is designed not to work for most use-cases, but rather to serve the demonstration purpose.**

**Comment by sooonmitch** [comment]
Thank you, gotta love rookie mistakes xD
