### ISSUE TITLE
Small 'x' button for clear input text

### ISSUE THREAD

**Issue by brascene** [FaridSafi/react-native-google-places-autocomplete#109]
How can we add the 'clear text input' button at the right side of text input? Is there an option for this or must be manually made?

Thanks!

**Comment by myaskevich** [comment]
Hi @brascene 

Did you try to search on stackoverflow yet?

**Comment by myaskevich** [comment]
Check out `clearButtonMode` prop on `<TextInput>`.

You can pass this props to the component using `textInputProps` prop.
