### ISSUE TITLE
debouncing

### ISSUE THREAD

**Issue by jnrepo** [FaridSafi/react-native-google-places-autocomplete#110]
is there a way to debounce the calls made by this component?

**Comment by myaskevich** [comment]
Hi
No, there's currently no way to do that.

Sincerely,
Maxim Yaskevich




On Mon, Feb 6, 2017 at 3:33 AM +0300, "Joon Heo" <notifications@github.com> wrote:












is there a way to debounce the calls made by this component?

**Comment by jnrepo** [comment]
@myaskevich thanks for the quick response

**Comment by myaskevich** [comment]
Added in https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/127
Available in v1.2.9
