### ISSUE TITLE
Inside a TextField If text is long its getting cut from start

### ISSUE THREAD

**Issue by jvarshaprdxn** [FaridSafi/react-native-google-places-autocomplete#111]
I'm Using **React Native: ^0.35.0**  for making android application.

I've used **GooglePlacesAutocomplete** 

**What I did:**
Step1: In my first scene I've selected address from list provided by GooglePlacesAutocomplete.
Step 2: In my next scene displayed already selected address in a GooglePlacesAutocomplete TextField.

**Problem I'm facing:**
If address is short, It shows proper from start to end. Please see below screenshot:

**Screenshot 1:**
![addr](https://cloud.githubusercontent.com/assets/13621482/22694124/f8c7434c-ed6b-11e6-8b02-f925ac2aed09.jpg)

but if address is long - **starting text of address getting cut**(text getting cut means horizontally it gets scroll to the right).

**Screenshot 2:**
![address_cut](https://cloud.githubusercontent.com/assets/13621482/22694054/b2baa3da-ed6b-11e6-825e-0e9e24bee7e8.jpg)

**What I want:** Irrespective if address is short or long It(address text) should be showcase from start. It(address text) shouldn't get cut from start. above address(shown in #screenshot 2) should start like shown in the belowed #screenshot 3.

**Screenshot 3:**
![addess](https://cloud.githubusercontent.com/assets/13621482/22693871/0f048846-ed6b-11e6-8fc2-1cebef7b88c8.jpg)

**Comment by myaskevich** [comment]
Hi @jvarshaprdxn 

I tried to reproduce your example, and it look like the text is always cut from the end (as it's supposed to):
<img width="315" alt="screen shot 2017-03-26 at 7 59 55 pm" src="https://cloud.githubusercontent.com/assets/958221/24333357/ed4ac8a0-125e-11e7-9a2e-e2fb5b5c5fc5.png">

Could you paste in some code, so I could see more details?

**Comment by bhavna18** [comment]
Facing the same problem as above for the long text. How to resolve?
Here is the snippet`  <GooglePlacesAutocomplete
          ref="textInput"
          placeholder="Search"
          minLength={2} // minimum length of text to search
          autoFocus={false}
         multiline={true}
          clearButtonMode={'while-editing'}
         // onMove={[0,0]}
          returnKeyType={'search'} 
          listViewDisplayed="false" // true/false/undefined
          fetchDetails={false}
          renderDescription={row => row.description} // custom description render
          onPress={(data, details) => this.onPlaceSearch(data,details)}
            
            getDefaultValue={() => {
            return this.state.newAddress; // text input default value
          }}
        
          onChangeText={this.onChangeText}
          text={this.state.newAddress}`

**Comment by rajeshdevu92** [comment]
This issue is not happening on iOS, but it still occurs on Android. Do you have any solution or workaround?

**Comment by MussadiqAli** [comment]
Getting the same issue? Any workaround or solution?
