### ISSUE TITLE
Is there a way to put the ListView on top of input text?

### ISSUE THREAD

**Issue by khrizt** [FaridSafi/react-native-google-places-autocomplete#112]
Hi,

Sorry if this is an easy question, but I wanted to put the listview on top of the input text because in my app the input text always goes at bottom and results are on top. If possible I'd like to keep styles coherent between inputs.

Thanks

**Comment by myaskevich** [comment]
Hi @khrizt 

I'm afraid it is not possible in current implementation. But I'm sure it would be easy to add. Feel free to send a PR.

**Comment by khrizt** [comment]
Ok, I'll try :)

**Comment by khrizt** [comment]
Hi, I forked the current repo to try to add this option but with the following code the module does not show any place, but current npm version of the package does. Is there something that I need to change?

```
<GooglePlacesAutocomplete
  placeholder={this.props.placeholder}
  minLength={3} // minimum length of text to search
  autoFocus={false}
  listViewDisplayed={true}    // true/false/undefined
  fetchDetails={true}
  //renderDescription={(row) => console.log(row.description)} // custom description render
  onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true
    // console.log(data.description);
    // console.log(details);
  }}
  getDefaultValue={() => {
    return ''; // text input default value
  }}
  query={{
    // available options: https://developers.google.com/places/web-service/autocomplete
    key: 'KEY,
    components: 'country:es',
    language: 'es', // language of the results
    types: 'address', // default: 'geocode'
  }}
  styles={styles}
  currentLocation={false} // Will add a 'Current location' button at the top of the predefined places list
  nearbyPlacesAPI='GooglePlacesSearch'
  GoogleReverseGeocodingQuery={{
  }}
  GooglePlacesSearchQuery={{
    rankby: 'distance',
    types: 'address',
  }}
  filterReverseGeocodingByTypes={['locality', 'administrative_area_level_3']} // filter the reverse geocoding results by types - ['locality', 'administrative_area_level_3'] if you want to display only cities
  enablePoweredByContainer={false} />
```

**Comment by RikNieuwoudt** [comment]
@khrizt, a simple solution would be to set your container style to `flexDirection:'column-reverse`.

**Comment by khrizt** [comment]
@RikNieuwoudt mmm I don't think this is working, at least on my example

**Comment by khrizt** [comment]
@RikNieuwoudt sorry, looks like it did work I was doing something wrong. Thanks a lot!

**Comment by Applifiedindia** [comment]
import React from 'react'
import { SafeAreaView, View, Text } from 'react-native'
import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';

const MAP_KEY = 'YOUR_KEY'

function HomeScreen() {
    return (
        <SafeAreaView style={{ flex: 1 }}>


            <View style={{ position: 'absolute', height: '75%', width: '100%', top: '50%' }}>
                <GooglePlacesAutocomplete
                    placeholder='Search'
                    minLength={5}
                    onPress={(data, details = null) => {
                        // 'details' is provided when fetchDetails = true
                        console.log(data, details);
                    }}

                    query={{
                        key: MAP_KEY,
                        language: 'en',
                    }}
                    fetchDetails={true}
                    styles={{
                        listView: {
                            position: 'absolute',
                            top: '-50%',
                            height: '50%',
                            width: '100%'
                        }
                    }}

                />
            </View>


        </SafeAreaView>
    )
}

export default HomeScreen
