### ISSUE TITLE
is there way to quickly clear text input to type another search?

### ISSUE THREAD

**Issue by sonnguyenit** [FaridSafi/react-native-google-places-autocomplete#113]
**is there way to quickly clear text input to type another search?**
x button like this image 
![xbutton](https://cloud.githubusercontent.com/assets/13761142/22785067/522507a4-ef05-11e6-8825-5bd96a6b48bf.png)

And when i press delete keyboard quickly, this autocomplete doesn't continue working. 
Please fix this Issue.

**Comment by myaskevich** [comment]
Hi @sonnguyenit 

See https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/109

**Comment by zolrath** [comment]
As far as I can tell that prop only functions on iOS, so it doesn't solve the issue/request for Android.
