### ISSUE TITLE
GooglePlacesAutocomplete suggestion list text moving(scrolling) horizontally

### ISSUE THREAD

**Issue by jvarshaprdxn** [FaridSafi/react-native-google-places-autocomplete#114]
I'm Using **React Native: ^0.35.0** for making android application.

I've used **GooglePlacesAutocomplete**

**Problem I'm facing:**
Suggestion list provided by GooglePlacesAutocomplete, Each row content moving(scrolling) horizontally.

**What I want:**
If address is long then I'm able to scroll it left and Right both side. **It should be scroll Left only**. 
If address is short in suggestion list **it shouldn't be scroll Left and Right**.

**Comment by myaskevich** [comment]
Fixed in https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/130

**Comment by myaskevich** [comment]
Check out v1.2.9

**Comment by jvarshaprdxn** [comment]
Thanks @myaskevich @tusharkotlapure
