### ISSUE TITLE
You have a bug

### ISSUE THREAD

**Issue by Jaafar-abusair** [FaridSafi/react-native-google-places-autocomplete#116]
Hi,

I believe in GooglePlacesAutocomplete.js render function

this line 

let { onChangeText, onFocus, ...userProps } = this.props.textInputProps;

should be like this

let { onChangeText, onFocus, userProps } = this.props.textInputProps;

Please fix it and push a new version.

also in your code I can see you have underlineColorAndroid="transparent" for the search TextInput but when i did npm install your last version, this line is missing, do you have the last version on npm?

Thanks

**Comment by myaskevich** [comment]
"You have a bug" doesn't really work as a issue description.

I'd suggest you come back with more details on the subject.

**Comment by Jaafar-abusair** [comment]
It's simple, in your render code, int GooglePlacesAutocomplete.js file, you assign the userProps and you have three (.) before the object and this doesn't work, it should be userProps instead with out three dots and inside the textInput with three dots for extraction as you do.

my scenario, I wanted to assign a specific properties to the textInput so I did the following in my code
<GooglePlacesAutocomplete
textInputProps={{
                             userProps:
                                {underlineColorAndroid : "transparent",
                                autoCorrect : false
                                }
                         }}
... />

And this worked only when I removed the three dots from 
let { onChangeText, onFocus, ...userProps } = this.props.textInputProps;

If you have any suggestion to make this work without removing the three dots. please let me know.

**Comment by myaskevich** [comment]
`userProps` is not a valid `TextInput` prop. See the full list here https://facebook.github.io/react-native/docs/textinput.html#props

**Comment by Jaafar-abusair** [comment]
dude, your wrote this code? you are passing what ever in userProps to the TextInput and that great, but you have small bug which is the three dots, just remove them from the assign code, that's it

**Comment by myaskevich** [comment]
`userProps` is just the name of variable and is not exposed to the component's API.

I'm pretty sure, the issue is on your side. Just pass your props directly to `textInputProps` without wrapping them into `userProp` and you're done.
