### ISSUE TITLE
components /  componentsRestrictions not working

### ISSUE THREAD

**Issue by maurogs** [FaridSafi/react-native-google-places-autocomplete#118]
Trying to limit results by county, but not working...
I want to show only result from spain first, after I wanna try only madrid.
I've tried: componentRestrictions: {country: 'es'}, component: {country: 'es'}, etc..
Any suggestions? Thank you farid and also thanks for your youtube chat video.
Merci
![gplaces](https://cloud.githubusercontent.com/assets/9518552/22866695/fd5b5dcc-f17a-11e6-9009-bb61a5ec0d43.png)

**Comment by myaskevich** [comment]
Hi @maurogs 

See https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/117
