### ISSUE TITLE
Unable to Resolve node modules ?

### ISSUE THREAD

**Issue by lavarajallu** [FaridSafi/react-native-google-places-autocomplete#122]
I have Downloaded Sample file and I have installed Node modules but it's not working ..showing this image
![simulator screen shot feb 23 2017 7 36 26 pm](https://cloud.githubusercontent.com/assets/20550556/23262147/ae11d9c0-f9ff-11e6-8905-463cb58adb29.png)

**Comment by myaskevich** [comment]
Hi @lavarajallu 

Please check you import path and try to refresh packager cache.

I don't think it's the library that causing you troubles.

**Comment by lavarajallu** [comment]
Hello Thanks for your response @myaskevich i gave a exact path and install package also...
