### ISSUE TITLE
Unrecognized font family 

### ISSUE THREAD

**Issue by mmoravec** [FaridSafi/react-native-google-places-autocomplete#124]
I'm trying to import a font family into the input like so:

           styles={{
             textInput: {
               fontSize: 16,
               fontFamily: 'LatoRegular',
             },
           }}

and I get an error `Unrecognized font family 'Lato'`. I use my custom font elsewhere in my project. Anyone know whats going on?

**Comment by myaskevich** [comment]
Hi @mmoravec 

Anything you put into `styles.textInput` is passed without changes directly to the underlying `<TextInput>` component style prop.

So it is not probably the library to blame. Check you font importing setup in XCode.
