### ISSUE TITLE
accuracy of search

### ISSUE THREAD

**Issue by s-ostrovsky** [FaridSafi/react-native-google-places-autocomplete#132]
is it possible to limit range of search query by distance, or may be by city (country etc.)?

**Comment by myaskevich** [comment]
Hi @s-ostrovsky 

Yes, take a closer look at the example in README:
```
        query={{
          // available options: https://developers.google.com/places/web-service/autocomplete
          key: 'YOUR API KEY',
          language: 'en', // language of the results
          types: '(cities)', // default: 'geocode'
        }}
```

For the full list of query options available, refer to [Google Places Autocomplete API docs](https://developers.google.com/places/web-service/autocomplete#place_types).
