### ISSUE TITLE
Use `renderDescription` for the TextInput text as well

### ISSUE THREAD

**Issue by globetro** [FaridSafi/react-native-google-places-autocomplete#141]
It looks like there's a fix for this already: https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/9197bbb0866f7da968b240f559a8cdae749d603c/GooglePlacesAutocomplete.js#L349 but just not released yet. Are there any issues that's blocking this from being released?

**Comment by myaskevich** [comment]
Hi @globetro 

Check out v1.2.12.
