### ISSUE TITLE
Filter results by types

### ISSUE THREAD

**Issue by sifrenette** [FaridSafi/react-native-google-places-autocomplete#142]
There should be a way to filter the results. In the same way we can use the filterReverseGeocodingByTypes prop, it would be nice if there would be a filterResultsByTypes prop to filter the normal results. 

Btw, in my use case, we can't use the 'types' property in the query to filter the results, because google api doesn't support filtering by address + city (it will also be deprecated soon).

I can make a pull request.

**Comment by guilhermepontes** [comment]
Please do!

**Comment by tgreco** [comment]
@sifrenette @guilhermepontes was this ever implemented? 
How to use it?

**Comment by githistory** [comment]
@sifrenette @guilhermepontes was this ever implemented please?
