### ISSUE TITLE
Allow Font Scaling To Be Turned On & Off

### ISSUE THREAD

**Issue by zzimbler** [FaridSafi/react-native-google-places-autocomplete#145]
Allow font scaling to be turned on or off as a setting for and Text elements the libraries utilizes.

Example of massive font sizing making it impossible to read the autocomplete selections:
![img_0159](https://cloud.githubusercontent.com/assets/538636/25597249/f5391506-2e8a-11e7-950f-ef34c3d6a6c2.PNG)

**Comment by zzimbler** [comment]
I would happily submit a pull request for this, but closing as a wontfix basically says your library won't support accessibility features and immediately makes it not useable for any application that needs to support that (which is eventually all apps in production, even though we're talking about maybe <1% of users)

**Comment by guilhermepontes** [comment]
@zzimbler sorry for being such stupid. It's really important, I just didn't realize that. I would be happy to see a pull-request for that. :)

Sorry again!

**Comment by zzimbler** [comment]
👍 might take me a few weeks, I will only have time on the weekends to try and fix this

**Comment by guilhermepontes** [comment]
No worries!
