### ISSUE TITLE
Onblur implementation missing?

### ISSUE THREAD

**Issue by oatcrunch** [FaridSafi/react-native-google-places-autocomplete#149]
Hi,

Are we missing the implementation for "onblur"? When search results are displayed, then when I unfocus the search text box, the search results are still being displayed. I suppose we should make it disappear when the search textbox is not being focused?

Thanks and regards.

**Comment by akajack** [comment]
same issue :\

**Comment by guilhermepontes** [comment]
You can use the `textInputProps` prop.
Example:

```jsx
<GooglePlacesAutocomplete
  textInputProps={{
    onFocus : () => console.log('focused'),
    onBlur  : () => console.log('blurred')
  }} 
/>
```
