### ISSUE TITLE
textInputProps & clearButtonMode

### ISSUE THREAD

**Issue by Taakn** [FaridSafi/react-native-google-places-autocomplete#150]
Hello,
This does not work as intended:

  ```
        textInputProps={{
            clearButtonMode: 'never'
          }}
```
Thanks

**Comment by Mellemel** [comment]
I submitted a pull request to fix this, https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/153, but if you need a fix for it now, just follow the changes in that commit.

**Comment by Taakn** [comment]
Thanks !
