### ISSUE TITLE
Clear the form

### ISSUE THREAD

**Issue by jonidelv** [FaridSafi/react-native-google-places-autocomplete#155]
Is there a way to clear the input ? let say once I submitted the form I want to clear the input.

**Comment by ujwal-setlur** [comment]
I want this too

**Comment by delvallejonatan** [comment]
You can do this: 
1) The component that you are using `<ReactNativeGooglePlacesAutocomplete />`  need to be a class component.
2) Then add a ref to the component like this `<ReactNativeGooglePlacesAutocomplete ref={(instance) => { this.GooglePlacesRef = instance }}/>`
3) When you need to clear the input just `this.GooglePlacesRef.clearInput()`

**Comment by ujwal-setlur** [comment]
Thanks for the tip! This worked, but I had to do a ```this.GooglePlacesRef.setAddressText("")```. There was no ```clearInput()``` in the **react-native-google-places-autocomplete** component.

**Comment by delvallejonatan** [comment]
@ujwal-setlur  Maybe they changed the component methods, I tried this like 1 month ago. Glad it works 😀

**Comment by sagomezza** [comment]
@jonidelv  Can you provide a complete example of your solution? I'm new with RN so I don't get it so easily.

**Comment by prospteam** [comment]
> @ujwal-setlur Maybe they changed the component methods, I tried this like 1 month ago. Glad it works 😀

i would like to ask where can i find a documentation where "setAddressText" can be found,
i cant find it here,

**Comment by orsospatrick** [comment]
1) <GooglePlacesAutocomplete ref={(instance) => { this.GooglePlacesRef = instance }}/>

2) At onPress use this.GooglePlacesRef.setAddressText("").

Work for me

**Comment by fbotalla** [comment]
How can I go about doing this without having a class component?

**Comment by mirfanahmed** [comment]
Hello. How can we clear the results of the search? setAddressText("") only clear the textinput text only.

**Comment by amiradgham** [comment]
i got  this.GooglePlacesRef is indefined how can i fix that anyone can help ?

**Comment by Francefire** [comment]
> i got this.GooglePlacesRef is indefined how can i fix that anyone can help ?

this.GooglePlacesAutocomplete use this instead, the named changed

In case this happens again just take a look at the source code of the component (GooglePlacesAutocomplete.js)

**Comment by vajda-media** [comment]
Newly you have to use: googlePlacesRef.current.changeValue(''); to reset the inputfield value.
