### ISSUE TITLE
getDefaultValue not rerender with state value change

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [FaridSafi/react-native-google-places-autocomplete#158]
We are using RN: 0.40.0.
Is there any way by which we rerender default value after first time render <GooglePlacesAutocomplete /> ?
We are trying to update default value in GooglePlacesAutocomplete   "getDefaultValue" attribute by changing state value.

  Can anyone suggest any solution?

**Comment by matthiasprieth** [comment]
Same Problem here

**Comment by matthiasprieth** [comment]
Ok i wrapped a condition around so that it renders only when the default value is ready. Not an elegant version, but works for now. 
```
{this.props.defaultValueReady ? (
    <GooglePlacesAutocomplete
         query={{
         ...
     />
) : <View></View>}    
```

**Comment by matthiasprieth** [comment]
@MSSPL-PiyaleeMaiti but i think all in all you are wright there is no way of setting the autocomplete input field later on from outside/state you can just set it by typing in text as i understood

**Comment by janvdt** [comment]
Are you still working on this? I have the same issue

**Comment by noambonnie** [comment]
You can use setAddressText("...").

On your autocomplete component get a reference to the object:
`<GooglePlacesAutocomplete ref={(instance) => { this.locationRef = instance }} .../>` 

and then: 
`this.locationRef.setAddressText("New York, NY")`

**Comment by janvdt** [comment]
Thanks that worked!

**Comment by dgpoo** [comment]
@noambonnie Thanks it worked

**Comment by eneasharrais85** [comment]
@noambonnie I can´t get it to work, when I try this:

<GooglePlacesAutocomplete
ref={(instance) => { this.GooglePlacesRef = instance }}
getDefaultValue={() => {
                  this.GooglePlacesRef.setAddressText("Something")
                  }}

I get an error Cannot read property 'setAddressText' of undefined

**Comment by murtazaezzy** [comment]
@noambonnie Thanks a TON !! Saved my day :)

**Comment by NeenaMishra12** [comment]
> You can use setAddressText("...").
> 
> On your autocomplete component get a reference to the object:
> `<GooglePlacesAutocomplete ref={(instance) => { this.locationRef = instance }} .../>`
> 
> and then:
> `this.locationRef.setAddressText("New York, NY")`

Where to do this after setting reference?
> `this.locationRef.setAddressText("New York, NY")`

**Comment by bell-steven** [comment]
@NeenaMishra12 see [this](https://snack.expo.io/@sbell/react-native-google-places-autocomplete---ref) example.

**Comment by NeenaMishra12** [comment]
> @NeenaMishra12 see [this](https://snack.expo.io/@sbell/react-native-google-places-autocomplete---ref) example.

Yes have checked this but, how to add it using state ?

**Comment by logan0900** [comment]
I got error in Function based component:

pickupRef.current.setAddressText is not a function. (In 'pickupRef.current.setAddressText('qwerty')', 'pickupRef.current.setAddressText' is undefined)
![Simulator Screen Shot - iPhone 13 - 2022-12-15 at 05 53 15](https://user-images.githubusercontent.com/58814997/207746928-cf9d809d-6f00-41c2-90fe-93fceead23b7.png)
