### ISSUE TITLE
How to position "powered by google"?

### ISSUE THREAD

**Issue by ahmed1490** [FaridSafi/react-native-google-places-autocomplete#16]
<img width="282" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/13730930/e6c0b218-e95d-11e5-827b-68e8637e87c7.png">

**Comment by MustaphaGhlissi** [comment]
Add this style to styles prop 

```
 poweredContainer: {
     justifyContent: 'center'
 } 
```
