### ISSUE TITLE
Warning: GooglePlacesAutocomplete: isMounted is deprecated

### ISSUE THREAD

**Issue by jakecraige** [FaridSafi/react-native-google-places-autocomplete#162]
Seeing this error when upgrading to react 16.0.0-alpha.12 and react-native 0.45.0.

> Warning: GooglePlacesAutocomplete: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

It's referring to this line in the specific error, but will come up for the other places this is checked as well. https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L529

**Comment by iMokhles** [comment]
you can disable the yellow box by adding this line

```
// disable yellow box
console.disableYellowBox = true;
```

inside your index.ios.js and index.android.js

cheers

**Comment by ujwal-setlur** [comment]
You should not do that. That will disable all yellow box warnings, things that need fixing. The correct fix here is to fix the isMounted() reference in this code.

**Comment by ujwal-setlur** [comment]
I have issued a PR: https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/178

**Comment by williamwlchan** [comment]
Having the same issue here after updating expo to v18.0.1

**Comment by Clowning** [comment]
Sadly, i think this component is no longer maintained :/

**Comment by Jamongkad** [comment]
Damn what timing for this component to _not_ maintained. Has anybody made a fork and fixed the this issue?

**Comment by ujwal-setlur** [comment]
Please look at my fork. I have submitted a pull request, but it has not been merged.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jamongkad** [comment]
ok will check it out! :)

**Comment by jsappme** [comment]
+1

**Comment by guilhermepontes** [comment]
Fixed by `1.3.0`
