### ISSUE TITLE
OnChangeText

### ISSUE THREAD

**Issue by eyalabadi98** [FaridSafi/react-native-google-places-autocomplete#165]
Hello, 

I am using redux with your Autocomplete component, and I'm looking for a prop, just like in InputText, that allows me to set the value and a prop that tells me when text has changed.

I am trying to pass this on my view:
onChangeText={endGoogle => this.props.DriverAddForm({ prop: 'endGoogle', value: endGoogle })}

but it is not getting triggered. How can I make this work? onPress is not working either

Here is my code:
```jsx
<GoogleAutoComplete
  //placeholder='Start'
  placeHol="End"
  minLength={2}
  autoFocus={false}
  returnKeyType={'default'}
  fetchDetails
  onChangeText={endGoogle => this.props.DriverAddForm({ prop: 'endGoogle', value: endGoogle })}
  value={this.props.endGoogle}
  onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true
  console.log('data is +' + data.formatted_address);
  //console.log('details is')

  }} />
```

and I have a component called GoogleAutoComplete which has the example code plus  onChangeText={this.onChangeText}

Thank you

**Comment by cbartondock** [comment]
This ^. Have you found a work around?

**Comment by eyalabadi98** [comment]
Yeah, I did  
`onPress={(value) => this.props.DriverAddForm({ prop: 'stopOverGoogle', value: value.description })}`
