### ISSUE TITLE
Warnings: isMountent, Invalid PropType for TextInput, Can only update a mounted component

### ISSUE THREAD

**Issue by AdrianZghibarta** [FaridSafi/react-native-google-places-autocomplete#167]
Hi guys, I have some errors using this library:
![simulator screen shot jun 22 2017 2 37 17 pm](https://user-images.githubusercontent.com/11558151/27432368-87ff7ee8-5758-11e7-9956-ffc66b088629.png)
![simulator screen shot jun 22 2017 2 37 21 pm](https://user-images.githubusercontent.com/11558151/27432370-8802a9ce-5758-11e7-80b0-ae3cf4a58e5d.png)
![simulator screen shot jun 22 2017 2 37 30 pm](https://user-images.githubusercontent.com/11558151/27432369-8800a156-5758-11e7-80f3-86cb0777a5d5.png)

**Comment by kidmysoul** [comment]
I have the first one too. Does this library still be maintained?

**Comment by arrayewhy** [comment]
Same here!

**Comment by guilhermepontes** [comment]
Will be fixed by `1.3.0`.

**Comment by lfkwtz** [comment]
Using latest version, I'm still getting this error ---

![simulator screen shot - iphone se - 2018-01-05 at 09 39 38](https://user-images.githubusercontent.com/1746853/34616020-6b4ca17e-f1fc-11e7-8ed0-9acc80e79a0c.png)
