### ISSUE TITLE
Is there a way to determine if autocomplete results = 0

### ISSUE THREAD

**Issue by kcfgl** [FaridSafi/react-native-google-places-autocomplete#168]
Love this library so thank you!  Maybe I'm missing this in the docs, but what I'm looking to do is present some text and a button when the autocomplete results return 0.

For example: a user is searching for a specific place. after entering the entire place name, there are no results. So I want to show something like "Can't find your place? Add it!" and a button. 

Is that possible?  Thanks!

**Comment by schneck** [comment]
I think you can use the `onNotFound` prop: https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L89

**Comment by sa2812** [comment]
Sorry to bring this back up after it's already closed, but the `onNotFound` prop adds a method inside the `_onPress` method and so if there are no results, it will never be called.

Is there something I'm missing? Side note, should I repost this as a new issue?
