### ISSUE TITLE
Custom styling of TextInput and result list

### ISSUE THREAD

**Issue by rohitgoyal** [FaridSafi/react-native-google-places-autocomplete#17]
Great job with this plugin. 
I don't know whether custom styling is possible in this yet or not? If yes it would be pretty helpful if you can put this in documentation on how to do it.
i simply tried to put autoCorrect to false by putting "autoCorrect:false," into textInput style but got the invalid props.style key autoCorrect supplied to TextInput.

**Comment by kvieira90** [comment]
It is possible. Ready through the source code, he has prop hooks for the styles you can pass. I agree, there should be better documentation on this but not too hard to find if you try.

**Comment by jamesone** [comment]
I just went in the source and edited it myself...was too lazy to add custom props!

**Comment by dimonge** [comment]
We can also help with the documentation whenever possible, its part of our contribution to the lib. 👍

**Comment by myaskevich** [comment]
Hi @dimonge @kvieira90 !

Sure! If you could add a little snippet to the documentation, it'd be awesome!
I'll gladly merge it.

**Comment by nak1b** [comment]
@myaskevich  added documentation for styling the component here [PR](https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/53)

**Comment by myaskevich** [comment]
Thanks a lot @nak1b
