### ISSUE TITLE
Can't get loading spinner to show up

### ISSUE THREAD

**Issue by michaelcarter** [FaridSafi/react-native-google-places-autocomplete#174]
First of all, thanks for your great work on this component.

We're having a bit of trouble getting any sort of activity indicator to show in our app while it fetches locations from Google's API using version `1.2.12` of `react-native-google-places-autocomplete`. Here's the code we're using to include it:

```javascript
<GooglePlacesAutocomplete
  placeholder={this.props.placeholder || 'Enter Location'}
  minLength={2}
  autoFocus
  listViewDisplayed='auto'
  fetchDetails
  enablePoweredByContainer={false}
  renderDescription={(row) => row.description}
  textInputProps={{
    autoCorrect: false
  }}
  onPress={(data, details = {}) => this._setDetails(details)}
  query={{
    key: googleMapsKey,
    language: 'en'
  }}
  styles={placesStyles}
  nearbyPlacesAPI='GooglePlacesSearch'
/>

const placesStyles = {
  textInputContainer: {
    height: 40
  },
  textInput: {
    borderRadius: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    height: 40,
    borderWidth: 1,
    borderColor: colors.grey,
    fontFamily
  },
  description: {
    fontFamily
  }
}
```

Looking at the source code for the component, it looks like you're doing a `if (rowData.isLoading === true) {` check within the `_renderLoader` function. When I insert a `console.log` here, this is always undefined for me. However, if I change the equality check to `if (true) {` I still never see an `ActivityIndicator` rendered, even if simulate a really slow connection.

Aside from this, everything seems to work as we'd expect, we can get results back just fine as you can see from the screenshot below:

![screen shot 2017-07-03 at 16 35 17](https://user-images.githubusercontent.com/1911741/27799892-eb95dc22-600e-11e7-818b-ff9cad5c688a.png)

Any help anyone could offer would be very much appreciated. This is causing a poor user experience in our app at the moment for users with slow connections.

**Comment by gitlovenotwar** [comment]
Hi, are you able to workaround to show loader when it's searching?

**Comment by guilhermepontes** [comment]
The spinner is related to the `onPress` event of an item. But it's good to have this kind of feeding.
I think the loading it's not added because it's hard to find a good ux for it since the load it's supposed to appear in the `onChange` event, which might clean all the places you already have. 

Maybe the usage of the `NetworkActivityIndicatorVisible` ([here](https://facebook.github.io/react-native/docs/statusbar.html#networkactivityindicatorvisible) - iOS only) might be a good thing to add.

Otherwise, can you give me some ideas about a good place to put the loading indicator?

**Comment by linux08** [comment]
Hi guys, I am also stuck on this issue.Anyone found a solution?

**Comment by paras-kc** [comment]
I would say if you can make a progress bar under the textinput container or something custom so that whosoever wants to add a loader can add as per their own accordance.
