### ISSUE TITLE
React Native Google Places API restriction issue

### ISSUE THREAD

**Issue by Bertjuhh** [FaridSafi/react-native-google-places-autocomplete#176]
I get the following error while using "React Native Google Places autocomplete".
"This IP, site or mobile application is not authorized to use this API key...".

I'm using a Google Places API Web Service key, which restrictions on Android-App. This one is restricted with the package name "com.xxx.xxx.debug" and "com.xxx.xxx.test". Another API key is restricted to "com.xxx.xxx". I've added the proper SHA-1 key.Anyone has a clue what I'am doing wrong or why it doesn't work? 

I've checked the docs of Google and tried out many different things, still I cannot get it to work with a restriction.
Question also asked on [SO](https://stackoverflow.com/questions/45028935/react-native-google-places-api-restriction-issue)

**Comment by guilhermepontes** [comment]
I think it was fixed by #170. It's available on version `1.3.0`
