### ISSUE TITLE
Add feature to render the places on different component

### ISSUE THREAD

**Issue by gitlovenotwar** [FaridSafi/react-native-google-places-autocomplete#177]
Hi, is it possible to add the said feature on the title? I have a view that's independent to the search area. It should be able to render the list on different component and display it there.

**Comment by gitlovenotwar** [comment]
Or rather call the core api to get the list?

**Comment by gitlovenotwar** [comment]
Hi, is it possible to add these features? This is really necessary... Where the input and the list are separated or apart from each other. The must have an option to render on a custom view.

**Comment by gitlovenotwar** [comment]
This is the only library I found working perfectly. Please help.

**Comment by nschurmann** [comment]
Same here!

**Comment by guilhermepontes** [comment]
I think this is a different approach for what this library does. You can use the API to build a custom component by yourself. 

https://developers.google.com/places/web-service/search
