### ISSUE TITLE
i dont know why but i can't get it running, I keep running into weird issues like following.

### ISSUE THREAD

**Issue by jpca999** [FaridSafi/react-native-google-places-autocomplete#179]
do you have an example repo where i can see it running via my expo app ?

![image](https://user-images.githubusercontent.com/1026325/28282359-2b217786-6af8-11e7-97f7-5410a34b9a72.png)

**Comment by guilhermepontes** [comment]
This is a npm issue, try deleting the `npm_modules` and re-installing everything again.
