### ISSUE TITLE
How to close the autocomplete dropdown?

### ISSUE THREAD

**Issue by tomazahlin** [FaridSafi/react-native-google-places-autocomplete#18]
I have a scenario, where the user can input something in the textbox and he can:
 - choose something from the dropdown (works ok)
 - not choose anything and type his own custom text (not sure how to close the dropdown with suggestions without clicking on any of the suggestions)

I can easily write a PR to solve this, by adding a onEditingEnd prop on TextInput and setting the state.listViewDisplayed to false. Does this sound okay, should I make a PR? I can also do that all this is enabled when setting a prop to the GooglePlacesAutocomplete, to keep backwards compatibility.

**Comment by FaridSafi** [comment]
Hello, as you wish since there is still backward compatibility

**Comment by tomazahlin** [comment]
Here is a PR: https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/19

I have tested it and works nice, you can try it too before merging.

**Comment by tomazahlin** [comment]
Looks like here is an issue with selecting a  value, sorry about that. Will try to fix it.

**Comment by tomazahlin** [comment]
Seems it is not so easy to fix. With my PR, when clicking on any suggestion, the onEndEditing is executed, which first hides the suggestions, and then it is not selected. Do you have any suggestions how to fix this? I tried a few approaches, but no luck yet.

**Comment by myaskevich** [comment]
Hi @tomazahlin !

Using `onEndEditing` event handler doesn't quite fit for this purpose. It'll fire in both cases: when you leave text input and select an item from dropdown list.

Currently if you type random text without selecting any suggested places, it'll remain unchanged.

If you need to hide the dropdown, you'll need to do it manually (button press, etc.).

**Comment by shettyrahul8june** [comment]
@myaskevich How can we do it with a button press? Note that I have installed the package. I went through the source code and I see that _onBlur is the only way through which we can hide the listView. Can you let me know whether there is any option available for us to hide the list by maybe passing a state to the component?

**Comment by myaskevich** [comment]
Great news everyone!

I found some time to look at the problem and has eventually put together a simple solution: `listViewDisplayed` prop.

Available in v1.2.4

**Comment by Vishal1419** [comment]
@myaskevich @FaridSafi I have created a variable called shouldDisplayListView and set listViewDisplayed to that as shown in code below:

```
let shouldDisplayListView = false;
<GooglePlacesAutocomplete listViewDisplayed={shouldDisplayListView}
    textInputProps={{
        onFocus: () => shouldDisplayListView = true;
        onBlur: () => shouldDisplayListView = false;
    }} ............ />
```

But still I cannot see the listView. Instead if I set listViewDisplayed to "auto" then I can see the listView. But then onBlur of textInput I am unable to hide it.

**Comment by nbaghiro** [comment]
[https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/293](url)

**Comment by MSSPL-PiyaleeMaiti** [comment]
listViewDisplayed={shouldDisplayListView} this solution is not working for me.
Can anyone suggest any solution? 
In my emulator when I tap on location from the suggestion list then the list is closed. But in my phone after clicking on location from suggestion list the list is opened as well not closed. What is the problem I can't understand, please suggest anyone any solution.
I am using :  
  `` react-native : 0.54.4
   "react-native-google-places-autocomplete": "^1.3.6",``

**Comment by Parmar-Bansi** [comment]
> listViewDisplayed={shouldDisplayListView} this solution is not working for me.

same here in my case also
any other solution..??

**Comment by cchoe1** [comment]
I also found that listViewDisplay={false} does not cause the list view to hide.  But you can call one of the methods if you set a ref

`ref.current.blur()`

It seems to hide the list by blurring, as expected but it seems to be very hard to actually blur the input field without clicking a result from the list.  So manually blurring worked for me
