### ISSUE TITLE
How can I get data and detail when I use it as a child component?

### ISSUE THREAD

**Issue by kyooryoo** [FaridSafi/react-native-google-places-autocomplete#180]
I use this lib as a component and import it to a container. It works fine, but how could I get the data and detail objects of this component from its parent container?
I guess I should put something in onPress and use {...this.props} when I refer it in container, but just have no clue how to achieve it.

**Comment by guilhermepontes** [comment]
https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/177#issuecomment-324329315
