### ISSUE TITLE
ListView should be tappable when keyboard is up(android)

### ISSUE THREAD

**Issue by gitlovenotwar** [FaridSafi/react-native-google-places-autocomplete#183]
Hi, please allow the list to tap only once. Right now on android, when keyboard is up, the list of places have to be tapped twice in order to select the place. I'm thinking it must be because of the scrollview you used, please add the keyboardShouldPersistTaps to 'always' or 'handled'

**Comment by guilhermepontes** [comment]
[It is](https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L765). [And you can use configure it](https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L573).

**Comment by PC98** [comment]
@guilhermepontes I am having this same issue, despite setting `keyboardShouldPersistTaps` to "always". Here is my code:
```
    <GooglePlacesAutocomplete
      placeholder=""
      onPress={(data, details = null) => {
        // 'details' is provided when fetchDetails = true
        console.log(data, details);
      }}
      getDefaultValue={(): string => value}
      query={{
        key: MY_KEY,
        types: "address"
      }}
      styles={{
        textInputContainer: {
          backgroundColor: "white",
          borderColor: "gainsboro",
          borderWidth: 1
        },
        textInput: {
          paddingLeft: 0,
          paddingRight: 0,
          paddingBottom: 0,
          paddingTop: 0,
          fontSize: 18
        },
        description: {
          fontSize: 16
        },
        listView: {
          backgroundColor: "white"
        }
      }}
      debounce={200} // debounce the requests in ms. Set to 0 to remove debounce. By default 0ms.
      enablePoweredByContainer={false}
      keyboardShouldPersistTaps="always"
    />
```
Any thoughts on what could be going wrong here?
