### ISSUE TITLE
Getting unit/apartment #

### ISSUE THREAD

**Issue by nloui** [FaridSafi/react-native-google-places-autocomplete#186]
Hi there,

Curious if there's a way to get unit/apartment number in the Google places autocomplete results?  For some reason, I can't find any docs on this.

Thanks!

**Comment by timsaval** [comment]
same

**Comment by guilhermepontes** [comment]
I don't think it's possible.

**Comment by samernady** [comment]
hey, any update on this? 
Whenever I pick an address even if it has the apartment number the autocomplete results override the apartment number and only show the building number.
