### ISSUE TITLE
need postal code in auto complete suggestions 

### ISSUE THREAD

**Issue by PatelAtit2017** [FaridSafi/react-native-google-places-autocomplete#187]
Hi there,

Is there's a way to get postal code (zip code) in the Google places autocomplete results?  I can't find any docs on this.
tried with types as : type: 'address',  types: '(cities)',  no luck
Thanks

**Comment by guilhermepontes** [comment]
I don't think so.

**Comment by bYemma** [comment]
@guilhermepontes @PatelAtit2017 Is there a solution to this question?

**Comment by harshvitra** [comment]
@bYemma @PatelAtit2017 Did you guys found a work around.

**Comment by bYemma** [comment]
No, sorry. No solution found for this problem.

**Comment by ThirumuruganPK** [comment]
i am also facing this same issue

**Comment by bell-steven** [comment]
The Google Autocomplete API does not provide the postcode

**Comment by Suhailattatras** [comment]
Guys what I did is after calling the autocomplete API where I get latitude and longitude so by using these latitude, longitude I again made a call to google's reverse geocoding that give me the postcode for the location. You can try this.

**Comment by Suhailattatras** [comment]
Guys what I did is after calling the autocomplete API where I get latitude and longitude so by using these latitude, longitude I again made a call to google's reverse geocoding that give me the postcode for the location. You can try this.

**Comment by bell-steven** [comment]
You can also use the `fetchDetails` prop to call the Place Details API. The postcode will be available in the second paramater of `onPress`.
