### ISSUE TITLE
This package is not working on latest react-16 and react-native 0.47.1

### ISSUE THREAD

**Issue by shameemz** [FaridSafi/react-native-google-places-autocomplete#188]
Due to lot of deprecation  from react and react-native, this package is not compatible for react 16 and react-native 0.47.1

**Comment by grigored** [comment]
my fork works, just put this in your package json "react-native-google-places-autocomplete": "git+https://github.com/grigored/react-native-google-places-autocomplete.git",

**Comment by manfye** [comment]
@grigored  just add this? "react-native-google-places-autocomplete": "git+https://github.com/grigored/react-native-google-places-autocomplete.git", 

no need do npm?

**Comment by grigored** [comment]
of course you need to do npm install

**Comment by vivanov1410** [comment]
@grigored I am using your fork, component renders but as I type no places show up. Is it working fine for you? Maybe you can provide a code example?

**Comment by grigored** [comment]
Do you see anything in the console? Maybe you didn't put any api key?

**Comment by guilhermepontes** [comment]
Will be fixed by `1.3.0`.
