### ISSUE TITLE
on focus

### ISSUE THREAD

**Issue by ellismarte** [FaridSafi/react-native-google-places-autocomplete#194]
How can I know when a user has clicked on the search bar? on press seems to only be for when they hit search or done, but i need to take an action when they just click on the search bar.

**Comment by kirakik** [comment]
Add `onFocus` inide `textInputProps`

```
textInputProps={{
    onFocus: () => yourCallback(),
}}
```

**Comment by MaxInMoon** [comment]
Do you know how to retrieve an `event` arg in `onFocus` function?  Thank you

**Comment by hecmonn** [comment]
Were you able to find how? @MaxInMoon

**Comment by vaibhavgadekar** [comment]
> textInputProps={{
>     onFocus: () => yourCallback(),
> }}

Most Useful thank you

**Comment by colinmatthewlee** [comment]
Still can't seem to retrieve the event arg in the onFocus function, anyone have any idea?

**Comment by dsws** [comment]
I did something like this, works ok

    return (
      <View
        onLayout={event => {
          const layout = event.nativeEvent.layout;
          setLocationFieldY(layout.y);
        }}>
        <LocationField
          props={{
            onInputFocus: e => {
                props.scrollToLocation(locationFieldY);
            },
