### ISSUE TITLE
Using onChangeText in the textInputProps breaks the autocomplete

### ISSUE THREAD

**Issue by kirakik** [FaridSafi/react-native-google-places-autocomplete#196]
I am trying to retrieve the text from the input, in order to validate it (e.g., if the user presses on the clear button, I would like the confirmation button to be disabled). However, when trying to use `onChangeText` prop inside the `textInputProps`, it breaks everything. The text in the input no longer changes as you type. I tried working around that by adding the `value` prop inside the `textInputProps`, which is updated as you type, but the autocomplete list does not show up anymore. This is quite critical, as it prevents clients from having full control of the UX when an autocomplete field is being used.

Is there a way around this? Could I potentially get the input field value another way?

Thank you

**Comment by AdamPD** [comment]
Submitted PR #205

**Comment by guilhermepontes** [comment]
fix on `1.3.5`

**Comment by r0bbarnk** [comment]
This is still a problem though. There is no way to read the input to the textfield as doing:
```
textInputProps={{
     onChangeText: (text) => this.handleTextInput(text),
}}
```
Will override the "onChange" and "onChangeText" in the .js file for the package.

Is there anyway around this? I need to read the input text to trigger some important functions in my app. But of course I would also like to autocomplete list to appear...

using:
`"react-native-google-places-autocomplete": "^1.3.6",`
in package.json

**Comment by ajaysaini-sgvu** [comment]
@r0bbarnk Have you got solution for this issue ?

**Comment by r0bbarnk** [comment]
@ajaysaini-sgvu I ended opp changing the sourcefiles for this repo and make my own "onChangeText".

**Comment by trinhhien272** [comment]
Hi , I am having this same problem as in version 1.3.9.

Can console value textInput. But Cannot execute any method.

`textInputProps={{
          onChangeText: text => {
            console.log(text);
            this.props.screen._changeKeyword(text);
          }
        }}`
