### ISSUE TITLE
Trigger when clearing text input

### ISSUE THREAD

**Issue by huyvohcmc** [FaridSafi/react-native-google-places-autocomplete#199]
Hi, I want to make a trigger when a user

1. Search for an address
2. Choose an address
3. Clear the text in text input

I tried `onChangeText={(text) => console.log(text)}` but it doesn't works :'(

**Comment by guilhermepontes** [comment]
https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/149#issuecomment-324326038

Can you tell me if this solves your problem?

**Comment by huyvohcmc** [comment]
@guilhermepontes Yes, it is, thank you, sir.
