### ISSUE TITLE
Current Location Suggestions: Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by KhalilKhalaf** [FaridSafi/react-native-google-places-autocomplete#200]
So I upgraded From 1.2.6 into 1.3.2 and now when I go to a screen that has `GooglePlacesAutocomplete` Component, and I click on Current Location to see nearby locations, it pops a warning saying the each child of the FlatList should have a unique key.

**Code:**

```
<GooglePlacesAutocomplete
    placeholder="Search"
    minLength={4}
    autoFocus={false}
    fetchDetails={true}
    onPress={this.handleUpdateLocation.bind(this)}
    query={{
        key: GOOGLE_PLACES_API_KEY,
        language: 'en', // language of the results
    }}
    
    // home & work values are hard coded above (top of the file)  
    currentLocation={true} 
    currentLocationLabel="Current Location"
    predefinedPlaces={[HOME_LOCATION, WORK_LOCATION]} // will add two predefined (hard coded) locations, home & work.
/>
```

**Behavior:**
![1](https://user-images.githubusercontent.com/14429474/30218205-6cc26e0e-9486-11e7-9b4b-794070ef8e08.gif)

**Warning:**

![simulator screen shot sep 8 2017 11 10 31 am](https://user-images.githubusercontent.com/14429474/30218188-61ffa19e-9486-11e7-8853-66afa0ea2fd0.png)

**Comment by guilhermepontes** [comment]
Fixed by #192. I will release a new version soon :D
Thank you for your message.

**Comment by KhalilKhalaf** [comment]
@guilhermepontes  HI and thanks, 

when are you planning to release? As it looksl ike most of the results are being whipped out. In my above GIF, the final results are pretty far away locations from my current location. And if we look closely on the GIF, it seems like it loads ALL results, but then removes some and pops the warning. 

Please and thanks again

**Comment by guilhermepontes** [comment]
I just released it, @KhalilKhalaf.

**Comment by guilhermepontes** [comment]
Please use version `1.3.4`
