### ISSUE TITLE
Input Text is cleared while typing after update 1.3.3

### ISSUE THREAD

**Issue by Lowisoft** [FaridSafi/react-native-google-places-autocomplete#201]
Hi, after the update to 1.3.3, your module seems to not work anymore. The exactly problem is that the Input Text is cleared while I'm typing.
So, you've probably changed something in your update that causes this bug.
 I hope that you can fix this soon.
Thanks.

**Comment by Lowisoft** [comment]
I'm closing this issue, because I'm using an Interval function that triggers every second a rerender and this probably doesn't match with your module anymore (after the update). 
After stopping the Interval function, your module works as before. 
So, in my case, I've found a workaround. 
Thanks for the work that you put in this module.

**Comment by guilhermepontes** [comment]
@Lowisoft, I just tested what you said it was really happening. I just created a bugfix version, you can use the `1.3.4`.

Thank you for your issue!

**Comment by Lowisoft** [comment]
@guilhermepontes Unfortunately, the 1.3.4 version doesn't fix the issue with the interval in my case. The same code runs fine with 1.3.2, but not with 1.3.3 or 1.3.4. As mentioned before, I've found a workaround and therefore it isn't affecting me anymore.
However, the spinner, that you added in the 1.3.3 version, has disappeared in the 1.3.4 version.
So, I hope that you re-add the spinner soon, because in the 1.3.3 version, it worked perfectly.
Thank you for your quick response!

**Comment by AdamPD** [comment]
This is happening for us in version 1.3.4 too.  I can't type anything in the text input at all.  I will debug this issue and see if I can work out what change broke it.

**Comment by AdamPD** [comment]
This is the same issue for me in #196.

The problem is, in this commit:

https://github.com/FaridSafi/react-native-google-places-autocomplete/commit/f77062fc75bb6815fc32729509bb83a34ac8c57b#diff-e574d057fb2c5e71b74e6125228256e3R734

`userProps` is now added to the end of the props, which means adding an `onChangeText` into the `textInputProps` overrides the default `onChangeText` (which obviously breaks the normal behaviour).

Quite obviously, `onChangeText` should be added after `userProps` (considering it calls through to any specified `onChangeText` later on).

I will fork and submit a PR.

**Comment by AdamPD** [comment]
Submitted PR #205

**Comment by AdamPD** [comment]
Just a further update - there is in fact a second bug.  In `componentWillReceiveProps`, it compares the text in state with the future text prop.  If no `text` prop is specified, it goes with the default of `''` which inevitably is different from the state's text and therefore forces an update.

My fix removes the default value for `text` and skips this check if it is undefined.

**Comment by guilhermepontes** [comment]
fix on `1.3.5`

**Comment by Lowisoft** [comment]
Thank you for your quick update! Though I can't check if the issue is solved (due to my workaround) , I'm closing this issue, because I assume that it works now and if it doesn't, feel free to re-open this issue.
