### ISSUE TITLE
getting Unhandled promise rejection

### ISSUE THREAD

**Issue by wmonecke** [FaridSafi/react-native-google-places-autocomplete#202]
I got my web API KEY. I pasted it in, into the component and tried it out. The component renders and looks good but once I start searching for a place I get the following error:

`Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'toString' of undefined
TypeError: Cannot read property 'toString' of undefined`

My code:

`<GooglePlacesAutocomplete
            placeholder='Search'
            minLength={2} // minimum length of text to search
            autoFocus={false}
            returnKeyType={'search'} // Can be left out for default return key https://facebook.github.io/react-native/docs/textinput.html#returnkeytype
            listViewDisplayed='auto'    // true/false/undefined
            fetchDetails={true}
            onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true
              console.log(data);
              console.log(details);
            }}
            getDefaultValue={() => {
              return ''; // text input default value
            }}
            query={{
              // available options: https://developers.google.com/places/web-service/autocomplete
              key: 'myAPIKey',
              language: 'en', // language of the results
              types: '(cities)' // default: 'geocode'
            }}
            styles={{
              description: {
                fontWeight: 'bold'
              },
              predefinedPlacesDescription: {
                color: '#1faadb'
              }
              }}

            currentLocationLabel="Current location"
            nearbyPlacesAPI='GooglePlacesSearch' // Which API to use: GoogleReverseGeocoding or GooglePlacesSearch
          
            GooglePlacesSearchQuery={{
              // available options for GooglePlacesSearch API : https://developers.google.com/places/web-service/search
              rankby: 'distance',
              types: 'food'
            }}

            filterReverseGeocodingByTypes={['locality', 'administrative_area_level_3']} // filter the reverse geocoding results by types - ['locality', 'administrative_area_level_3'] if you want to display only cities

            debounce={200} // debounce the requests in ms. Set to 0 to remove debounce. By default 0ms.
          />`

**Comment by adityak16** [comment]
@wmonecke for me also it is showing same error but earlier it was working. did you get the solution for this issue ??

**Comment by adityak16** [comment]
@wmonecke #206 solve this issue.
