### ISSUE TITLE
No action triggered when selecting first row

### ISSUE THREAD

**Issue by buskerone** [FaridSafi/react-native-google-places-autocomplete#204]
UPDATE: This only happen with the city "Valdivia, Chile". I changed the initialRegion for another one (not Valdivia Chile) and it didn't work. 

Having troubles when trying to select the first row of results, no action is triggered when selecting it. When selecting the first row the spinner appears but it goes away quickly. Any ideas?

RN: v0.47.1
RN-GPA: v1.3.4

![issue](https://user-images.githubusercontent.com/2034112/30393668-405ab686-9897-11e7-9955-f69add00ddbc.png)

**Comment by guilhermepontes** [comment]
This seems like a styling problem, try adding some zIndex in our styling properties to see if it fixes it.
https://github.com/FaridSafi/react-native-google-places-autocomplete#styling

**Comment by buskerone** [comment]
Sorry @guilhermepontes but why did you close the issue? I think it's not a styling problem because as I said this only happen with the city above - "Valdivia" - and it doesn't happen with any other place.

**Comment by guilhermepontes** [comment]
As I told you @buskerone, this seems like a styling problem with your app, I just ran an example here and it seems fine. Take a look in the styling props to see if you can fix it. Try adding `zIndex`.

And sorry for the late response.

![](http://g.recordit.co/cBmps90OMI.gif)

**Comment by buskerone** [comment]
Ok, thanks I'll try it by adding the zIndex but it's so weird because it works perfectly with other places. I'll give you an update when I fix it.

**Comment by guilhermepontes** [comment]
let me know if it fixes, if not I will open it again! good luck :)

**Comment by SanchiSinghal** [comment]
I can't get the selected text or value from the list in the textinput. 
Can you please help me that ? I'm new to react-native
