### ISSUE TITLE
Refused to set unsafe header "Referer" when you use remote debug

### ISSUE THREAD

**Issue by enguerranws** [FaridSafi/react-native-google-places-autocomplete#207]
Hi,

I'm trying to debug the data that comes back from the module. My issue is that when I try to do so, the console throw this error:
```
GooglePlacesAutocomplete.js:480 Refused to set unsafe header "Referer"
GooglePlacesAutocomplete._this._request @ GooglePlacesAutocomplete.js:480
GooglePlacesAutocomplete._this._onChangeText @ GooglePlacesAutocomplete.js:493
GooglePlacesAutocomplete._this._handleChangeText @ GooglePlacesAutocomplete.js:502
_onChange @ TextInput.js:784
proxiedMethod @ createPrototypeProxy.js:44
invokeGuardedCallback @ ReactErrorUtils.js:22
invokeGuardedCallback @ ReactErrorUtils.js:110
invokeGuardedCallbackAndCatchFirstError @ ReactErrorUtils.js:133
executeDispatch @ EventPluginUtils.js:89
executeDispatchesInOrder @ EventPluginUtils.js:121
executeDispatchesAndRelease @ EventPluginHub.js:37
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:48
forEachAccumulated @ forEachAccumulated.js:32
processEventQueue @ EventPluginHub.js:232
runEventQueueInBatch @ ReactEventEmitterMixin.js:18
handleTopLevel @ ReactEventEmitterMixin.js:38
(anonymous) @ ReactNativeEventEmitter.js:106
fiberBatchedUpdates @ ReactGenericBatching.js:27
performFiberBatchedUpdates @ ReactGenericBatching.js:33
perform @ Transaction.js:150
batchedUpdates @ ReactDefaultBatchingStrategy.js:61
batchedUpdates @ ReactUpdates.js:92
batchedUpdates @ ReactGenericBatching.js:38
batchedUpdatesWithControlledComponents @ ReactGenericBatching.js:51
_receiveRootNodeIDEvent @ ReactNativeEventEmitter.js:105
receiveEvent @ ReactNativeEventEmitter.js:130
__callFunction @ MessageQueue.js:250
(anonymous) @ MessageQueue.js:101
__guard @ MessageQueue.js:218
callFunctionReturnFlushedQueue @ MessageQueue.js:100
(anonymous) @ debuggerWorker.js:71
XMLHttpRequest cannot load https://maps.googleapis.com/maps/api/place/autocomplete/json?&input=Pa&key=AIzaSyDAXXXXXXXXXX5Dw&language=en&types=%28cities%29. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access.
```
If I disable the remote debugger, the module works fine. Another thing to note: my API Key doesn't have any restrictions.

How to use this module and debug it properly?

**Comment by enguerranws** [comment]
The issue really comes from: `XMLHttpRequest cannot load https://maps.googleapis.com/maps/api/place/autocomplete/json?&input=Pa&key=AIzaSyDAXXXXXXXXXX5Dw&language=en&types=%28cities%29. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access.
`

My API key has no restriction, so I guess the issue is I'm using Google Places API Web Service, as mentionned by the docs. However, this key can't be used on client-side (that's what I'm trying to do with the remote debugger).

Any solutions to debug JS while using this module?

**Comment by guilhermepontes** [comment]
Hey, sorry for the late response.
Looks like you are using the `GLOBAL.originalXMLHttpRequest` to debug, right? So... it is not going to work because of the CORS issue. And I think there's no need for a debug prop in the component since this is more for lib maintainers usage.

I'd recommend you to these steps to try to get more info about the request:
1. Comment the http debug line
2. Go to your local `node_modules`
3. Open the `react-native-google-places-autocomplete` folder
4. Open `GooglePlacesAutocomplete.js`
5. Log the result of the line `240` or [find this line.](https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L240)
6. Profit. :)

Let me know if you need help!

**Comment by enguerranws** [comment]
@guilhermepontes Thanks for your quick answer. Actually, I realize I could simply use react-native log-ios / log-android to do this.

**Comment by guilhermepontes** [comment]
cool! :)

**Comment by mateuszmatyszkowicz** [comment]
@guilhermepontes I working with axios and FormData, but when I using this debugging options it's crashed  in others cases works good. Do you know any others approach to debug networks? Thanks in advance :)

**Comment by ziaulrehman40** [comment]
I am facing this same issue, but i am converting an existing `react-native` app to [react-native-web](https://github.com/necolas/react-native-web) app.
We had separate keys for both mobile app and legacy web app, i am using the web app key in the react-native-web version, still same error. If i use restricted mobile app key, error is still the same.

This is odd, any help will be appreciated. Thanks.

**Comment by minhdongsss** [comment]
How about this status, bros.... :D Look my case the same with @ziaulrehman40 . I also convert from mobile app to web app. And get this error when using it :(

**Comment by hthillman** [comment]
Any update here? Looks like this uses the server-side library. Right now this is unusable on web.... Needs to be replaced with the client library for web implementations.

See this thread:
https://github.com/googlemaps/google-maps-services-js/issues/59
