### ISSUE TITLE
Clicking on Current Location doesn't fire onPress

### ISSUE THREAD

**Issue by atalebagha** [FaridSafi/react-native-google-places-autocomplete#216]
clicking on a suggestion fires onPress but when clicking on current location it does not fire.

I am using onPress to go to save the data to redux form and also navigate to the next screen.

**Comment by smokinjoe** [comment]
This is a pretty significant part of my use-case for this, any suggested workarounds, @FaridSafi?

**Comment by smokinjoe** [comment]
I was able to solve this via these two comments:

https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/129#issuecomment-287578645

https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/129#issuecomment-289293500

(The second one was the key one that got `onPress` triggering for me)
