### ISSUE TITLE
Warning: In next release empty section headers will be rendered. In this release you can use 'enableEmptySections' flag to render empty section headers.

### ISSUE THREAD

**Issue by sodik82** [FaridSafi/react-native-google-places-autocomplete#22]
I am getting `Warning: In next release empty section headers will be rendered. In this release you can use 'enableEmptySections' flag to render empty section headers.` with react native 0.23.1

It does not cause any troubles now but might be a problem with future versions of RN.

**Comment by myaskevich** [comment]
Hey @sodik82 !
You're absolutely right, thanks for the tip!
This will be fixed in the next version.
