### ISSUE TITLE
[Question / Feature Request] keyboardShouldPersistTaps to prevent need for double tapping

### ISSUE THREAD

**Issue by wbattel4607** [FaridSafi/react-native-google-places-autocomplete#223]
I've implemented this like your example but the main issue I am having is that it takes two taps to select the list item. The first tap dismisses the keyboard and then the second will select the row- which should happen on the first tap.

This sounds similar to [this](https://stackoverflow.com/questions/43992012/autocomplete-textinput-with-listview-have-to-tap-listview-twice-to-select-list) so I'm wondering if you could provide some insight on if it's from the same issue, if everyone on this library is affected, and if it can be fixed. I tried adding the prop `keyboardShouldPersistTaps={true}` but it had no effect.

Thanks!

**Comment by thechefchen** [comment]
+1

**Comment by ashishere-nike** [comment]
+1

**Comment by jeanpaulsio** [comment]
I was able to get persistent taps working. I have the auto complete component as a child of `ScrollView`

```jsx
  <ScrollView
    keyboardShouldPersistTaps={"always"}
  >
    <GooglePlacesAutocomplete />
  </ScrollView>
```

I believe `keyboardShouldPersistTaps={true}` is deprecated. Hope this helps!

**Comment by wbattel4607** [comment]
@jeanpaulsio unfortunately I didn't share your luck. I am still unable to get this working.

**Comment by pospieszynski** [comment]
me neither.. Dropdown basically ignores my taps(address is not set, only dropdown disappears), only reacts sometimes when I double tap very fast..

 Any help, or at least some explenation why does it work like this?

**Comment by Base29** [comment]
@jeanpaulsio ... I was having the same issue ... I tried your suggestion and it worked ... Thanks

**Comment by r281GQ** [comment]
Hey guys! I am having the same issue. Even stranger,  @jeanpaulsio your solution worked in one component in the app whereas it doesn't in on other where the render code is identical expect their parents are different. I can't figure out what is the issue.

**Comment by mistryhiren94** [comment]
@jeanpaulsio thanks
it works for me

**Comment by BryonApps** [comment]
Make sure that any parent ScrollViews (or FlatList, etc.) of your GooglePlacesAutocomplete component have the prop keyboardShouldPersistTaps={'always'}set. This resolved the problem for me. Good luck!

**Comment by adlondon** [comment]
Also having this issue. Setting  keyboardShouldPersistTaps="always" in the parent works great if there are no other children, but the problem is that my components parent has a scrollview with other input fields that rely on those taps _not_ persisting. Has anyone found any other solutions?

**Comment by wbattel4607** [comment]
@guilhermepontes why was this closed? This is still a problem.

**Comment by samuelmataraso** [comment]
the same problem here, + 1, I don't know what I need to do, for a single tap works to select an item of the list. I try with `keyboardShouldPersistTaps={"always"}` and nothing !

**Comment by Mariana1523** [comment]
I'm having the same problem, did you manage to solve it?

**Comment by namanica** [comment]
pls helppp two years have passed and we still have it !!
I have tried all possible workarounds from the docs and other related issues - nothing works
the thing is that it's the issue overally inside the component I guess, because the input gets unfocused every time we click on the list
I tried to remove all the wrappers - just inside a simple view and it performed the same
