### ISSUE TITLE
Styling of listView

### ISSUE THREAD

**Issue by cmedara** [FaridSafi/react-native-google-places-autocomplete#226]
I can't seem to remove the border bottom of each address options in the  drop down.
![capture](https://user-images.githubusercontent.com/5249473/32403704-2a2528a2-c195-11e7-88a0-a843f8c20e59.PNG)

**Comment by cmedara** [comment]
never mind solved it.
it's a view component called seperator(not a border). 
can change the style by passing the "seperator" as the key in styles

**Comment by ajkhatibi** [comment]
any idea on how to wrap the listview text if it extends further than the width of the screen?
