### ISSUE TITLE
on press current location showing blank list 

### ISSUE THREAD

**Issue by jangidprashant92** [FaridSafi/react-native-google-places-autocomplete#227]
I have clicked on current location but it's showing blank list check the link https://snack.expo.io/Skd57d2r-

Pleas help me

**Comment by IbraheemOsama** [comment]
I have the same issue as well.

**Comment by jangidprashant92** [comment]
you have to remove renderDescription after that resolve your problem

**Comment by IbraheemOsama** [comment]
You saved me !! thanks :)
