### ISSUE TITLE
Autocomplete Suggestions don't work with single tap

### ISSUE THREAD

**Issue by SandroBCIT** [FaridSafi/react-native-google-places-autocomplete#230]
The autocomplete is working well, other than the fact that you have to double tap the search suggestions in order to interact with them. Is there a way to use a suggestion by just tapping once on them??

**Comment by RoysyLee** [comment]
+1

**Comment by wbattel4607** [comment]
Duplicate of #223

**Comment by lllymok** [comment]
+1

**Comment by BryonApps** [comment]
Make sure that any parent ScrollViews (or FlatList, etc.) of your GooglePlacesAutocomplete component have the prop `keyboardShouldPersistTaps={'always'}`set.  This resolved the problem for me.  Good luck!

**Comment by samuelmataraso** [comment]
the same problem here, + 1, I don't know what I need to do, for a single tap works to select an item of the list. I try with `keyboardShouldPersistTaps={"always"}` and nothing !

**Comment by rohanvasishth** [comment]
Still facing this issue, I have used keyboardShouldPersistTaps={"always"} everywhere still not working.
