### ISSUE TITLE
Is it possible to limit the number of results that are been rendered?  

### ISSUE THREAD

**Issue by sagomezza** [FaridSafi/react-native-google-places-autocomplete#231]
Hi, I want to know if Is it possible to limit the number of results that are been rendered?

**Comment by supercamilo** [comment]
@sagomezza why did you close this issue without an answer? did you find a way to limit the results?

**Comment by sagomezza** [comment]
@supercamilo Yeah, I just gave the listView a defined height

**Comment by MikaelConecto** [comment]
Not a very valid answer... You just hide them, not restrict them
