### ISSUE TITLE
Autocomplete suggestion box open from first time

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [FaridSafi/react-native-google-places-autocomplete#235]
We are using this package in our App. 
Here we define a default value from the first time and in android the suggestion options are open, we don't want it open from the first time, it will open after click on the text field. Can anyone suggest how to close the suggestion. It's only happening in Android.

We are using react-native : 0.44
"react-native-google-places-autocomplete": "^1.2.12",

**Comment by GemN** [comment]
I have exactly the same problems on iOS with default values.

**Comment by MSSPL-PiyaleeMaiti** [comment]
@GemN  what is your react-native and "react-native-google-places-autocomplete" version??

**Comment by GemN** [comment]
{
  "name": "react-native",
  "version": "0.50.3",

{
  "name": "react-native-google-places-autocomplete",
  "version": "1.3.6",
}

Current behavior with my custom fix is that on focus, nothing happens until i modify the text which is fine for me for now.

**Comment by MSSPL-PiyaleeMaiti** [comment]
@GemN  where you use focus? In text field or in Google Autocomplete field onfocus? Can you explain this thing.

**Comment by noambonnie** [comment]
I also experience this issue - when I set a default value, the list is open when the component mounts even if autoFocus is set to false. For now I used @alex-osman fix - though it feels a bit like a hack.

**Comment by noambonnie** [comment]
After further reviewing the code, I would like to propose a different solution to @alex-osman.

1. In _onChangeText, set the value of listViewDisplayed to this._isMounted (instead of true).
2. In componentDidMount call _onChangeText() first, and only then set _isMounted.

I will create a pull request later, but wanted to put this solution out there.

**Comment by guilhermepontes** [comment]
Sounds good @noambonnie.

**Comment by noambonnie** [comment]
@guilhermepontes - Done.

**Comment by lmichailian** [comment]
Hi! This was fixed ?

**Comment by GemN** [comment]
@lmichailian fixed with the last version

**Comment by pymd** [comment]
Hi, is there a new release planned anytime soon?

**Comment by guilhermepontes** [comment]
@pymd guess it's fixed on master branch. will be releasing a new version soon

**Comment by noambonnie** [comment]
@guilhermepontes I noticed that the code that fixes it that I submitted is no longer there (it used to be in past versions). There were two pull requests to fix this: 271 and 272.

For now I fixed it again locally. I'm not sure whether it was removed for a reason or just some inadvertent override.

I hope the pull requests can be reintroduced. They're very small (2 lines of code basically)
