### ISSUE TITLE
How can i get onChangeText event on the input text ?

### ISSUE THREAD

**Issue by NelsonPetitos** [FaridSafi/react-native-google-places-autocomplete#236]

**Comment by se1exin** [comment]
Just found the answer to this - the component has an [undocumented textInputProps prop](https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L504) that accepts an `onChangeText` handler

Use it like this:
```
textInputProps={{
    onChangeText: (text) => { console.log(text) }
}}
```

**Comment by EvanBacon** [comment]
This should be closed @FaridSafi :)

**Comment by unicornRainbows** [comment]
awesome!

**Comment by Base29** [comment]
@se1exin ... I want to use "ref" and "onSubmitEditing" props ... I tried your method but getting an error "undefined is not an object (evaluating '_this2.refs.businessaddress.focus') ... any suggestions ? I am new to react native

**Comment by MalguyMQ** [comment]
@Base29 
You can try to add textInputProps on your googleMapAutocompleteInput with ref inside like this : 
```
textInputProps={{
    onRef={(r) => this.googleMapInput = r}
}}
```
and in your TextInput before googleMapAutocompleteInput try to add this props : 
```
              onSubmitEditing={() => this.googleMapInput.focus()}
              returnKeyType={ 'next' }
```
