### ISSUE TITLE
Remove separator from the last item in the list.

### ISSUE THREAD

**Issue by viper1029** [FaridSafi/react-native-google-places-autocomplete#24]
Hi,

Thanks for this very useful component. I'm trying to figure out 2 things:
1. How to remove the seperator after the last item in the list.
2. I'm assuming clearButtonMode will need to be implemented manually for android. Is this correct? Any suggestions?

Thank you.

**Comment by myaskevich** [comment]
Hey @viper1029 

Sorry for such a late response.

Luckily, last item separator issue has been fixed recently as a part of https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/77
