### ISSUE TITLE
How to use componentRestrictions 

### ISSUE THREAD

**Issue by Base29** [FaridSafi/react-native-google-places-autocomplete#247]
I am trying to restrict the autocomplete results to Australia only but I can't figure out how to do this ... Where should I pass componentRestrictions ... or there is some other function in the GooglePlacesAutocomplete API  ?

**Comment by sagomezza** [comment]
Check out the options that GooglePlacesAutocomplete API has for that, it is specified as a comment in example.js: 
[https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/d669cf624a2e5d7a7f113e55fe26c8b93a745856/GooglePlacesAutocompleteExample/Example.js#L30](url)

**Comment by blacktea** [comment]
Example:

Limit country to Argentina 

```
            components: 'country:ar'
```

**Comment by vishaljaggi** [comment]
What about multiple countries?

**Comment by charithAmila** [comment]
How about restrict for country and state Eg : I need to filter only US and Los Angeles data only .

**Comment by vishaljaggi** [comment]
Found my answer: components:’country:ca|country:uk’
