### ISSUE TITLE
onNotFound() is not being triggered when there are no results

### ISSUE THREAD

**Issue by sagomezza** [FaridSafi/react-native-google-places-autocomplete#248]
I want to show a simple Text when there are no results to show. But the onNotFound is not being triggered (I know it because I did a console.log on the function, and there's no message). I've already tried it with autoRefill on true and nothing happens. 

So, when is it supposed to be triggered?

**Comment by vkumarNobul** [comment]
+1

**Comment by Hammza1** [comment]
I got the same issue please anyone help

**Comment by MayoudP** [comment]
Any update on this ?

**Comment by iamshadmirza** [comment]
Same issue, `onNotFound` is not getting triggered. I want to add a simple text instead of result rows if there is no result. @guilhermepontes

**Comment by Nikita2708** [comment]
+!

**Comment by Nikita2708** [comment]
+1
