### ISSUE TITLE
How to handle the clear event when the x is pressed?

### ISSUE THREAD

**Issue by mlevkovsky** [FaridSafi/react-native-google-places-autocomplete#250]
When I type a city to do a lookup there appears a little x in order to clear my selection.

Is there a prop I can set so that when that button is pressed I can take some action?

Thanks

**Comment by Devlin556** [comment]
+1

**Comment by yashovardhanagrawal** [comment]
I can't see the `x` button in Android but on iOS its there. Is there some prop that can be set to show it up on Android?

**Comment by mefallit** [comment]
+1

**Comment by dhorrock** [comment]
+1

**Comment by pjforde1978** [comment]
@guilhermepontes you closed this issue without comment. Is this just a #wontfix or did I miss something?

**Comment by AdamGold** [comment]
Any news on this?

**Comment by jamesa3** [comment]
Any updates on this?

**Comment by bell-steven** [comment]
@jamesa3 this issue is closed. Please open a new issue (please allow the issue template).

**Comment by ArjunPatidarRadix** [comment]
add refrence the call 
`      <GooglePlacesAutocomplete
        ref={InputRef} 
        ... />
InputRef.current?.setAddressText('')`
