### ISSUE TITLE
listView display bug

### ISSUE THREAD

**Issue by khalilleo** [FaridSafi/react-native-google-places-autocomplete#253]
<img width="334" alt="2018-01-10 10 14 25" src="https://user-images.githubusercontent.com/2585057/34779739-1a530dfc-f5ef-11e7-9f05-03e510043366.png">

set position: 'absolute' for listView

**Comment by tomcrusader** [comment]
This might indeed occur @khalilleo , but it's enough to place the auto complete in an absolute container.

To work around it you might specify background white on the **listView** style:



```
const Styles = StyleSheet.create({
  containerTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  horizontal: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  padding: { padding: 20 },
  listView: {
// This is the fix:
    backgroundColor: '#ffffff',
  },
  textInputContainer: {
    borderBottomWidth: 0,
    borderTopWidth: 0,
  },
  textInput: {
    color: '#00539b',
    fontSize: 16,
  },
  description: {
    fontWeight: 'bold',
  },
  predefinedPlacesDescription: {
    color: '#fede00',
  },
});

<View style={[styles.containerTop, styles.horizontal, styles.backgroundWhite]}>
            <GooglePlacesAutocomplete
              styles={styles}
            ...
            />
</View>
```
![image](https://user-images.githubusercontent.com/396545/35329054-b2b2ba92-00fe-11e8-97cc-77097c849e6f.png)

**Comment by khalilleo** [comment]
Fixed by adding 'elevation: 1' to listView

**Comment by alessandro-pianetta** [comment]
I added 'elevation: 1' to listView and am still having this issue.

(Green background just to show obvious bounds of component)

![simulator screen shot - iphone x - 2018-01-28 at 18 05 28](https://user-images.githubusercontent.com/25068419/35490684-3f7ad2e8-0456-11e8-9162-6370ec100622.png)

**Comment by levapramim** [comment]
I have two Searchs and does not work to me.  =(  any other suggestions ?
