### ISSUE TITLE
Can I use it as a data library only?

### ISSUE THREAD

**Issue by jack2684** [FaridSafi/react-native-google-places-autocomplete#254]
I have some input box and flatlist which have some of my own customized UI interaction feature. Is it possible to use this npm as a pure data lib to fetch data from google?

**Comment by EQuimper** [comment]
@jack2684 I've done this lib here with some idea of this one for helping me building customizable ui. Maybe that can help :) https://github.com/EQuimper/react-native-google-autocomplete
