### ISSUE TITLE
Please warn users about Google usage charges for underlying web API

### ISSUE THREAD

**Issue by tarheele** [FaridSafi/react-native-google-places-autocomplete#258]
Thanks for your contribution of this great library!

It is my understanding that folks get charged after 25,000 API calls for the Google Maps Web APIs.

Thus, any user whose app might go viral will probably want to use the native Android or iOS APIs, which appear to allow unlimited usage (and which this project does not appear to use)

Please make this clear in your user guide.  You do make it clear that this project uses the web API, but a user might be impacted down the road not knowing the implications.

**Comment by guilhermepontes** [comment]
This is a not a libraries responsibility.
