### ISSUE TITLE
Use iOS/Android key instead of web

### ISSUE THREAD

**Issue by greatwitenorth** [FaridSafi/react-native-google-places-autocomplete#26]
Is there any way of changing this library to use the iOS/Android keys? Right as is we have to set our web key to allow incoming requests from anywhere. Someone can easily obtain our key by sniffing traffic and use our key however they like which is quite insecure. Not sure what would all be involved, but I imagine there's some native code which would be needed in order to make this happen.

**Comment by myaskevich** [comment]
Hi @greatwitenorth 

I'm afraid there is no such way to use something other that API keys from google.

In order to prevent key theft you could try some [best practices suggested by Google](https://support.google.com/cloud/answer/6310037) and make sure to refresh keys after a while.

**Comment by myaskevich** [comment]
Closing this one... Please reopen it, if you have any other questions.

**Comment by bufke** [comment]
To clarify - is it not possible to use the js api key with this? As I understand the web key is intended for use in a server. With react native we would be distributing the key to clients.
