### ISSUE TITLE
how get the place selected ?

### ISSUE THREAD

**Issue by Johnba1988** [FaridSafi/react-native-google-places-autocomplete#261]
I want to get the place selected to use it in other variable.

**Comment by moussasarr** [comment]
I am looking for the same thing. How to get the value to be used somewhere else. Let me know if you find an answer. Thanks

**Comment by noambonnie** [comment]
I'm not sure I understand your question. Why can't you use onChangeText just like you would with TextInput components? or the results coming in onPress?

**Comment by Johnba1988** [comment]
@moussasarr , add this props `onPress={text => {`
`//here add what you want to do with the place selected (place selected is inside text.description`
            console.log (   `text.description`)
           ` }}`

**Comment by moussasarr** [comment]
I already figured out the solution . Thanks!!

**Comment by GulShenR** [comment]
@moussasarr How u did?
