### ISSUE TITLE
Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by BlackStef** [FaridSafi/react-native-google-places-autocomplete#266]
I have a problem, since today (before it worked) I have a promise rejection every time I modifie the text in my GooglePlaceAutocomplete textBox : 

![screenshot_1517873934](https://user-images.githubusercontent.com/12743769/35834488-5236c5d2-0ad6-11e8-99a2-b28dad094dbd.png)

I have my code working as on the example, I didnt touch every thing on my component since the last time it working. 

Someone has an idea ?

**Comment by wisepuck** [comment]
<img width="355" alt="screenshot at mar 26 00-05-53" src="https://user-images.githubusercontent.com/5129689/37879999-5302c41e-308a-11e8-9fb3-46f7c35d71ef.png">
I am also have problem. v1.3.6

**Comment by andela-cofor** [comment]
@wisepuck I am having the same error any fix ?

**Comment by guilhermepontes** [comment]
fixed in new version
