### ISSUE TITLE
filterReverseGeocodingByTypes not working

### ISSUE THREAD

**Issue by yarakanigara** [FaridSafi/react-native-google-places-autocomplete#269]
So I want filter only ['administrative_area_level_2', 'political'] and it still give me an object with ['administrative_area_level_3', 'locality'] and another object with administrative_area_level_1
my GooglePlacesAutocomplete property for filterReverseGeocodingByTypes :
 
`filterReverseGeocodingByTypes={[
                    'administrative_area_level_1',
                    'political'
                  ]}`

**Comment by rezonjov** [comment]
try using renderDescription

```
renderDescription={row => row.description.split(',').shift()} // custom description render
```
