### ISSUE TITLE
support for RN 0.26

### ISSUE THREAD

**Issue by sodik82** [FaridSafi/react-native-google-places-autocomplete#27]
Hello, it would be nice to resolve breaking changes in upcomming RN 0.26.
See deprecations in https://github.com/facebook/react-native/releases/tag/v0.25.1

possible fix: e.g. see https://github.com/cridenour/react-native-google-places-autocomplete/commit/41e10d2ce4fec365ce4084ac107998f0daff6d5d

**Comment by Gedzis** [comment]
PR submited: https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/28

**Comment by sodik82** [comment]
closing - should work now :)
