### ISSUE TITLE
How To Hide Current Location Link?

### ISSUE THREAD

**Issue by singhlovey** [FaridSafi/react-native-google-places-autocomplete#280]
Hi,

I want to hide currentLocation link from page. But when I set currentLocation={false} nothing will displayed on the page and search text input also disappear.

Here is my code.

			  <GooglePlacesAutocomplete
						placeholder='Search'
						minLength={2} 
						autoFocus={false}
						listViewDisplayed='auto'    
						fetchDetails={true}
						renderDescription={row => row.description || row.vicinity} 
                                              onPress={(data, details = null) => { 
						// console.log("data " + JSON.stringify(data));
						// console.log("details " + JSON.stringify(details.address_components));
                                               }}

					   getDefaultValue={() => {
						 return ''; // text input default value
					   }}
					   query={{
						 key: 'API_KEY_VALUE',
						 language: 'en', // language of the results
						 types: 'address', // default: 'geocode'
					   }}
					  
					   currentLocation={true} 
					   nearbyPlacesAPI='GoogleReverseGeocoding' 
					   predefinedPlacesAlwaysVisible={true}

If I change currentLocation={true}  to currentLocation={false}, I got blank page. 

Please help.

Thanks

**Comment by jakeOliv** [comment]
just comment down these lines..
// currentLocation={true}
// currentLocationLabel="  Current Location"
