### ISSUE TITLE
Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by andela-cofor** [FaridSafi/react-native-google-places-autocomplete#282]
<img width="380" alt="screen shot 2018-03-28 at 6 03 48 pm" src="https://user-images.githubusercontent.com/25608370/38044684-71e45d96-32b2-11e8-97a5-0a36c6015b61.png">

**Comment by aloptrbl** [comment]
i'm also have this issue. How to fix this

**Comment by andela-cofor** [comment]
No have you @aloptrbl ?

**Comment by guilhermepontes** [comment]
Can you share more info about your code?

**Comment by Coucy** [comment]
Got this error too. In my case this.props.query.origin is undefined
![Screen Shot 2019-07-11 at 10 57 16](https://user-images.githubusercontent.com/9610401/61032813-d6901980-a3ca-11e9-818c-4c84293604c9.png)

**Comment by Coucy** [comment]
As a temporary solution, I set this param to null
![Screen Shot 2019-07-11 at 11 06 56](https://user-images.githubusercontent.com/9610401/61033557-6aaeb080-a3cc-11e9-971c-169ed6060ac8.png)
