### ISSUE TITLE
No way to style placeholder

### ISSUE THREAD

**Issue by nikolas7892** [FaridSafi/react-native-google-places-autocomplete#285]

**Comment by dagrinchi** [comment]
Yes see https://facebook.github.io/react-native/docs/textinput.html#style
and `placeholderTextColor` props

**Comment by nica0012** [comment]
This doesn't work?

**Comment by nica0012** [comment]
Never mind, you can achieve this via textInputProps

**Comment by Charles22219** [comment]
> Never mind, you can achieve this via textInputProps

Can I ask how I can exactly do this.. So far i have tried doing it like this, but the color still doesnt change
`placeholderTextColor='white'
 placeholder='Destination'`

**Comment by hrmoller** [comment]
@nica0012 can you provide an example of how you made it work? I can't figure out how to style the placeholder.

**Comment by tomo10** [comment]
> @nica0012 can you provide an example of how you made it work? I can't figure out how to style the placeholder.

You want to pass the textInputProps as a prop to the GooglePlacesAutocomplete.  Not into the styles obj like you pass most of the other styling.  For example see below:

<GooglePlacesAutocomplete
      placeholder={'Search'}
      fetchDetails={true}
      query={{
        key: '...',
        language: 'en',
      }}
      textInputProps={{ placeholderTextColor: 'pink' }}
      styles={{
        container: {
          backgroundColor: theme.color.screen,
        },
        textInput: {
          backgroundColor: theme.color.secondaryScreen,
          color: theme.color.boneIcon,
        },
        textInputContainer: {
          backgroundColor: theme.color.screen,
        },
      }}
      onFail={(error) => console.log('error:', error)}
    />

**Comment by faisal-murad** [comment]
Still not working for me

> > @nica0012 can you provide an example of how you made it work? I can't figure out how to style the placeholder.
> 
> You want to pass the textInputProps as a prop to the GooglePlacesAutocomplete. Not into the styles obj like you pass most of the other styling. For example see below:
> 
> <GooglePlacesAutocomplete placeholder={'Search'} fetchDetails={true} query={{ key: '...', language: 'en', }} textInputProps={{ placeholderTextColor: 'pink' }} styles={{ container: { backgroundColor: theme.color.screen, }, textInput: { backgroundColor: theme.color.secondaryScreen, color: theme.color.boneIcon, }, textInputContainer: { backgroundColor: theme.color.screen, }, }} onFail={(error) => console.log('error:', error)} />

**Comment by tobywisener** [comment]
> Never mind, you can achieve this via textInputProps

Not working for me either.. did you try it?
