### ISSUE TITLE
clear button for Android

### ISSUE THREAD

**Issue by Giosk** [FaridSafi/react-native-google-places-autocomplete#287]
In android I can't see the clear button in the form.
Is it an issue or is it because on android doesn't exist?
Do you have a solution? 

Thanks

**Comment by tienw** [comment]
second that

**Comment by anchetaWern** [comment]
oh so there's actually a clear button within the autocomplete form? 
I was looking for a way to reset the text field value and found this.

**Comment by guilhermepontes** [comment]
There is, but not supported for Android.
