### ISSUE TITLE
[Feature suggestion] Reverse lookup

### ISSUE THREAD

**Issue by hegelstad** [FaridSafi/react-native-google-places-autocomplete#288]
It would be really neat to supply the component with a latlong coordinate and get a list with the closest addresses/components shown in the component. With the possibility of a "feeling lucky" mode where it sets the text-field and returns the callback with the address lookup result.

**Comment by antgel** [comment]
@guilhermepontes Closed with no response? Did I miss something? Is there a supported way to do this?
