### ISSUE TITLE
Current Location

### ISSUE THREAD

**Issue by Shashi147** [FaridSafi/react-native-google-places-autocomplete#291]
Get Current Location showing nearby places instead of exact location

**Comment by buoto** [comment]
You need to set [`nearbyPlacesAPI='None'`](https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/43e313fc8f6bb82bfca85d5e3b34654a651e607a/GooglePlacesAutocomplete.js#L187). This library really needs some up to date docs.

**Comment by guilhermepontes** [comment]
@buoto feel free to send a PR! :)
