### ISSUE TITLE
Google places within a city

### ISSUE THREAD

**Issue by Mubashir1044** [FaridSafi/react-native-google-places-autocomplete#292]
How to search places of a specific city of a specific country??

**Comment by elleryfamilia** [comment]
You can specify _location_ and _radius_ in the query. [Read the documentation](https://developers.google.com/places/web-service/autocomplete) so you can see all the query options.

**Comment by alexpopa-work** [comment]
The city isn't necessarily a circle, I was wandering if the results could be limited to a country by specifying the country code and not the radius around a point on the map.
