### ISSUE TITLE
OnBlur not connected

### ISSUE THREAD

**Issue by nbaghiro** [FaridSafi/react-native-google-places-autocomplete#293]
Hi guys, 

I was debugging the issue of not closing the dropdown when onBlur happens on TextInput and realized that you never connect _onBlur function to the TextInput. 

After adding `onBlur={this._onBlur}` prop to the TextInput in your library code, it started to work properly. Can you publish a fix for that please or let me know if you are handling this in some other way? 

Thanks for the great work!

**UPDATE**: 
I know get why onBlur was not attached because it messes up things related clicking the list items. But how do we close the listView without clicking on one of the items in it?

**Comment by codeandproduce** [comment]
By "messes up" do you mean the error: "_this.refs.textInput.blur is not a function" error? Because I'm getting that and I thought it may be because I defined by own behavior for onBlur but I'm getting the error message nevertheless.
