### ISSUE TITLE
Location Request Timed Out

### ISSUE THREAD

**Issue by darkmantle** [FaridSafi/react-native-google-places-autocomplete#294]
Having a problem where, on Android, the location request times out whenever I select 'Current Location'. I have enabled the Geocoding API - here is my code:

```jsx
<GooglePlacesAutocomplete
                placeholder='Search'
                minLength={2}
                autoFocus={false}
                fetchDetails={true}
                enablePoweredByContainer={false}
                onPress={(data, details = null) => {
                    console.log("DATA: ", data);
                    console.log("DETAILS: ", details);
                }}
                query={{
                    key: 'lol-no',
                    language: 'en',
                    types: 'geocode',
                    components: 'country:gb'
                }}
                currentLocation={true}
                currentLocationLabel={'Current Location'}
                nearbyPlacesAPI='GoogleReverseGeocoding' // Which API to use: GoogleReverseGeocoding or GooglePlacesSearch
            />
```

**Comment by noambonnie** [comment]
There are plenty of issues with react native's getCurrentLocation. Just look it up. What I ended up doing is using Google's Fused Location library which is far more consistent on Android devices. And for the AutoComplete component I just managed it myself: I would get the current location when I need it.

**Comment by darkmantle** [comment]
I did manage to fix this, but have forgotten how now. I eventually changed to a custom UI anyway...

May have been issue with API key. Closing for now.

**Comment by umrashrf** [comment]
I can reproduce this. It happens when location permission are delayed (as requested by Google Play Team). On Android location can't be requested unless the user explicitly requested it.

After giving the location access to the app by the user, user has to restart the app for Current Location to work. This issue is only with react-native-google-places-autocomplete.
