### ISSUE TITLE
Layout for List Items

### ISSUE THREAD

**Issue by dquilter** [FaridSafi/react-native-google-places-autocomplete#299]
I want to style the list items, but I'm having trouble because the `renderDescription` option seems to throw content into a `Text` node. Because of this I can't use a `View` as this throws an error (View within a `Text` node), and nesting another `Text` node doesn't give me the ability to create the layout I want.

Is there something I'm missing here? Or are we only able to give the list item the most basic of styling/layout?

**Comment by guilhermepontes** [comment]
You have full control of the styling  by using the `styles` prop, the docs are not that good and I'm sorry for that, I'll try to give it some life.

**Comment by Ovsdrak** [comment]
You are able to do what you want by using the `renderRow` option instead of renderDescription, it is not in the documentation but it does in `node_modules/react-native-google-places-autocomplete/GooglePlacesAutocomplete.js` line 528 aprox.
