### ISSUE TITLE
Fetch details of place too?

### ISSUE THREAD

**Issue by kanerogers** [FaridSafi/react-native-google-places-autocomplete#3]
Hi, Farid!

Thanks again for making such a wonderful, useful component!

Would you like to add an option to fetch the details of the place via the [Google Place Details API](https://developers.google.com/places/web-service/details)? I'm about to implement this myself in my application code, but figured this might be helpful to the library as well.

If necessary, it could be hidden behind a `fetchDetails` flag, if you don't want this to be the default behaviour.

Let me know if you're interested! :smile_cat:

**Comment by FaridSafi** [comment]
Hello Kane, thank you for this suggestion.
It's a good idea, I will implement it today

**Comment by kanerogers** [comment]
Thanks, Farid! := )

**Comment by kanerogers** [comment]
PS. Is there any reason why you are using `XMLHttpRequest` instead of `fetch` as specified in the [React Docs](http://facebook.github.io/react-native/docs/network.html#content)? :smile:

**Comment by FaridSafi** [comment]
Yes it's because fetch doesn't provide a method to abort requests (while typing fast new char I cancel previous search request)

**Comment by kanerogers** [comment]
Got it! I figured there must be reason - that's a very good one. ;)

**Comment by FaridSafi** [comment]
fetchDetails tag in now available.
You can retrieve the details in the second parameter of the onPress callback

**Comment by kanerogers** [comment]
Hi, @FaridSafi,

I tried the latest version today, and it works well. Thank you!
