### ISSUE TITLE
Current location not showing text

### ISSUE THREAD

**Issue by JenniferLeonFonseca** [FaridSafi/react-native-google-places-autocomplete#310]
I am trying to put the current location options but they do not show the text, even though it shows the ListItem, do not contain text,  Please Help

![image](https://user-images.githubusercontent.com/16937991/41066360-3065cff4-69a7-11e8-8967-07552b9c67fc.png)

**Comment by hegelstad** [comment]
Search in issues, this problem has been described and solved in several issues.
