### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by Nnanyielugo** [FaridSafi/react-native-google-places-autocomplete#317]
I tried reproducing the example in the readMe only to get this error.
Below is a screenshot of the red box.

My environment:
react-native: 0.56.0
react-native-google-places-autocomplete:  1.3.6

![screenshot_1531393720](https://user-images.githubusercontent.com/27894311/42630774-ed5a89bc-85cf-11e8-87a6-33a679483006.png)

**Comment by guilhermepontes** [comment]
Going to be fixed in the next release

**Comment by Nnanyielugo** [comment]
It's okay.

**Comment by Nnanyielugo** [comment]
It's okay.
Built my own anyways.

I guess I have to thank you for that.
