### ISSUE TITLE
undefined is not an object (image.resizeMode.contain)

### ISSUE THREAD

**Issue by tgreco** [FaridSafi/react-native-google-places-autocomplete#319]
https://stackoverflow.com/questions/51317168/react-native-google-places-undefined-is-not-an-object-when-searching

**Comment by gabrieletondi** [comment]
I've opened a pull request to fix this: https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/321

**Comment by guilhermepontes** [comment]
Going to be fixed in the next release

**Comment by JenniferLeonFonseca** [comment]
Is this already fixed ? im using  
"react": "16.4.1",
 "react-native": "0.56.0",
"react-native-google-places-autocomplete": "^1.3.6"
And off course I have this error so im pretty much interested in this solution
Thanks for the info :)

**Comment by Madhur2207** [comment]
Just go to node_modules/react-native-goolge-place-autocomplete/GooglePlaceAutocomplete.js
and remove 'resizeMode={Image.resizeMode.contain}' from_renderPoweredLogo method

**Comment by nicomontanari98** [comment]
@JenniferLeonFonseca @tgreco 
You can see my changes in my pull request #323

**Comment by Madhur2207** [comment]
Welcome
