### ISSUE TITLE
Filter by country

### ISSUE THREAD

**Issue by Roconda** [FaridSafi/react-native-google-places-autocomplete#32]
Hi,

I'm interested in restricting search to a country. Is this possible using this plugin?

Thanks
Tim

**Comment by myaskevich** [comment]
Hi @Roconda 

Thanks for your interest!

After looking at [Google Places Autocomplete API Docs](https://developers.google.com/places/web-service/autocomplete#place_types) I can say that it does support restricting the search query.

Try passing `(country)` to the `query.types` prop:

```javascript
var Example = React.createClass({
  render() {
    return (
      <GooglePlacesAutocomplete
        query={{
          key: 'YOUR API KEY',
          language: 'en', // language of the results
          types: '(country)', // default: 'geocode'
        }}
```

If that answers your question, please consider closing this issue.

Thanks,
Max

**Comment by Roconda** [comment]
Hi @myaskevich,

Thanks for your response! I wasn't probably clear enough what I ment with restricting to a country. Currently I'm creating an app which only supports The Netherlands. So all I want to do is search to locations located in The Netherlands. 

The types: 'country' property only supports searching to countries if I understand it correctly, right?

Thanks,
Tim

**Comment by yangster24** [comment]
Hello @Roconda and @myaskevich,

I believe the default way of restricting the country is through componentRestrictions: {country: 'whatever_country'} and I attempted to do it the default way, but it seems like this implementation of autocomplete doesn't support this feature? Could you clarify @myaskevich if this is true?

**Comment by myaskevich** [comment]
Hey @Roconda @yangster24 

Thanks, now it's much clearer for me.

I just got my autocomplete component to restrict all results to the Netherlands by using `query.components` props:

```javascript
var Example = React.createClass({
  render() {
    return (
      <GooglePlacesAutocomplete
        query={{
          key: 'YOUR API KEY',
          components: 'country:nl'
        }}
```

See [`components` optional autocomplete query parameter](https://developers.google.com/places/web-service/autocomplete#place_autocomplete_requests) for more info.

**Comment by Roconda** [comment]
Thank you very much @myaskevich, this is exactly what I needed!

**Comment by gbwashleybrown** [comment]
This doesn't seem to work for me

  ````
query={{
   language: "en",
   components: "country:uk",
}}
````

But it still brings up addresses for any country...

**Comment by mjm918** [comment]
> This doesn't seem to work for me
> 
> ```
> query={{
>  language: "en",
>  components: "country:uk",
> }}
> ```
> 
> But it still brings up addresses for any country...

If you want to search in `United Kingdom` only, I think you should use `GB` (Great Britain) according to [ISO 3166](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes)

**Comment by sarmad-321** [comment]
what if i need multiple countries ? for example i need dubai and uk both

**Comment by IntuzRajZ** [comment]
@sarmad-321, You can do like these in the components param,

 * components :
 * A grouping of places to which you would like to restrict your results. Currently,
 * you can use components to filter by up to 5 countries. Countries must be passed as a two-character,
 * ISO 3166-1 Alpha-2 compatible country code. For example: components=country:fr would restrict your results to
 * places within France. Multiple countries must be passed as multiple country:XX filters, with the pipe character | as a separator.
 * For example components=country:us|country:pr|country:vi|country:gu|country:mp would restrict your results to places within the United States and
 * its unincorporated organized territories.
 *
 * @default country:ch // Switzerland ISO 3166-1 Alpha-2 compatible country code
