### ISSUE TITLE
Clicking on suggestion doesn't fire onpress event on first click, but when you press second time onpress event is fired.

### ISSUE THREAD

**Issue by cr21** [FaridSafi/react-native-google-places-autocomplete#322]
<GooglePlacesAutocomplete
                placeholder='Search'
                placeholderTextColor='#1F4497'
                minLength={2} // minimum length of text to search
                autoFocus={false}
                returnKeyType={'search'} // Can be left out for default return key https://facebook.github.io/react-native/docs/textinput.html#returnkeytype
                listViewDisplayed='auto'    // true/false/undefined
                fetchDetails={true}
                renderDescription={(row) => row.description} // custom description render
                enablePoweredByContainer={false}
                onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true
                    console.log(data);
                    console.log("*****");
                    console.log("pressing location");
                    //console.log(details.geometry.location);
                    this.props.onFindingDirections(details.geometry.location);
                }}
                getDefaultValue={() => {
                    return ''; // text input default value
                }}
                query={{
                    // available options: https://developers.google.com/places/web-service/autocomplete
                    key: GOOGLE_API_KEY,
                    language: 'en', // language of the results
                    //types: '(cities)', // default: 'geocode'
                    // components: 'country:gh'
                }}
                styles={{
                    description: {
                        fontWeight: 'bold'
                    },
                    predefinedPlacesDescription: {
                        color: 'blue'
                    }
                }}
                currentLocation={false} // Will add a 'Current location' button at the top of the predefined places list
                //currentLocationLabel="Current location"
                //nearbyPlacesAPI='GooglePlacesSearch' // Which API to use: GoogleReverseGeocoding or GooglePlacesSearch
                //GoogleReverseGeocodingQuery={{
                    // available options for GoogleReverseGeocoding API : https://developers.google.com/maps/documentation/geocoding/intro
                    //}}
                    /*GooglePlacesSearchQuery={{
                    // available options for GooglePlacesSearch API : https://developers.google.com/places/web-service/search
                    rankby: 'distance',
                    types: 'food'
                }}*/

                filterReverseGeocodingByTypes={['locality', 'administrative_area_level_3']} // filter the reverse geocoding results by types - ['locality', 'administrative_area_level_3'] if you want to display only cities
                //predefinedPlaces={[homePlace, workPlace]}
                predefinedPlacesAlwaysVisible={true}
                debounce={500} // debounce the requests in ms. Set to 0 to remove debounce. By default 0ms.
                renderLeftButton={() => <Icon name="search" size={20} color="#1F4497" style={{ alignSelf: 'center', paddingHorizontal:5}}/>}
                renderRightButton={() => <Text></Text>}
                />
        );
    }

**Comment by rickardinho** [comment]
I have the same issue.  I think its because on the first click, the textInput loses focus, and then its only the second click that is recognised as the onPress event.
This isn't ideal - is there a way to make the click recognised even though the text input is focussed?

**Comment by EstebanBP** [comment]
Have you found any solution or workaround for this?

**Comment by cr21** [comment]
Yes I found hack , you need to change in node modules for that

**Comment by AarshApple** [comment]
@cr21 Did you solve the problem ?

**Comment by tobilastik** [comment]
If you are still facing this issue @EstebanBP solved the issue for me.
wrap the GooglePlacesAutocomplete inside a Scrollview and add 
keyboardShouldPersistTaps="handled"

**Comment by devcoderbuzz** [comment]
I do not have any scroll view, but still onPress not working.. :(

**Comment by rvenky125** [comment]
any update on it @devcoderbuzz ?

**Comment by Rorofy** [comment]
I have the same problem without having GooglePlacesAutocomplete in a ScrollView and even if i wrap GooglePlacesAutocomplete in a Scrollview and add keyboardShouldPersistTaps="handled" i get this error 
` VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.`
Does anyone have another fix for this ?

**Comment by tonydatw** [comment]
I am having the same problem now, tried all the above options but nothing works, not nested in any scrollview or sectionlist, onPress not working on first try but after i hit the Enter button and then retype the place, it will press.

**Comment by danglequocbao001** [comment]
Me too @devcoderbuzz , still can't find a solution...

**Comment by danglequocbao001** [comment]
> I do not have any scroll view, but still onPress not working.. :(

Me too, still can't find solution...
