### ISSUE TITLE
Question: what about new billing across Google Places API?

### ISSUE THREAD

**Issue by imarem** [FaridSafi/react-native-google-places-autocomplete#324]
What about new billing across Google Places? How it affect in this plugin?

Is there any way like Per session (sessionToken), to minimize these costs?

Thanks in advance

**Comment by alexpopa-work** [comment]
It will affect it as any other website or app. The component is making http requests using your api key, so you get billed if the limit is reached.

**Comment by marconucara** [comment]
It would be great to have an option to enable sessionToken.

Last paragraph in this page explains how to implement it, it's very easy:
https://cloud.google.com/maps-platform/user-guide/pricing-changes
And you should also reset the token on selection.

**Comment by guilhermepontes** [comment]
PRs are welcome

**Comment by ollieh-m** [comment]
Hi @marconucara,
Could you give an example of how you added the sessionToken to autocomplete requests?
Would be really appreciated!

**Comment by marconucara** [comment]
Just create an access token using uuid v4, as suggested by google documentation:

```
const createPlacesAutocompleteSessionToken = (a) => {
  return a
    ? (a ^ Math.random() * 16 >> a / 4).toString(16)
    : ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, createPlacesAutocompleteSessionToken);
};
```

I do that on componentDidMount and probably you should refresh it on suggestion select (I destroy the component on select, so I don't need that):

```
this.placesAutocompleteToken = createPlacesAutocompleteSessionToken()
```

Then pass it in query prop:

```
query={{
  ...,
  sessiontoken: this.placesAutocompleteToken,
}}
```

Check the api call in network tab, the token will appear.

**Comment by ollieh-m** [comment]
Great, and thanks for such a quick response!

**Comment by imarem** [comment]
thanks @marconucara 

Really helpful!!

**Comment by paras-kc** [comment]
what is this a parameter a in the function

**Comment by SnidelyWhiplash** [comment]
Heads up that you also need to pass the `sessiontoken` in the Details query for any of this to have an affect, afaik.

```
  query={{
    ...,
    sessiontoken: this.placesAutocompleteToken,
  }}
  GooglePlacesDetailsQuery={{
    ...,
    sessiontoken: this.placesAutocompleteToken,
  }}
