### ISSUE TITLE
Extracting Place_id 

### ISSUE THREAD

**Issue by yangster24** [FaridSafi/react-native-google-places-autocomplete#33]
With the api, is there a method in which I can extract the Place_id (id of the address) or the longitude and latitude once creating the GooglePlacesAutocomplete component? Looking at the src code, it is called several times, but I was wondering if I can explicitly retrieve the values of it after creating the component.

**Comment by yangster24** [comment]
to retrieve the value, you can get it from data.place_id.

**Comment by BeckhamVinoth** [comment]
Can you please show me your code ??

**Comment by BeckhamVinoth** [comment]
i would like to know how to get place id by using react native MapView
