### ISSUE TITLE
Possible unhandled Promise Rejection (id:0)

### ISSUE THREAD

**Issue by kingtross88** [FaridSafi/react-native-google-places-autocomplete#331]
My app stopped being able to utilize google autocomplete module. My api key is working. Not sure what was the change. I did see that this issue was open before but was closed out a couple of days ago. 

![screen shot 2018-08-08 at 3 07 15 pm](https://user-images.githubusercontent.com/6825383/43859660-47303202-9b1f-11e8-8ec2-0e7aa31f98ee.png)

**Comment by danieljgp2** [comment]
@guilhermepontes I start to get this error once i install rn-fetch-blob as dependecy, have you fix this issue ?

**Comment by kingtross88** [comment]
I had to download the node module and drop it in my node folder to fix the
issue. It was some time ago. I believe that is how I got it to work. sorry
it was some time ago.
