### ISSUE TITLE
no streets after update to 1.3.8

### ISSUE THREAD

**Issue by quandevelopment** [FaridSafi/react-native-google-places-autocomplete#332]
Hi,
after updating to 1.3.8. the query results don't show the streets anymore. If I go back to 1.3.6. iIr works again. Is this a bug or did you changed the API.

Best Qung

**Comment by guilhermepontes** [comment]
If you are talking about the `query` prop, you can simply remove the `types` from the object.

**Comment by quandevelopment** [comment]
thanks for your answer. 
on the first screenshot you can see the current version 1.3.9. There are no streets in the results.
in the second screenshot you can see the results, if you type a street into the search bar.

types = 'geocode' in both cases

thanks!
![bildschirmfoto 2018-08-24 um 12 00 04](https://user-images.githubusercontent.com/23075358/44579013-5d2d0f80-a795-11e8-8986-3ac8577c7b73.png)
![bildschirmfoto 2018-08-24 um 11 58 00](https://user-images.githubusercontent.com/23075358/44579014-5d2d0f80-a795-11e8-8999-e4917e96f7d1.png)

**Comment by guillermodoghel** [comment]
same issue. even removing types, removing also `filterReverseGeocodingByTypes` did the trick
