### ISSUE TITLE
Populate search box with Current Address

### ISSUE THREAD

**Issue by ramuachala** [FaridSafi/react-native-google-places-autocomplete#335]
Hi, I would like to populate the search box with my current address as default value. How do I do that. I have gone through all the issues and did not find any solution.  I see the an option 
```
getDefaultValue={() => {
  return ''; // text input default value
}}
```
for showing the default value. I want to show the current address instead of " " text.

**Comment by SirPhemmiey** [comment]
Have you solve this problem? @ramuachala

**Comment by luisrodge** [comment]
Any updates on this? I need to do the same thing.

**Comment by klapperkopp** [comment]
Assuming you have a state.address value you would do it like this:

`getDefaultValue={() => this.state.address || ''}`

So for example my Input contains a config like this:

```
<GooglePlacesAutocomplete
        placeholder={'Please Search A Location'}
        minLength={2}
        autoFocus={true}
        returnKeyType={'default'}
        fetchDetails={true}
        getDefaultValue={() => address || ''}
        onPress={(data, details = null) => {
              this.setState({ address: data.description || data.name }) 
              this.addressInput.toggleExpandableModal(false);
       }}
       onCancel={ () => { this.setState( () => { this.addressInput.toggleExpandableModal(false) }) } }
       query={{ key: Config.GEOCODING_KEY, language: 'en' }}
/>
```

I think there is no issue here and this could be closed.

**Comment by i1990jain** [comment]
> Assuming you have a state.address value you would do it like this:
> 
> `getDefaultValue={() => this.state.address || ''}`
> 
> So for example my Input contains a config like this:
> 
> ```
> <GooglePlacesAutocomplete
>         placeholder={'Please Search A Location'}
>         minLength={2}
>         autoFocus={true}
>         returnKeyType={'default'}
>         fetchDetails={true}
>         getDefaultValue={() => address || ''}
>         onPress={(data, details = null) => {
>               this.setState({ address: data.description || data.name }) 
>               this.addressInput.toggleExpandableModal(false);
>        }}
>        onCancel={ () => { this.setState( () => { this.addressInput.toggleExpandableModal(false) }) } }
>        query={{ key: Config.GEOCODING_KEY, language: 'en' }}
> />
> ```
> 
> I think there is no issue here and this could be closed.

this does not work for me ... the value is never displayed from the state variable

**Comment by i1990jain** [comment]
https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/158#issuecomment-372740996

this works perfectly

**Comment by bell-steven** [comment]
It appears like this is resolved.  Feel free to open a new issue if this is still a problem for you.
