### ISSUE TITLE
google places autocomplete: The provided api key is invalid

### ISSUE THREAD

**Issue by ballsac** [FaridSafi/react-native-google-places-autocomplete#336]
I receive the following error when trying to use this package:
![error](https://user-images.githubusercontent.com/39440090/44162429-4a785380-a08e-11e8-88dc-afc6a5bc2dd6.PNG)

As per the directions, I have enabled the following APIs:
- Places API for Web
- Geocoding API
![apis](https://user-images.githubusercontent.com/39440090/44162680-046fbf80-a08f-11e8-8b9a-8dd654b36d70.png)

I also added the following restrictions to see if that would help, but it did not:
![restrictions](https://user-images.githubusercontent.com/39440090/44162741-2c5f2300-a08f-11e8-8cd5-14380c805103.png)

Any help would be appreciated.

**Comment by guilhermepontes** [comment]
You need to get the key here https://developers.google.com/places/web-service/intro

And use the component like this:

```
<GooglePlacesAutocomplete query={{ key: 'API_KEY' }} />
```

**Comment by akashkrshukla** [comment]
None of the above working for me .
