### ISSUE TITLE
you have exceeded your daily request quota for this API

### ISSUE THREAD

**Issue by PatricioBrass** [FaridSafi/react-native-google-places-autocomplete#337]
Hi, have a problem with the key. I were working without  problem, I do not know what's happening. 
I Change key, change project and nothing
Help please!

**Comment by ld234** [comment]
I'm having the same problem. Did you figure out how to solve it?

**Comment by PatricioBrass** [comment]
@ld234 yes! you do have to enter a credit card in google cloud platform

**Comment by vivekshah-zymr** [comment]
@PatricioBrass, I want to display a message to a user when "Daily request quota for this API is exceeded"
