### ISSUE TITLE
How to restrict the search to show only country names?

### ISSUE THREAD

**Issue by ShridharCodewave** [FaridSafi/react-native-google-places-autocomplete#339]

**Comment by cmacdonnacha** [comment]
@ShridharCodewave , did you find out how to do this? I only want to search certain countries.

**Comment by ShridharCodewave** [comment]
hello @cmacdonnacha , using the "types" prop and setting it countries inside query was supposed to work but it didn't.

> query={{
                  key: "your api key",
                  language: "en", // language of the results,
                  types: "(cities)"
                }}

So I came with a workaround and passed cities which was working and from the result I filtered the country name. But I don't know how to show only country names while searching.

**Comment by MayoudP** [comment]
This is a needed basic feature here . Some helps ?
