### ISSUE TITLE
Current location list issue

### ISSUE THREAD

**Issue by adarshperumal** [FaridSafi/react-native-google-places-autocomplete#351]
Can someone please help in identify where I am going wrong. The current location is getting picked up but the list is not getting shown properly.

![img_5770](https://user-images.githubusercontent.com/8089128/46255148-ec3bee80-c4dc-11e8-963b-3f8744328f34.jpg)

`<GooglePlacesAutocomplete
      placeholder='Deliver To'
      minLength={2} // minimum length of text to search
      autoFocus={false}
      returnKeyType={'search'} // Can be left out for default return key https://facebook.github.io/react-native/docs/textinput.html#returnkeytype
      listViewDisplayed='auto'    // true/false/undefined
      fetchDetails={true}
      renderDescription={row => row.description || row.vicinity} // custom description render
      onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true
        console.log(data, details);
      }}
      getDefaultValue={() => ''}
      query={{
        // available options: https://developers.google.com/places/web-service/autocomplete
        key: '',
        language: 'en', // language of the results
        types: 'geocode', // default: 'geocode'
        components: 'country:au',
      }}
      
      styles={{
        textInputContainer: {
          width: '100%',
          backgroundColor: 'rgba(0,0,0,0)',
          borderLeftWidth: 0.5,
          borderRightWidth: 0.5,
          
        },
        textInput: {
          fontFamily: "AvenirMedium",
          fontSize: 17,
          color: "#000",
          backgroundColor: 'rgba(0,0,0,0)',
          
        },
        description: {
          fontWeight: 'bold'
        },
        predefinedPlacesDescription: {
          color: '#1faadb'
        }
      }}
      
      currentLocation={true} // Will add a 'Current location' button at the top of the predefined places list
      currentLocationLabel="Current location"
      nearbyPlacesAPI={'GoogleReverseGeocoding'} // Which API to use: GoogleReverseGeocoding or GooglePlacesSearch
      GoogleReverseGeocodingQuery={{
        // available options for GoogleReverseGeocoding API : https://developers.google.com/maps/documentation/geocoding/intro
        key: '',
        language: 'en',
      }}
    />
`

**Comment by reinvanimschoot** [comment]
Where you able to get this to work?

**Comment by adarshperumal** [comment]
Hi @reinvanimschoot , Not yet. Would you be able to help please. Thanks

**Comment by reinvanimschoot** [comment]
I was able to solve this by changing the styles of the description. I think for some reason the default text color is white, hence why you don't see any places but the rows are there.

**Comment by adarshperumal** [comment]
Thanks very much @reinvanimschoot. I'll make the changes and check

**Comment by adarshperumal** [comment]
Hi @reinvanimschoot , I tried setting the font color and also tried to change the background color just in case but looks like it is not getting populated. Can you please help.

![img_1370](https://user-images.githubusercontent.com/8089128/46724365-9843bd80-ccc5-11e8-98ed-7d3467a5f028.jpg)

**Comment by sazo2300** [comment]
I had a similar issue. On my end the list did get populated, but looked exactly like yours. The issue was the render details property didnt work. You have:
renderDescription={row => row.description || row.vicinity} // custom description render
i had:
renderDescription={row => row.description }

Removing the render description fixed the issue for me. Havent played around to get it to work with the renderDescription property yet.

However, the current location now renders names of places, but i want it to show addresses, and i cant get it to cooporate with that..

**Comment by Gorbus** [comment]
Hi @sazo2300, I know I am a bit late but may help future users.

If you need to render adresses and not places you have to use :

 nearbyPlacesAPI={'GoogleReverseGeocoding'}

instead of 

nearbyPlacesAPI={'GooglePlacesSearch'}

**Comment by jituumaria** [comment]
Hii, Its not a issue, see the renderDescription props

renderDescription={row => row.description || row.formatted_address || row.name}

**Comment by jituumaria** [comment]
> Can someone please help in identify where I am going wrong. The current location is getting picked up but the list is not getting shown properly.
> 
> ![img_5770](https://user-images.githubusercontent.com/8089128/46255148-ec3bee80-c4dc-11e8-963b-3f8744328f34.jpg)
> 
> `<GooglePlacesAutocomplete
> placeholder='Deliver To'
> minLength={2} // minimum length of text to search
> autoFocus={false}
> returnKeyType={'search'} // Can be left out for default return key https://facebook.github.io/react-native/docs/textinput.html#returnkeytype
> listViewDisplayed='auto' // true/false/undefined
> fetchDetails={true}
renderDescription={row => row.description || row.formatted_address || row.name}
> onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true
> console.log(data, details);
> }}
> getDefaultValue={() => ''}
> query={{
> // available options: https://developers.google.com/places/web-service/autocomplete
> key: '',
> language: 'en', // language of the results
> types: 'geocode', // default: 'geocode'
> components: 'country:au',
> }}
> 
> ```
>   styles={{
>     textInputContainer: {
>       width: '100%',
>       backgroundColor: 'rgba(0,0,0,0)',
>       borderLeftWidth: 0.5,
>       borderRightWidth: 0.5,
>       
>     },
>     textInput: {
>       fontFamily: "AvenirMedium",
>       fontSize: 17,
>       color: "#000",
>       backgroundColor: 'rgba(0,0,0,0)',
>       
>     },
>     description: {
>       fontWeight: 'bold'
>     },
>     predefinedPlacesDescription: {
>       color: '#1faadb'
>     }
>   }}
>   
>   currentLocation={true} // Will add a 'Current location' button at the top of the predefined places list
>   currentLocationLabel="Current location"
>   nearbyPlacesAPI={'GoogleReverseGeocoding'} // Which API to use: GoogleReverseGeocoding or GooglePlacesSearch
>   GoogleReverseGeocodingQuery={{
>     // available options for GoogleReverseGeocoding API : https://developers.google.com/maps/documentation/geocoding/intro
>     key: '',
>     language: 'en',
>   }}
> />
> ```
> 
> `

**Comment by bell-steven** [comment]
@jituumaria using the code you provided, it was working fine for me. Can you open a new issue (using the "usage help" template)?

In case this is just an issue with your key, you can add this to the props to surface those errors.
```
onFail={(message) => console.log(message)}
```

**Comment by Punith-goud** [comment]
@adarshperumal @Gorbus @sazo2300 @bell-steven , hey guys please check my code, I've tried everything you guys mentioned but still facing issuse, bellow is my code 

`          <GooglePlacesAutocomplete
            placeholder="Search a place"
            styles={{
              textInput: {
                height: 50,
                borderRadius: 13,
                marginTop: 10,
                backgroundColor: '#FAFAFA',
                borderWidth: 1,
                borderColor: '#d9d9d9',
                color: '#000',
                paddingHorizontal: 25,
              },
            }}
            currentLocation={true}
            currentLocationLabel="Current location"
            textInputProps={{
              placeholderTextColor: '#a9a9a9',
            }}
            value={venue}
            onPress={(data, details) => setVenueDetails(data, details)}
            query={{key: API_Key}}
            fetchDetails={true}
            onFail={error => console.log(error)}
            timeout={70000}
            onTimeout={error => console.error('Location Error: ', error)}
            onNotFound={() => console.log('no results')}
            listEmptyComponent={() => (
              <View style={{flex: 1}}>
                <Text>No results were found</Text>
              </View>
            )}
            renderRow={data => (
              <Text style={{color: 'black'}}>{data.description}</Text>
            )}
            nearbyPlacesAPI="GooglePlacesSearch"
          />`
