### ISSUE TITLE
removing "powered by google" signature 

### ISSUE THREAD

**Issue by artiumGlobalbit** [FaridSafi/react-native-google-places-autocomplete#353]
How can I remove the signature from the bottom of the search results? Thanks

**Comment by sbaldani** [comment]
Hi! I think you can do that with prop enablePoweredByContainer.
enablePoweredByContainer={false}

**Comment by aafaqahmed** [comment]
Appreciated

**Comment by Abhimanyusin** [comment]
> Hi! I think you can do that with prop enablePoweredByContainer. enablePoweredByContainer={false}

nice bro it's working thanks
