### ISSUE TITLE
Question, is it possible to set an array of fields

### ISSUE THREAD

**Issue by SamMatthewsIsACommonName** [FaridSafi/react-native-google-places-autocomplete#355]
Hi,
Thanks for the plugin. is it possible to specify the fields queried for the result? We're getting billed for some additional data which isn't huge but it's beginning to add up.

https://developers.google.com/places/web-service/details

<img width="248" alt="screen shot 2018-10-23 at 4 30 17 pm" src="https://user-images.githubusercontent.com/21329063/47392120-421d4400-d6e1-11e8-988f-9f5e2f5ada42.png">

Thanks!

**Comment by it2ak** [comment]
We need just a Basic category of fields from the Place Details. Is it possible to limit the response to these fields?

**Comment by ACHP** [comment]
I just created a PR to add this feature. https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/380

**Comment by RWOverdijk** [comment]
This feature appears to be merged. Perhaps this issue can be closed?

**Comment by bell-steven** [comment]
closed by #380
