### ISSUE TITLE
types should be type - please correct it

### ISSUE THREAD

**Issue by msman** [FaridSafi/react-native-google-places-autocomplete#358]
Hi,
Thanks for the great work. Please correct the types parameter to type of the GooglePlacesSearchQuery as that  mentioned in optional parameters here : [https://developers.google.com/places/web-service/search](url)

**Comment by moiseshilario** [comment]
@FaridSafi I just created a PR for this :https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/384. Thanks @msman for catching it!

**Comment by bell-steven** [comment]
Closed by #384
