### ISSUE TITLE
How to override methods

### ISSUE THREAD

**Issue by ptnz** [FaridSafi/react-native-google-places-autocomplete#36]
Hi!
Can you explain please, how to override your methods (for example, _onPress),  when I use your component in my project, and want to change some features?

**Comment by myaskevich** [comment]
Hi @ptnz 
I'm afraid there is no way to redefine core `_onPress` method quite yet. Furthermore I wouldn't recommend you doing that.
This might be the sign this library is not quite what you need.

Anyway, maybe if you dropped a few words about your problem, I could help you?

**Comment by ptnz** [comment]
Thanks for answer!

There is not so many libraries based on react and using google autocomplete api.
And your lib is very helpful.

I think, I found the way to override methods.

**Comment by myaskevich** [comment]
Since this is not encouraged, you'll have to do it on your own risk.
