### ISSUE TITLE
Is there any way to restrict api key

### ISSUE THREAD

**Issue by proyectarse** [FaridSafi/react-native-google-places-autocomplete#361]
Hi, Do you know any way to use a restricted API KEY on the Autocomplete for an APP. Can't find it, Thanks  lot

**Comment by traviisd** [comment]
I don't see the possibility for it in this component. I think in order to use a restricted key, there would have to be native code added and not just a JavaScript library unfortunately.

**Comment by proyectarse** [comment]
yes, Thanks for your answer, that's seems to be the solution... Thanks!!
