### ISSUE TITLE
 'react-native-google-autocomplete' doesn't exist in the hastle module app

### ISSUE THREAD

**Issue by shadynoah** [FaridSafi/react-native-google-places-autocomplete#366]
'react-native-google-autocomplete' doesn't exist in the hastle module app

**Comment by lucasacw05** [comment]
Same thing is happening with me...

**Comment by salvagit** [comment]
Did you try the following?

  $rm -rf node_modules
  $npm cache clean --force
  $npm install
  $react-native run-XXXX -- --reset-cache

**Comment by Averybeast1234** [comment]
Do npm install react-native-google-autocomplete   and that will fix that issue. At least it is what worked for me

**Comment by bell-steven** [comment]
This doesn't sound like an issue with the library itself.  Feel free to re-open if you haven't resolved this.
