### ISSUE TITLE
Not Fix for Promise Rejection ? RN v 0.55.4

### ISSUE THREAD

**Issue by lucasferreiraestevam** [FaridSafi/react-native-google-places-autocomplete#369]
![captura de tela 2018-12-08 as 13 59 41](https://user-images.githubusercontent.com/12140708/49687928-aa897e80-faf1-11e8-8d77-db15bcb54771.png)

**Comment by komangwie** [comment]
same problem here

**Comment by bell-steven** [comment]
There is no promise code in this library, so I am not sure where this error is coming from.

I'm going to close this for now, but if you want to provide some sample code, or better yet a [snack](https://snack.expo.io) so I can reproduce the issue, feel free to re-open this.
