### ISSUE TITLE
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by rollrodrig** [FaridSafi/react-native-google-places-autocomplete#371]
I just installed the library and then run `react-native run-android` the error pops on the console.

$ react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...

> Configure project :app 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-maps.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-maps: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

### package.json
"react": "16.6.1",
"react-native": "0.57.5",
"react-native-maps": "https://github.com/react-community/react-native-maps.git",
"react-native-google-places-autocomplete": "^1.3.9",

I also tried, but nothing changed. Any help ?
$ react-native link react-native-google-places-autocomplete

**Comment by bell-steven** [comment]
This library does not use any native android (or iOS) code.  The error you are showing is most likely coming from react-native-maps or another package (although by now, i'm sure it has been fixed).
