### ISSUE TITLE
How and where to pass client id?

### ISSUE THREAD

**Issue by GowthamGr** [FaridSafi/react-native-google-places-autocomplete#372]
Hi @FaridSafi ,
               Now am using google api key to get locations.But my requirement is to pass client id instead of api key.please guide to do this.

**Comment by bell-steven** [comment]
Please see the google doc [here](https://developers.google.com/maps/documentation/directions/get-api-key).

This issue is really old, so i'm going to close it.  Feel free to open a new issue if needed.
