### ISSUE TITLE
Bound autocomplete

### ISSUE THREAD

**Issue by DanielMarcello** [FaridSafi/react-native-google-places-autocomplete#374]
Hello.

Is there any way to bound the Autocomplete suggestions? for example show a list with addresses only nearest to your current location.

**Comment by AikoRamalho** [comment]
I'm facing the same problem. Any suggestions?

**Comment by d-spiridonov** [comment]
I think this is what you are looking for: https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/275

**Comment by bell-steven** [comment]
It appears that this is resolved.  Feel free to re-open a new issue if this is still a problem for you.
