### ISSUE TITLE
Is there a way to restrict the type of places user can search

### ISSUE THREAD

**Issue by buchidiai** [FaridSafi/react-native-google-places-autocomplete#378]
Just wanted to know if i can restrict user from searching for pizza places or things or places unrelated to a specific business type? thanks

**Comment by MikaelConecto** [comment]
Would like to know how to restrict to a certain country as well!

**Comment by tanveerparhar** [comment]
please check google places api documentation
https://developers.google.com/places/web-service/autocomplete
