### ISSUE TITLE
how to place the autocomplete on Map

### ISSUE THREAD

**Issue by Ahmed-Imam** [FaridSafi/react-native-google-places-autocomplete#379]
I am trying to build the autocomplete on top of a map, but the search box keeps pushing the map down, how can i overlay the search results on the map ?

```
    <GooglePlacesAutocomplete
                    listViewDisplayed='true'
                    placeholder='Search'
                    minLength={1} // minimum length of text to search
                    autoFocus={false}
                    fetchDetails={true}
                    onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true
                        this.setState({
                            latitude: details.geometry.location.lat,
                            longitude: details.geometry.location.lng, latitudeDelta: 0.3, longitudeDelta: 0.3
                        });
                    }}
                    getDefaultValue={() => {
                        return ''; // text input default value
                    }}
                    query={{
                        // available options: https://developers.google.com/places/web-service/autocomplete
                        key: key
                        language: 'ar', // language of the results
                        types: 'address', // default: 'geocode'
                    }}
                    styles={{
                        description: {
                            fontWeight: 'bold',
                            textAlign: 'right'
                        },
                        predefinedPlacesDescription: {
                            color: '#1faadb',
                        },
                    }}
                    currentLocation={false} // Will add a 'Current location' button at the top of the predefined places list
                    currentLocationLabel="Current location"
                    nearbyPlacesAPI='GooglePlacesSearch' // Which API to use: GoogleReverseGeocoding or GooglePlacesSearch
                    GoogleReverseGeocodingQuery={{
                        // available options for GoogleReverseGeocoding API : https://developers.google.com/maps/documentation/geocoding/intro
                    }}
                    GooglePlacesSearchQuery={{
                        // available options for GooglePlacesSearch API : https://developers.google.com/places/web-service/search
                        rankby: 'distance',
                        types: 'food',
                    }}
                    filterReverseGeocodingByTypes={['locality', 'administrative_area_level_3']} // filter the reverse geocoding results by types - ['locality', 'administrative_area_level_3'] if you want to display only cities
                    predefinedPlacesAlwaysVisible={true}
                />

                <MapView
                    region={this.getMapRegion()}
                    style={styles.map}
                    // onPress={() => alert('hello')}
                    provider={PROVIDER_GOOGLE}
                    mapType="standard"
                    onRegionChangeComplete={(region) => this.setState({
                        latitude: region.latitude, longitude: region.longitude,
                        latitudeDelta: region.latitudeDelta, longitudeDelta: region.longitudeDelta
                    })}
                    showsCompass={true}
                    showsBuildings={true}
                    showsTraffic={true}
                    showsIndoors={true}
                >
                    <MapView.Marker
                        coordinate={this.getMapRegion2()} />
                    <Image

                        style={{
                            resizeMode: 'contain',
                            left: '50%',
                            marginLeft: -24,
                            marginTop: -48,
                            height: 60, width: 60,
                            top: '50%'
                        }} source={require('../../assets/fake-marker.png')} />
                </MapView>

```
![50550819_347618482500155_1182095215993815040_n](https://user-images.githubusercontent.com/20854551/51783001-e2b25280-216d-11e9-8e14-ce7fa75b917c.jpg)

**Comment by nwaughachukwuma** [comment]
This works perfect, but when I click on a row, the click is bubbles up to the map component. This means, I cant listen for onPress on ~autocomplete. Any idea on how to resolve this?

**Comment by lyudad** [comment]
Have same issue

**Comment by Luckygirlllll** [comment]
This is annoying bug, I have the same problem with map!

**Comment by Ahmed-Imam** [comment]
I solved this issue by wrapping the GooglePlacesAutocomplete in a View position absolute as follow 
```
  <View style={{ position: 'absolute', width: width, zIndex: 9999, top: 10 }}>
                    <GooglePlacesAutocomplete
                        istViewDisplayed='false'
                        styles={{
                            textInputContainer: {
                                width: width - 40,
                                borderRadius: 5,
                                borderWidth: 1,
                                borderColor: '#eee',
                                marginHorizontal: 20,
                            },
                        }} />
                </View>

                <View style={{ flex: 1 }}>
                    <MapView style={{ flex: 1 }} />
                    <View style={{
                        left: '50%',
                        marginLeft: -24,
                        marginTop: -48,
                        position: 'absolute',
                        top: '50%'
                    }}>
                        <Image
                            style={{
                                resizeMode: 'contain',
                                height: 60, width: 60,
                            }}
                            source={require('../../assets/fake-marker.png')} />
                    </View>
                </View>
```

**Comment by lyudad** [comment]
Hello. This is not good solution. As yes - list shown correct, but any item that are on map are not clickable (try to click to item that on map and you will see that it not clickable)

**Comment by CrisHemswerthThor** [comment]
I was also getting the same issue : 
by giving  position:"absolute" in MapView style  and placing <GooglePlacesAutocomplete/> after <MapsView/> works for me. 

<SafeAreaView style={{flex: 1}}>
                <MapView
                    followsUserLocation={true}
                    animated={true}
                    showsCompass={true}
                    mapType='satellite'
                    provider='google'
                    style={styles.container}
                    moveOnMarkerPress={true}
                    showsUserLocation={true}
                    region={this.state.region}
                    showsMyLocationButton={true}
                    onMarkerDragEnd={(coordinate) =>
                        // this._getAddress(coordinate)
                        this.setState({
                            anotherCoordinate: {
                                latitude: coordinate.nativeEvent.coordinate.latitude,
                                longitude: coordinate.nativeEvent.coordinate.longitude,
                                latitudeDelta: LATITUDE_DELTA,
                                longitudeDelta: LONGITUDE_DELTA,
                            },
                        })
                    }
                >
                    <Marker
                        title='Current Location'
                        //draggable={true}
                        coordinate={this.state.region}
                    />
                    <Marker
                        title={this.state.destinationTitle}
                        draggable={true}
                        coordinate={this.state.anotherCoordinate}
                    />
                    <MapViewDirections
                        origin={this.state.region}
                        destination={this.state.anotherCoordinate}
                        apikey={GOOGLE_MAPS_API_KEY}
                        strokeWidth={3}
                        strokeColor="hotpink"
                    />
                </MapView>
                <GooglePlacesAutocomplete
                    placeholder='Enter your destination...'
                    minLength={2}
                    autoFocus={false}
                    returnKeyType={'search'}
                    keyboardAppearance={'light'}
                    listViewDisplayed={this.state.listViewDisplayCheck}
                    fetchDetails={true}
                    renderDescription={row => row.description}
                    onPress={(data, details = null) => {
                        this.setState({
                            anotherCoordinate: {
                                latitude: details.geometry.location.lat,
                                longitude: details.geometry.location.lng,
                                latitudeDelta: LATITUDE_DELTA,
                                longitudeDelta: LONGITUDE_DELTA,
                            },
                            listViewDisplayCheck:false
                        });
                    }}
                    query={{
                        key: GOOGLE_MAPS_API_KEY,
                        language: 'en',
                    }}
                    styles={{
                        textInputContainer: {
                            width: '100%',
                        },
                        textInput: {
                            height:30
                        },
                        listView: {
                            elevation: 1,
                        },
                        description: {
                            fontWeight: 'bold',
                        },
                        predefinedPlacesDescription: {
                            color: '#1faadb',
                        },
                        row:{
                            backgroundColor:"white"
                        }
                    }}
                    nearbyPlacesAPI='GooglePlacesSearch'
                    GoogleReverseGeocodingQuery={{}}
                    GooglePlacesSearchQuery={{
                        rankby: 'distance',
                        type: 'cafe',
                    }}
                    GooglePlacesDetailsQuery={{
                        fields: 'formatted_address',
                    }}
                    debounce={200}
                />
            </SafeAreaView>

**Comment by lyudad** [comment]
But select items on Map not work

**Comment by amitbravo** [comment]
How do you getting geometry location such as details.geometry.location.lat ? My details var is only fetching formatted_address, this is the below result data when I selected Sydney Airport from the list 
````
details  => {"formatted_address": "Sydney NSW 2020, Australia"}
data => {"description": "Sydney Airport (SYD), Sydney NSW, Australia", "id": "86dbe21c6cd13631c1485fca6e7766cf85504147", "matched_substrings": [{"length": 3, "offset": 7}], "place_id": "ChIJ24MzG_GwEmsRd2VLWl01368", "reference": "ChIJ24MzG_GwEmsRd2VLWl01368", "structured_formatting": {"main_text": "Sydney Airport (SYD)", "main_text_matched_substrings": [[Object]], "secondary_text": "Sydney NSW, Australia"}, "terms": [{"offset": 0, "value": "Sydney Airport (SYD)"}, {"offset": 22, "value": "Sydney"}, {"offset": 29, "value": "NSW"}, {"offset": 34, "value": "Australia"}], "types": ["airport", "point_of_interest", "establishment"]}
````

for following onPress method 
````
onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true
                        console.log('details'=>,details)
                        console.log('data=>',data)
                       
                     }}
````

**Comment by RicardoSom** [comment]
> How do you getting geometry location such as details.geometry.location.lat ? My details var is only fetching formatted_address, this is the below result data when I selected Sydney Airport from the list
> 
> ```
> details  => {"formatted_address": "Sydney NSW 2020, Australia"}
> data => {"description": "Sydney Airport (SYD), Sydney NSW, Australia", "id": "86dbe21c6cd13631c1485fca6e7766cf85504147", "matched_substrings": [{"length": 3, "offset": 7}], "place_id": "ChIJ24MzG_GwEmsRd2VLWl01368", "reference": "ChIJ24MzG_GwEmsRd2VLWl01368", "structured_formatting": {"main_text": "Sydney Airport (SYD)", "main_text_matched_substrings": [[Object]], "secondary_text": "Sydney NSW, Australia"}, "terms": [{"offset": 0, "value": "Sydney Airport (SYD)"}, {"offset": 22, "value": "Sydney"}, {"offset": 29, "value": "NSW"}, {"offset": 34, "value": "Australia"}], "types": ["airport", "point_of_interest", "establishment"]}
> ```
> 
> for following onPress method
> 
> ```
> onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true
>                         console.log('details'=>,details)
>                         console.log('data=>',data)
>                        
>                      }}
> ```

You have to use and set to true (boolean) fetchDetails prop in component

**Comment by blinqwebstudio** [comment]
I realize this is an old issue, but the problem with taps on an absolute positioned list bubbling through, still happens. I tried everything but it turns out that the below essentially screws up all efforts...
```
<View
  style={[
    suppressDefaultStyles ? {} : defaultStyles.container,
    styles?.container,
  ]}
  pointerEvents='box-none'  // <-- THIS IS EVIL INCARNATE!
>
```
Eventually I solved it by slipping a layer in between my map and the list when the list is active. That layer captures the bubbling tap and unalives it before it reaches the map below it.
```
<View 
  style={{
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,    // Just above the map, below everything else
    elevation: 1,  // Android equivalent
    backgroundColor: '#00000033', // Add a semi-transparent background to show list laying over the layer
  }}
  onTouchStart={(e) => {
    // Block touches from reaching the map
    e.stopPropagation();
    this.setState({ showingAutocompleteDropdown: false });
  }}
  pointerEvents="auto"
/>
```
