### ISSUE TITLE
Tapping on currentLocation link, but saying "Don't Allow" produces unfriendly error

### ISSUE THREAD

**Issue by scott-metalab-zz** [FaridSafi/react-native-google-places-autocomplete#383]
I have added in the `currentLocation` prop to the GooglePlacesAutocomplete component and everything works well through its happy path. 

Although, when a user taps on "Don't allow" two things are to note:
1/ The `currentLocation` link remains on the list
2/ Tapping on the `currentLocation` link renders an alert stating "User denied access to location services"

Ideally it would be nice that if the user attempts to tap the link again, they are presented with the option to allow access again (although, I don't think this is possible, at least in iOS). 

If that is not possible, it would be ideal to be able to pass in a `deniedLocationAlertText` string to explain that they need to go to settings to allow the location. 

Is this possible to add into this component? 

I think a stretch goal here would be to pass through a custom request alert to "fake" ask the user to share their location, therefore you will have less chance to run into iOS's "ask once and then you can't ask again" policy. 

Appreciate any help or updates here. 🙌

**Comment by pmarconi** [comment]
+1 👍 

I am in a similar situation.
but, in my opinion, I think you should delegate to the developer what action should occur in case of error

for example, it may be the case that I do not want to show a native alert to an error of permissions not granted, and simply want to display my custom alert

thx!

**Comment by bell-steven** [comment]
@scott-metalab-zz To echo what @pmarconi said, this should probably be handled outside of the library.  As you noted, on iOS you can only ask for permission once.

You can use the `currentLocation` prop to control together with a library like `react-native-permissions` to decide whether to show  the current location option to the user.

In addition, current location doesn't work in RN v0.60.0+, see #541 for more. 

Let me know if i can close this.

**Comment by pangolingo** [comment]
@bell-steven I attempted to use your suggestion (use the `currentLocation` prop together with `react-native-permissions`, and it mostly works.

However changing the `currentLocation` prop does not re-render the `buildRowsFromResults()`/`datasource` list until the user edits the field and then clears it. It seems we need a way to immediately re-render the suggestion list when this `currentLocation `prop changes.
