### ISSUE TITLE
List view is white and pushes down map

### ISSUE THREAD

**Issue by DennisMuchiri** [FaridSafi/react-native-google-places-autocomplete#388]
Please fix the listview white background color and enable this component not to push down other components

**Comment by Lelelo1** [comment]
Try this: `styles={{
                            container: {
                                flex: 0,
                                position: 'absolute',
                                width: '100%',
                                zIndex: 1,
                            },
                            listView: {
                                backgroundColor: 'white'
                            }
                        }}`

**Comment by DennisMuchiri** [comment]
Sorry, already moved to https://github.com/tolu360/react-native-google-places/blob/master/BETA_README.md

**Comment by kamlesh1000** [comment]
> Try this: `styles={{ container: { flex: 0, position: 'absolute', width: '100%', zIndex: 1, }, listView: { backgroundColor: 'white' } }}`

You saved my day !! Thank You.

**Comment by ashryOlarm** [comment]
If you still have this issue try to give other components negative zIndex.
