### ISSUE TITLE
Remove `ActivityIndicatorIOS` and replace with `ActivityIndicator`

### ISSUE THREAD

**Issue by tgoldenberg** [FaridSafi/react-native-google-places-autocomplete#39]
This should be changed for the latest React Native. In fact, I get a warning when I use this package saying this.

**Comment by kevinL5** [comment]
I got the same warning with react-native 0.28

**Comment by myaskevich** [comment]
Hi @tgoldenberg !
This should be fixed in v1.2.1.
Please let me know if you still have any issues.
