### ISSUE TITLE
Blur when tapping outside of list

### ISSUE THREAD

**Issue by RWOverdijk** [FaridSafi/react-native-google-places-autocomplete#390]
How can I hide the list view when tapping outside of it? I'd like to blur when I lose focus, but it seems to maintain focus.

**Comment by Lelelo1** [comment]
I am trying to solve it by adding a keyboard listener (https://stackoverflow.com/questions/51606099/how-to-detect-when-keyboard-is-opened-or-closed-in-react-native) inside componentWillMount of GooglePlacesAutoComaplete.js

Then `this.setState({ listViewDisplayed: false })` inside that listener.

Then one can use a ScrollView around the all ones components which will dismiss the keyboard anywhere you press.

However I am encountering a bug where I have to press on the items for the list two times when putting it inside a ScrollView to get selected.

**Comment by graemec23** [comment]
@RWOverdijk did you find a solution to this? I have run into the same issue

**Comment by bell-steven** [comment]
You can try adding an onBlur function to `textInputProp`.

**Comment by bell-steven** [comment]
This issue is over a year old. I am going to close it. If you encounter this, and it is still a problem for you, please open a new issue (please try and follow the issue template).
