### ISSUE TITLE
How can I remove the country name from list 

### ISSUE THREAD

**Issue by AarshApple** [FaridSafi/react-native-google-places-autocomplete#392]
First of all thank you for building an awesome library for places API. I have integrated it successfully and now need only to know how to purge country name from the list. Example current scenario "Chicago, IL, USA". Instead i want "Chicago, IL" only. Thank you in advance for the solution.

**Comment by pytyl** [comment]
If you set region in your query, this should prevent it from showing country. For example:

```
query={{
              // available options: https://developers.google.com/places/web-service/autocomplete
              key: "yourkey",
              language: "en",
              region: "US",
              location: "34.043,-118.267",
              radius: 10000
            }}
```

**Comment by AarshApple** [comment]
@pytyl Thank you, this worked as a charm for me .Also closing this issue as it solves the problem.
