### ISSUE TITLE
How to get the TextInput value ?

### ISSUE THREAD

**Issue by claristhagerins** [FaridSafi/react-native-google-places-autocomplete#396]
I need the TextInput value to add places manually.
When I print console.log (text.name) or console.log (text.description), the result I get is undefined.

Here is my code:

![image](https://user-images.githubusercontent.com/44046114/55341825-8f43e400-54d1-11e9-8dd9-07a7cfa04868.png)

**Comment by Biplovkumar** [comment]
`onPress={(data, details = null) => { this.setState({
 address: details.formatted_address, 
neighbourhood: details.name, 
})`

**Comment by claristhagerins** [comment]
Thanks for you help, it's work!
