### ISSUE TITLE
New NPM release?

### ISSUE THREAD

**Issue by cxrod** [FaridSafi/react-native-google-places-autocomplete#401]
Hi, I see that some of the new features like GooglePlacesDetailsQuery prop is not released yet and is useful for reduce the billing, and has been more than 6 month since the last release. Are you planning to make a release any time soon?

**Comment by morenoh149** [comment]
Guess you can try using the latest version in GitHub or fork lock the version for your personal use.

**Comment by bell-steven** [comment]
This has since been released on NPM.
