### ISSUE TITLE
How can I get the search results also based on zip-code ?

### ISSUE THREAD

**Issue by AarshApple** [FaridSafi/react-native-google-places-autocomplete#408]
Thank you for building an awesome library. I have integrated it successfully and now need only to know how to get suggestions from zip-code . Example: When i write '35801' in  search text-input, It would give me 'Huntsville, AL' in suggestions. Thank you in advance for the solution.

**Comment by odaiderawi** [comment]
Hi @AarshApple 
Did you find any solution for your question ?

**Comment by bell-steven** [comment]
Hi @AarshApple.  You can use the '(region)' [type](https://developers.google.com/places/web-service/autocomplete#place_types) in the `query` prop.

```js
<GooglePlacesAutocomplete
        placeholder="Search"
        onPress={(data, details = null) => {
          // 'details' is provided when fetchDetails = true
          console.log(data, details);
        }}
        query={{
          key: GOOGLE_PLACES_API_KEY,
          language: "en", // language of the results
          types: "(regions)",
        }}
      />
```

![IMG_21947660E080-1](https://user-images.githubusercontent.com/13405567/82770893-41dab280-9e08-11ea-951d-7859a7809fac.jpeg)

If you are looking to only search within a specific country use 
```js
query={{
          key: GOOGLE_PLACES_API_KEY,
          language: "en", // language of the results
          types: "(regions)",
          components: "country:us",
        }}
```
