### ISSUE TITLE
how to hide autocomplete listview

### ISSUE THREAD

**Issue by aggounix** [FaridSafi/react-native-google-places-autocomplete#413]
I have a form with two autocomplete input and I want to hide the autocomplete listview when not using it
How to open the listview only when using the autocomplete

**Comment by bell-steven** [comment]
@aggounix  Can you please provide a fully reproducible example of this by showing some code or better yet, linking to a [snack](https://snack.expo.io)?

Also see the `listViewDisplay` prop, it might be helpful.
