### ISSUE TITLE
Get Input Text if Address not found 

### ISSUE THREAD

**Issue by joeljerushan** [FaridSafi/react-native-google-places-autocomplete#422]
I have wasted a lot of time to make it work, but this didn't workout im using following code to `setState` input value but not working.

```
textInputProps={{
    onChangeText : (c_address) => {
        alert(c_address)
    }
}}
```
![image](https://user-images.githubusercontent.com/10111309/59662658-016fbf00-91cb-11e9-9f48-1278f6cbeab4.png)

but when it comes to setState
```
textInputProps={{
    onChangeText : (c_address) => {
        this.setState({ address : c_address })
    }
}}
```
it is not showing dropdown 
![image](https://user-images.githubusercontent.com/10111309/59662980-b3a78680-91cb-11e9-9ce5-4984ce8fe9aa.png)

if i set `listViewDisplayed` to `true` not hiding list of dropdown after choose one option from it 

![image](https://user-images.githubusercontent.com/10111309/59663074-dc2f8080-91cb-11e9-8405-bf9d4896a6fc.png)

**Comment by N8sGit** [comment]
I'm having the same issue. I'm working on a solution using refs to access the node directly. It seems to do the trick. This code lets you access the input value onPress of a button 

<img width="467" alt="Screen Shot 2019-06-20 at 6 02 50 PM" src="https://user-images.githubusercontent.com/20302783/59884218-ac2bdd00-9385-11e9-9337-74a5d4c0c7a1.png">

**Comment by Jhony-Reyes** [comment]
Same here!

This work
```
textInputProps={{
    onChangeText : text => {
        console.log(text);
    }
}}

// And this

textInputProps={{
    onChange : ({ nativeElement: { text }}) => {
        console.log(text);
    }
}}
``

This does'nt work
```
textInputProps={{
    onChangeText : text => {
        this.setState({addresText: text});
    }
}}

// And this

textInputProps={{
    onChange : ({ nativeElement: { text }}) => {
        this.setState({addresText: text});
    }
}}
```

**Comment by amitbravo** [comment]
Did you find any way to update state ?

**Comment by ajaysaini-sgvu** [comment]
@Jhony-Reyes Have you found solution for this ?

**Comment by JacopoKenzo** [comment]
I'm doing this to detect the changes and set the state:

```
textInputProps={{
   onChange: (object) => {
       console.log(object.nativeEvent.text);
       this.setState({address: object.nativeEvent.text})
   }
}}
```

Hope it helps!

**Comment by dejavu20180307** [comment]
What you need to do is to implement shouldComponentUpdate, and for the state variable you set in the textInputProps onChange method, you need to return false to prevent screen from updating.

**Comment by bell-steven** [comment]
I just tried reproducing this using the setState hook, and it worked fine for me. Please open a new issue (please follow the issue template) if this is still a problem for you.
