### ISSUE TITLE
Document filterReverseGeocodingByTypes values

### ISSUE THREAD

**Issue by morenoh149** [FaridSafi/react-native-google-places-autocomplete#428]
The readme and example do not clarify the possible options for filterReverseGeocodingByTypes and what each value is good for. What is the google documentation for each value? Lets link out to that document from the readme.

**Comment by bell-steven** [comment]
Hey @morenoh149 would you be able to open a PR for this?

**Comment by morenoh149** [comment]
I dont know where to link to

**Comment by bell-steven** [comment]
With the addition of the types file, this actually now gets suggested why typing it in. 
See [here](https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/589027fb4f75b6e513715461356d674a07bb843a/GooglePlacesAutocomplete.d.ts#L358) and the available options [here](https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/589027fb4f75b6e513715461356d674a07bb843a/GooglePlacesAutocomplete.d.ts#L166). 

I believe [this](https://developers.google.com/maps/documentation/geocoding/intro#Types) might be the google doc you are looking for.

**Comment by sirtok4** [comment]
Im adding `filterReverseGeocodingByTypes={['street_address','address','establishment']}` to my code but it is not working. It gives me the cities as well. What should I do?

**Comment by NoahSimajji** [comment]
How do you call the filtered data out? I couldn't take it out. Just want to console.log the filtered type.
