### ISSUE TITLE
conflict with watchPosition

### ISSUE THREAD

**Issue by lyudad** [FaridSafi/react-native-google-places-autocomplete#431]
version 1.3.9

If turn on geolocation watcher (https://github.com/Agontuk/react-native-geolocation-service) and try search something list automatically close every time when new coordinates come. 
Issue not because of re render component I have checked. Even if put just put console log autocomplete list disappear

this.watchId = Geolocation.watchPosition(
      (position) => {
        console.log('position', position)
      },
      (error) => {
        console.log('getLocationUpdates', error);
      },
      { enableHighAccuracy: true, distanceFilter: 0, interval: 5000, fastestInterval: 2000 }
    );

**Comment by bell-steven** [comment]
HI @lyudad can you please provide a reproducible example of this by showing some code or better yet, lining to a [snack](https://snack.expo.io)?

**Comment by lyudad** [comment]
I rewrite to own component as haven't found solution that time
