### ISSUE TITLE
Search results text goes off-screen for long results

### ISSUE THREAD

**Issue by vizFlux** [FaridSafi/react-native-google-places-autocomplete#432]
I am trying to handle the search results text goes off-screen when the text of a result is too long. I've tried

```JavaScript
row: {
  flex: 0,
},

description: {
  flexShrink:  1,
},
```

and #152 

but no luck as I need to render the text in a new line rather than ellipsis.

**Comment by bell-steven** [comment]
@vizFlux can you please provide a reproducible example of this by showing some code or better yet, lining to a [snack](https://snack.expo.io)?

Also, perhaps [this](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/429#issuecomment-574553219) solve your issue?
