### ISSUE TITLE
How to remove border on the input?

### ISSUE THREAD

**Issue by msqar** [FaridSafi/react-native-google-places-autocomplete#434]
So there seems to be a gray border around the inputContainer, even though I attempted putting borderWidth: 0, borderColor: 'transparent', to `textInputContainer`, to `textInput`, to `container`, nothing removes that border.

Any ideas? Thanks.

**Comment by msqar** [comment]
Nevermind, i found it. Had to check the lib. If anyone is under the same doubt just do this:

```
                        borderTopColor: CommonStyles.TRANSPARENT,
                        borderBottomColor: CommonStyles.TRANSPARENT,
                        borderTopWidth: 0,
                        borderBottomWidth: 0,
```

**Comment by nimrodbens** [comment]
> Nevermind, i found it. Had to check the lib. If anyone is under the same doubt just do this:
> 
> ```
>                         borderTopColor: CommonStyles.TRANSPARENT,
>                         borderBottomColor: CommonStyles.TRANSPARENT,
>                         borderTopWidth: 0,
>                         borderBottomWidth: 0,
> ```

thank you so much for that!
