### ISSUE TITLE
Issue with textAlign 'right' on TextInput when pressing 'space'

### ISSUE THREAD

**Issue by msqar** [FaridSafi/react-native-google-places-autocomplete#435]
I'm customizing the text input to be textAligned right, but there's a current reactnative bug for texts that are right aligned and pressing space, the space character won't be shown, you can press 100 times the space, it will add them, but you won't see it until you press another character != than space.
Now, there might be a way to solve it by doing:

```
_replaceSpace(str) {
  return str.replace(/\u0020/, '\u00a0')
}
```

On the value prop. But I can't access to state value using this component from parent.

Any workaround to fix this?

This is the react-native's github issue: https://github.com/facebook/react-native/issues/10218

**Comment by bell-steven** [comment]
Hi @msqar is this still an issue? Can you please provide a reproducible example of this by showing some code or better yet, lining to a [snack](https://snack.expo.io)?
