### ISSUE TITLE
Crash on web

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [FaridSafi/react-native-google-places-autocomplete#436]
Because of how you export this, this module doesn't work well with expo-web. 

I've changed it to export like this instead:

```
export { GooglePlacesAutocomplete, create };
```

Now it works.

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Please how do I submit a PR? I get access denied.

**Comment by leoncheng57** [comment]
This is a great fix ^

**Comment by ceddybi** [comment]
+1 for the export

**Comment by bell-steven** [comment]
There are a few PRs open for this #439 #445 #542 

I'll try to get one of these merged soon.
