### ISSUE TITLE
RE OPEN: Is it possible to limit the number of results that are been rendered?

### ISSUE THREAD

**Issue by MikaelConecto** [FaridSafi/react-native-google-places-autocomplete#438]
The answer was not valid and the issue was closed. How can I limit the number of results?

**Comment by jmhungdev** [comment]
The default return objects is 20. There's no way to return less than 20 (unless the data that you are querying is less than 20). However you can return more than 20 results by accessing the page_token attribute.  [here](https://stackoverflow.com/questions/9614258/how-to-get-20-result-from-google-places-api)

All you need to do is do write some javascript to limit the amount of results into an new array 
suppose your data is returned with an array **data**. 
let newData = data.slice(0,x)
where x is the amount of results you want to limit to.

hope this helps.

**Comment by bell-steven** [comment]
I don't believe that this is possible with the Google Places API.
