### ISSUE TITLE
Android works perfect, IOS pop-up list appears somewhere under the list bellow

### ISSUE THREAD

**Issue by popadorin** [FaridSafi/react-native-google-places-autocomplete#443]
I've tried to set zIndex on both Autocomplete component to be bigger than the FlatList bellow I'm using....Also tried to set up zIndex:0 to FlatList, also didn't work.

Tried to put position:'absolute' and other stuff - none did work.

**My versions:** 
react-native: 0.59.5
react-native-google-places-autocomplete: 1.3.9

Can anybody help please?

**Comment by choukat** [comment]
Hi, I had the same problem, after many tries, I put the autocomplete component inside <View style={{zIndex:9999}}> and it works for me.

**Comment by CmDogsInc** [comment]
yep it works, but the element below the Autocomplete component with your solution  were under neath

**Comment by bell-steven** [comment]
Hi @popadorin can you please provide a reproducible example of this by showing some code or better yet, lining to a [snack](https://snack.expo.io)?

**Comment by walterdl** [comment]
@popadorin did you solved it?

**Comment by walterdl** [comment]
@choukat it worked for me. Do you have any idea why it works? I don't like things that work like magic.

**Comment by popadorin** [comment]
I happen so far ago, I don't have already that code snippet. Next time I'll also upload some code example.
