### ISSUE TITLE
Calling triggerFocus isn't working

### ISSUE THREAD

**Issue by FRizzonelli** [FaridSafi/react-native-google-places-autocomplete#446]
Hello there, and thanks for the awesome lib :)

I'm trying to focus the textinput inside autocomplete, but unfortunately method _triggerFocus_ isn't working :( It literally does nothing.

Any advice on how to procede?

**Comment by MayoudP** [comment]
Hello, find a trick ?

**Comment by FRizzonelli** [comment]
@MayoudP Unfortunately nope :(

**Comment by ykal** [comment]
Hello there,

First, get a reference to `GooglePlacesAutocomplete` Component and the call `triggerFocus` like bellow.

`
const [autoComplete, setAutoComplete] = useState(null);

// when ever the coponent is mounted the text input will be on focus
 useEffect(() => {
        if (autoComplete !== null) {
            autoComplete.triggerFocus();
        }
    }, [autoComplete]);

<GooglePlacesAutocomplete
    ref={ref => setAutoComplete(ref) }
    // other props here
/>
`

**Comment by bell-steven** [comment]
Hi @FRizzonelli can you please provide a reproducible example of this by showing some code or better yet, lining to a [snack](https://snack.expo.io)?

**Comment by bell-steven** [comment]
I can't reproduce this. Please open a new issue if this is still a problem.

**Comment by FRizzonelli** [comment]
Dude this isn't fixed. I need a moment to create the snack. By the way, if u try to pass the ref of the textinput to googleplaces, and try to call "focus()" on it, it doesn't work.

**Comment by FRizzonelli** [comment]
Plus, no one answered for like months and you close it after 2 working days.

**Comment by bell-steven** [comment]
Feel free to open a new issue. 
This is an open source project.  There are no guarantees, SLAs, or support timelines.  I just joined this repo as a maintainer, and I am trying to bring the library up to date and go through the over 100 open issues and 30 PR to get some high priority work done.  This issue was opened last summer and there is one potential answer here with no response.  I thought it was reasonable to close the issue at that point.  
Closed != fixed

**Comment by iscosta** [comment]
get ref onFocus inside textInputProps 

`constructor(props) {
    super(props);
    this.textInput = React.createRef();
  }

<GooglePlacesAutocomplete
    textInputProps={{
    ref: this.textInput,
    }}
/>

and call:  this.textInput.current.focus()
`

**Comment by iscosta** [comment]
get ref onFocus inside textInputProps

```
constructor(props) {
super(props);
this.textInput = React.createRef();
}

<GooglePlacesAutocomplete
textInputProps={{
ref: this.textInput,
}}
/>

and call => this.textInput.current.focus()
```
