### ISSUE TITLE
navigator.geolocation.getCurrentLocation is undefined

### ISSUE THREAD

**Issue by Alishgiri** [FaridSafi/react-native-google-places-autocomplete#447]
I have fixed this issue by the following steps,

In GooglePlacesAutocomplete.js file,

importing Geolocation from '@react-native-community/geolocation' at the top,
and
replacing `navigator.geolocation.getCurrentPosition` to `Geolocation.getCurrentPosition`

**Comment by joeljerushan** [comment]
i'm using RN0.60 https://facebook.github.io/react-native/docs/geolocation and please post where i should make this changes since RN0.60 auto loads navigator.geolocation i Couldn't find the path for this change

**Comment by Alishgiri** [comment]
@joeljerushan Inside node_modules

> node_modules/react-native-google-places-autocomplete/GooglePlacesAutocomplete.js

**Comment by carmelocatalfamo** [comment]
I fixed it, refer to [@react-native-community/geolocation](https://github.com/react-native-community/react-native-geolocation#migrating-from-the-core-react-native-module)

> If you need to have geolocation API aligned with the browser (cross-platform apps), or want to support backward compatibility, please consider adding following lines at the root level, for example at the top of your App.js file (only for react native):
> ```
> navigator.geolocation = require('@react-native-community/geolocation');
> ```

**Comment by ralphevmanzano** [comment]
@Alishgiri following your instructions I got, `NativeModule.RNCGeolocation is null. To fix this issue try these steps: Run 'react-native-link' etc` do you know how can I fix this?

**Comment by Alishgiri** [comment]
> @Alishgiri following your instructions I got, `NativeModule.RNCGeolocation is null. To fix this issue try these steps: Run 'react-native-link' etc` do you know how can I fix this?

I will assume that you have installed geolocation package,

>  npm install or yarn add @react-native-community/geolocation

and if that issue you are facing is on Android (for RN <= 60.4),
> and if you are using React native navigation, add the following to MainApplication.java

`import com.reactnativecommunity.geolocation.GeolocationPackage;
protected List<ReactPackage> getPackages() {
...
new GeolocationPackage(),
...
}
`

or if the issue is on iOS (react-native link @react-native-community/geolocation should work for RN < 59.x). for RN > 60.x add podspec to podfile:
`  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
`

**Comment by LucasMallmann** [comment]
@carmelocatalfamo a quick question. Where am I supposed to edit this? Change this navigator config?
