### ISSUE TITLE
Only Sydney city and around search results.

### ISSUE THREAD

**Issue by amitbravo** [FaridSafi/react-native-google-places-autocomplete#452]
What is the current behavior?
Its showing results out of radius

What is the expected behavior?
I want results only from Sydney and radius 100km only

Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?
v7.2.1

I am using following code for a Sydney Taxi App: I need only results from Sydney.

 query={{
                    
                       key: '<mykey>',
                       language: 'en', // language of the results
                       location: '-33.8473566,150.6517734',
                       region: 'Australia',
                       radius: 1000,
                     }}
when I type "Pearl" for Pearl Beach for Australia , it also shows Pearl Harbor of USA, I want the list only from Sydney and around with in max 100KM area. how could I do it , I tried to use strictbound but it didn't work at all. it nulled the result.

**Comment by nyzszn** [comment]
`1000M =  1K`
Please first correct your radius to `radius:100000`

**Comment by bell-steven** [comment]
It looks like this is resolved.  Feel free to open a new issue if this is still a problem for you.
