### ISSUE TITLE
how to change search result to multiline

### ISSUE THREAD

**Issue by h4m3d66** [FaridSafi/react-native-google-places-autocomplete#454]
hi, 
How can I make search result multiline instead of horizontal scroll?

**Comment by sumukhah** [comment]
Hey,
You can specify it by providing an arguement "multiline", it takes boolean values into the TextInput field

**Comment by Adr1ann** [comment]
@sumukhah  isn't working. Any solution here?

**Comment by smartsuhani** [comment]
textInputProps={{multiline: true, blurOnSubmit: true}}

**Comment by bell-steven** [comment]
@h4m3d66 see [this](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/429#issuecomment-574553219) issue.
