### ISSUE TITLE
navigator.geolocation.getCurrentLocation is undefined and depreciated

### ISSUE THREAD

**Issue by presencewebdesign** [FaridSafi/react-native-google-places-autocomplete#456]
**How to fix in the meantime** 

**navigator.geolocation.getCurrentLocation is  now depreciated**, so you have to use @react-native-community/geolocation

Unfortunately react-native-google-places-autocomplete have not upgraded this yet.

yarn add @react-native-community/geolocation
open file location 
"node_modules/react-native-google-places-autocomplete/GooglePlacesAutocomplete.js"

add this line at the top 
import Geolocation from '@react-native-community/geolocation';

Then change 
navigator.geolocation.getCurrentPosition to Geolocation.getCurrentPosition

**Comment by hoonblizz** [comment]
There's a solution for this. 
```
navigator.geolocation = require('@react-native-community/geolocation');
```

**Comment by lookingsoft** [comment]
i think you should update your package with geolocation from @react-native-community and avoid using navigator.geolocation.

**Comment by guilhermepontes** [comment]
I'll release a new version of this package soon, all the deprecated warnings will be soon gone!

**Comment by maheshdatta** [comment]
Thank you for this great library. 
Is this fixed now? Getting an error as below 

<img width="491" alt="Screen Shot 2020-03-17 at 10 47 43 PM" src="https://user-images.githubusercontent.com/11534062/76882954-631ba180-68a1-11ea-8a63-f5a04f543734.png">
