### ISSUE TITLE
Using onChangeText in the textInputProps breaks the autocomplete

### ISSUE THREAD

**Issue by trinhhien272** [FaridSafi/react-native-google-places-autocomplete#458]
Hi , 
Issues "Using onChangeText in the textInputProps breaks the autocomplete" has been fixed at version 1.3.5

But I am having this same problem as in version 1.3.9.

Can console value textInput. But Cannot execute any method.

`textInputProps={{
          onChangeText: text => {
            console.log(text);
            this.props.screen._changeKeyword(text);
          }
        }}`

_Originally posted by @trinhhien272 in https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/196#issuecomment-541486742_

**Comment by ptcasa** [comment]
I have same problem too, after upgrade to react-native latest version 0.61.2, autocomplete was crashed(can't touch any more on app).

**Comment by mtalhagaoglu** [comment]
hi! has anyone been able to solve this problem?

**Comment by caleb-42** [comment]
@trinhhien272 This problem tends to come up when you are changing state from within your onChangeText prop. Store the text argument in a class property or variable (for example this.text) and use a button to carry out an onPress action with the following command - this.props.screen._changeKeyword(this.text);

**Comment by Rajdeepc** [comment]
Hi @caleb-42 / @trinhhien272 

My use is when Google Places API doesnt return any response  watever the user types in i am sending it back to my parent component like :
```
props.selectedAddress(value, {geolocation: '', name: value}); // passing the value to the parent
```
But while the Google Places API gives response, the response doesnt show up. 
Commenting out
```
setLocation(value); // setting the value
props.selectedAddress(value, {geolocation: '', name: value}); // passing the value to the parent
```
it works. Any solution how can i achieve this try catch scenario?
    
Code below:
```
textInputProps={{
onChangeText: (value) => {
setLocation(value); // setting the value
props.selectedAddress(value, {geolocation: '', name: value}); // passing the value to the parent
return value
 },
 }}
```

**Comment by bell-steven** [comment]
@trinhhien272  Can you please provide a fully reproducible example of this by showing some code or better yet, linking to a [snack](https://snack.expo.io)?
