### ISSUE TITLE
 Circular indeterminate `ProgressBarAndroid`is deprecated. Use `ActivityIndicator` instead.

### ISSUE THREAD

**Issue by robtassl** [FaridSafi/react-native-google-places-autocomplete#46]
On android, RN 0.31.0 with `fetchDetails={true}`, I get the following error -  Circular indeterminate `ProgressBarAndroid`is deprecated. Use `ActivityIndicator` instead.

Proposed solution - Remove the condition that returns the `ProgressBarAndroid` component in `_getRowLoader()` in `GooglePlacesAutocomplete.js`.

I can submit a PR for this, just wanted to get a contributors ok/opinion first.

**Comment by myaskevich** [comment]
Hi @robtassl 

Thanks for you report!

Could you please let me know which version you're on?

Max

**Comment by robtassl** [comment]
Hey @myaskevich 

Thanks for the quick reply!

Versions:
"react-native": "^0.31.0".
"react-native-google-places-autocomplete": "^1.2.2"

**Comment by myaskevich** [comment]
@robtassl 

Fixed since v1.2.0
