### ISSUE TITLE
Change "currentLocationLabel" with current street name

### ISSUE THREAD

**Issue by CmDogsInc** [FaridSafi/react-native-google-places-autocomplete#470]
I've added a state on currentLocationLabel 

` currentLocationLabel={this.stateCurrentStreet}`

but return "Current location"

**Comment by bell-steven** [comment]
@CmDogsInc can you provide a reproducible example of this by showing some code or better yet, lining to a [snack](https://snack.expo.io)?

**Comment by bell-steven** [comment]
Closing. Please open a new issue (with clear reproduction steps/code) if this is a problem for you.
