### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by hopewise** [FaridSafi/react-native-google-places-autocomplete#471]
When I try to access the service, I get this error:

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://maps.googleapis.com/maps/api/place/autocomplete/json?&input=AB&key=XXX&language=en&region=US&types=address&components=country%3Aus with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

Has any got this issue with Android?

**Comment by bell-steven** [comment]
Hi @hopewise can you please provide a reproducible example of this by showing some code or better yet, lining to a [snack](https://snack.expo.io)?

**Comment by bell-steven** [comment]
I can't reproduce this. Please open a new issue if you encounter this issue.
