### ISSUE TITLE
Only display COUNTRIES name (and not city or federal states)

### ISSUE THREAD

**Issue by MayoudP** [FaridSafi/react-native-google-places-autocomplete#474]
Hello quick question, 
I wasn't able to find a solution for this problem. 
Basically : I want to display only the countries 's name matching with the filter. 
* Img => 
<img width="340" alt="Capture d’écran 2019-11-25 à 17 01 54" src="https://user-images.githubusercontent.com/48682041/69556614-51865500-0fa5-11ea-9298-13571580b8f2.png">

For example above, it should not display `Frankfurt, Franklin, Franca or Framinghan` but only `FRANCE`.

This is how I wrote my `<GooglePlacesAutocomplete/>` : 

```
 <GooglePlacesAutocomplete
                        minLength={2} // minimum length of text to search
                        query={{
                            key: 'my-key',
                            language: getLanguageCode(), // language of the results
                            types: '(regions)' // default: 'geocode'
                        }}
                        nearbyPlacesAPI='GooglePlacesSearch' // Which API to use: GoogleReverseGeocoding or GooglePlacesSearch
                        filterReverseGeocodingByTypes={['country', 'political']} // filter the reverse geocoding results by types 
                        debounce={200} // debounce the requests in ms. Set to 0 to remove debounce. By default 0ms.
                    />
```

Any suggestions/solutions ?

**Comment by MayoudP** [comment]
Found a trick, I used a custom rendering for the results received.
`renderRow={row => this.renderRow(row)}`
and 
```
 renderRow(item) {
        return (
            _.isEqual(path(["types", "0"], item), "country") ?
                <View>
                    <Text>{item.description}</Text>
                </View> : null)
    }
```
So checking that the type of the result is well a country and not a locality or whatever else... It would be nice tho maybe to add this feature directly in the props of the lib like ==> 

name  | type
 ------|-----
**onlyShowCountry** | boolean

or

**Comment by hiteshdua1** [comment]
@MayoudP  It shows me blank rows in between where i return `null` , Did you discard the those result for you ? how do we do that ?

**Comment by kabus202** [comment]
@hiteshdua1  did you manage to figure out how to prevent the blanks?
