### ISSUE TITLE
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.

### ISSUE THREAD

**Issue by archana-iron** [FaridSafi/react-native-google-places-autocomplete#475]
After upgrading to react-native 0.61 I get a lot of warnings like that:

> VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.

What is the other VirtualizedList-backed container that i should use, and why is it now advised not to use like that?

It comes when I am clicking on autocomplete.

**Comment by archana-iron** [comment]
Any Solution??

**Comment by Rhomennik** [comment]
ONly problem :(

**Comment by vendeesh** [comment]
I have faced sam issues. Have any one got solution?

**Comment by archana-iron** [comment]
> I have faced same issues. Have any one got solution?

Not yet :(

**Comment by natanaeladit** [comment]
temporary solution

`import {YellowBox} from 'react-native';`

`YellowBox.ignoreWarnings([
      'VirtualizedLists should never be nested', // TODO: Remove when fixed
    ]);`

**Comment by CharlotteRdn** [comment]
I face the same issue, did you resolve this ?

**Comment by mayupat13** [comment]
I too have same issue. Any solution?

**Comment by kopax** [comment]
I have a ScrolView within a ListView and I get this error.

**Comment by sharma-archu** [comment]
> I too have same issue. Any solution?

not yet.

**Comment by yuritoledo** [comment]
+ 1

**Comment by ranggabadrus** [comment]
any update?

**Comment by forster007** [comment]
Any update?

**Comment by YahiaBadr** [comment]
any updates?

**Comment by rajnishcoder** [comment]
any update?

**Comment by arjun-ravi** [comment]
Any update?

**Comment by bell-steven** [comment]
Can someone please provide a fully reproducible example of this by showing some code or better yet, linking to a [snack](https://snack.expo.io)?  I cannot reproduce this.

**Comment by bell-steven** [comment]
Closing, as I can't reproduce this. Please open a new issue (with code reproduction or steps) if you encounter this.

**Comment by Hervera** [comment]
This happens when there is a ScrollView as a parent element

**Comment by omarsoufiane** [comment]
i guess this happens to everyone using nativebase theme copntainers. list do not display whenever there is an error in api call

**Comment by AmityTek** [comment]
1 year after ... this issue is not fix really ??

**Comment by KrisLau** [comment]
@bell-steven I can't reproduce this in a snack but it happens on my bare react native projects

**Comment by huzaifaaak** [comment]
Also happening when using KeyboardAwareScrollView

**Comment by shmkane** [comment]
Also having this issue.

**Comment by rubydeve** [comment]
```
<ScrollView horizontal={false} style={{flex: 1, width: '100%', height: '100%'}}>
      <ScrollView horizontal={true} style={{flex: 1, width: '100%', height: '100%'}}>
            <GooglePlacesAutocomplete ... />
      </ScrollView>
</ScrollView>
``` 
use horizontal true false . Works 

- [ ]

**Comment by StevenL98** [comment]
> ```
> <ScrollView horizontal={false} style={{flex: 1, width: '100%', height: '100%'}}>
>       <ScrollView horizontal={true} style={{flex: 1, width: '100%', height: '100%'}}>
>             <GooglePlacesAutocomplete ... />
>       </ScrollView>
> </ScrollView>
> ```
> 
> use horizontal true false . Works

This works! But now my styling is messed up, with the default styling the textinput will only stretch to full width if I start typing, do you know how I can fix it such that the textInput is always full width?

**Comment by rubydeve** [comment]
> > ```
> > <ScrollView horizontal={false} style={{flex: 1, width: '100%', height: '100%'}}>
> >       <ScrollView horizontal={true} style={{flex: 1, width: '100%', height: '100%'}}>
> >             <GooglePlacesAutocomplete ... />
> >       </ScrollView>
> > </ScrollView>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > use horizontal true false . Works
> 
> This works! But now my styling is messed up, with the default styling the textinput will only stretch to full width if I start typing, do you know how I can fix it such that the textInput is always full width?

<ScrollView horizontal={false} style={{flex: 1, width: '100%', height: '100%'}}>
      <ScrollView horizontal={true} style={{flex: 1, width: '100%', height: '100%'}}>
            <GooglePlacesAutocomplete  
                          styles={{
			                container: {
					              width: '100%',
			              },
			              textInputContainer: {
				                    width: '100%',
				      },
			             textInput: {
			  	                   width: '100%',
			             }
                         }}
             />
      </ScrollView>
</ScrollView>

**Comment by marquina-abreu** [comment]
![Screen Shot 2021-11-19 at 10 30 05 PM](https://user-images.githubusercontent.com/34238806/142711447-ca6d040e-4b4f-4cc0-b7bf-96642121b726.png)

```<Content
       horizontal={false}
       contentContainerStyle={styleContent}
       keyboardShouldPersistTaps="handled"
        showsVerticalScrollIndicator={false}>

      <ScrollView horizontal={true} contentContainerStyle={{flex: 1, width: '100%', height: '100%'}}>
           <GooglePlacesAutocomplete /> ......
       </ScrollView>
```

This is how it worked for me

**Comment by Abusayid693** [comment]
> ```
> <ScrollView horizontal={false} style={{flex: 1, width: '100%', height: '100%'}}>
>       <ScrollView horizontal={true} style={{flex: 1, width: '100%', height: '100%'}}>
>             <GooglePlacesAutocomplete ... />
>       </ScrollView>
> </ScrollView>
> ```
> 
> 
>      
>   
> 
> use horizontal true false . Works

This works fine for me
