### ISSUE TITLE
How to check input text changes using this package? What prop is used to detect text input changes?

### ISSUE THREAD

**Issue by archana-iron** [FaridSafi/react-native-google-places-autocomplete#476]
I have created a custom component for this and want to detect input text changes. How I can detect input text changes without using "onPress" prop. Because here I want to add the prop for input changes.
Please help!

**Comment by felipearosemena** [comment]
@archana-iron You can pass a `textInputProps` prop to listen to events on the underlying input

**Comment by archana-iron** [comment]
Yes, I am using this, but can you explain to me how can I call a function on input change?

```
textInputProps={{
					onChangeText: () => {
						this.onChangeAddress(onChangeText);
						return onChangeText;
					},
				}}
```

**Comment by jebinILeaf** [comment]
textInputProps={{
                onChangeText: txt => {
                  //this.setState({ searchText: txt });
                  this._yourFunction(txt)
                }
              }}

**Comment by archana-iron** [comment]
I got a solution, just need to return "onChangeText" value here, because it's not a function type. 
So I have returned on change value and called a function inside that section like this::
```
textInputProps={{
	onChangeText: (value) => {
		this.onChangeAddress(value);
		return value;
	},
}}
```
