### ISSUE TITLE
Scrollview with GooglePlacesAutocomplete doesn't work!

### ISSUE THREAD

**Issue by Rhomennik** [FaridSafi/react-native-google-places-autocomplete#477]
I was wondering if anyone knows how I can hide this error? I even tried to render a custom list but it still gives the error why it loads _renderRow

![image](https://user-images.githubusercontent.com/24496303/69995547-0cc36680-152f-11ea-97b1-0c9af162bf38.png)

### Example code

```javascript
import React from 'react';
import {Text, ScrollView} from 'react-native';
import {GooglePlacesAutocomplete} from 'react-native-google-places-autocomplete';

const GooglePlacesInput = () => {
  return (
    <ScrollView>
      <GooglePlacesAutocomplete />
    </ScrollView>
  );
};

export default GooglePlacesInput;```

**Comment by omkarrong** [comment]
I am also facing this issue. If you got the solution please drop here too.
Thank you in advance.

**Comment by dominik992** [comment]
Same here

**Comment by neosowmiya** [comment]
i fixed this issue by inclluding keyboardShouldPersistTaps='always' and listViewDisplayed={false} in your scroll view JSX

**Comment by dmedelba** [comment]
> i fixed this issue by including keyboardShouldPersistTaps='always' and listViewDisplayed={false} in your scroll view JSX

this worked for me ! thx

**Comment by tobilastik** [comment]
> i fixed this issue by including keyboardShouldPersistTaps='always' and listViewDisplayed={false} in your scroll view JSX

worked for me! thanks!

**Comment by WAQAZ0178** [comment]
> I am also facing this issue. If you got the solution please drop here too. Thank you in advance.

this is happening because of scrollView

**Comment by youcefswoo** [comment]
check [this](https://stackoverflow.com/questions/69817827/react-native-google-places-autocomplete-does-not-work-in-a-scroll-view-virtuali/78215227#78215227) solution

**Comment by emmadal** [comment]
> check [this](https://stackoverflow.com/questions/69817827/react-native-google-places-autocomplete-does-not-work-in-a-scroll-view-virtuali/78215227#78215227) solution

@youcefswoo thanks. that's work for me.

**Comment by shubhamtriosoft** [comment]
not working
