### ISSUE TITLE
Input does not support non latin characters

### ISSUE THREAD

**Issue by aymkin** [FaridSafi/react-native-google-places-autocomplete#479]
For example: Cyrillic or Arabic letters cannot be entered in the search input

**Comment by bell-steven** [comment]
I can't seem to reproduce this.

Please open a new issue if this still doesn't work in the latest version of the library. 

![IMG_3321](https://user-images.githubusercontent.com/13405567/81759137-dac90f80-9491-11ea-9aa4-968a28d4c27f.PNG)
![IMG_3320](https://user-images.githubusercontent.com/13405567/81759141-dbfa3c80-9491-11ea-87c0-033d0db9480f.PNG)
