### ISSUE TITLE
Warning: componentWillMount has been renamed

### ISSUE THREAD

**Issue by aymkin** [FaridSafi/react-native-google-places-autocomplete#480]
Looks like the library should use the modern react hooks instead of deprecated one

**Comment by lmuntaner** [comment]
Yep, I have the same warning 🙄

**Comment by guilhermepontes** [comment]
I'll be releasing the version 2.0.0 of this package soon

**Comment by ws7one** [comment]
Any ETA on 2.0.0

**Comment by ItsRhen** [comment]
I second. This warning is still present on my install. I'm at the latest. Thanks for a great library.
