### ISSUE TITLE
i want to restrict just for two countries

### ISSUE THREAD

**Issue by sohel-tech** [FaridSafi/react-native-google-places-autocomplete#485]
components: 'country:ca'
How can i add one more country in the above line

**Comment by rizshivalli** [comment]
components:['country:gb', 'country:us'],

**Comment by sohel-tech** [comment]
components:['country:gb', 'country:us'] --- This one is not working.

bit i found the answer in another issue ----components: 'country:ca|country:us'

**Comment by rizshivalli** [comment]
close the issue
