### ISSUE TITLE
Not working with KeyboardAwareScrollView

### ISSUE THREAD

**Issue by igibliss00** [FaridSafi/react-native-google-places-autocomplete#486]
I'm currently using `KeyboardAwareScrollView` with `react-native-google-places-autocomplete` and only when the auto-complete component is within `KeyboardAwareScrollView`, the drop-down suggested addresses from Google does not respond to presses.  When the aut0-complete component is without `KeyboardAwareScrollView`, the component works as expected. 

The expected behavior is that when the suggested addresses are clicked, the clicked addresses can be used in the `onPress` property of `react-native-google-places-autocomplete`, but when the component is placed within `KeyboardAwareScrollView`, the suggested list disappears as soon as the list is clicked, and no addresses are selected or retrieved. 

```js
const CreatePost = ({ navigation }) => {
    const [animation] = useState(new Animated.Value(0))
    useEffect(() => {
        Keyboard.addListener('keyboardWillShow', keyboardWillShow)
        Keyboard.addListener('keyboardWillHide', keyboardWillHide)
        return () => {
            Keyboard.removeListener()
        }
    }, [])

    const keyboardWillShow = e => {
        Animated.timing(animation, {
            duration: e.duration,
            toValue: 1,
        }).start()
    }

    const keyboardWillHide = e => {
        Animated.timing(animation, {
            duration: e.duration,
            toValue: 0,
        }).start()
    }

    const opacityInterpolate = animation.interpolate({
        inputRange: [0, 1],
        outputRange: [1, 0]
    })

    const photoStyles = {
        opacity: opacityInterpolate
    }

    const submitHandler = async (value, action) => {}

    return (
        <KeyboardAwareScrollView>
            <Form submitHandler={submitHandler} />
        </KeyboardAwareScrollView>

    )
}
```
I placed `react-native-google-places-autocomplete` within `Formik`:
```js
const Form = ({
    submitHandler,
}) => {
const [addressAnimation] = useState(new Animated.Value(0))
const [addressHeight, setAddressHeight] = useState()
const yCoordinate = heightPosition - addressHeight

const onFocusAddressAutoComplete = () => {
    // onFocus Animation
}
const onBlurAddressAutoComplete = () => {
    // onBlur Animation
}

const translateInterpolate = addressAnimation.interpolate({
    inputRange: [0, 1],
    outputRange: [0, !!yCoordinate && yCoordinate],
    extrapolate: "clamp",
})

const addressStyle = {
    transform: [
        {
            translateY: translateInterpolate
        }
    ]
}

const onFocusProps = () => {
    setHideList(true)
    onFocusAddressAutoComplete()
}

const onBlurProps = (param, callback) => {
    callback(param)
    onBlurAddressAutoComplete()
    setHideList(false)
}

return (
    <View style={styles.container} >
        <Formik
            initialValues={initialValues}
            onSubmit={(value, action) => submitHandler(value, action)}
            validationSchema={yup.object().shape({
                address: yup
                    .string()
                    .min(5)
                    .required(),
            })}
        >
            {({
                values,
                handleChange,
                errors,
                setFieldTouched,
                touched,
                isValid,
                handleSubmit,
                resetForm,
                isSubmitting,
                }) => (
                    <View style={styles.form}>
                        <Animated.View
                            style={[styles.fieldset, addressStyle]}
                            onLayout={e => {
                                if (addressHeight !== e.nativeEvent.layout.y) {
                                    setAddressHeight(e.nativeEvent.layout.y)
                                }
                            }}
                        >
                            <Text style={{ marginLeft: 40, marginVertical: 5 }}>
                                <Text style={{ color: '#FF5D4E' }}>* </Text>
                                Address
                                </Text>
                            <View style={styles.autoComplete}>
                                <GooglePlacesInput
                                    onBlur={() => onBlurProps('address', setFieldTouched)}
                                    onChangeText={handleChange('address')}
                                    onFocus={onFocusProps}
                                />
                            </View>
                        </Animated.View>
                        {touched.address && errors.address &&
                            <Animated.Text style={{ fontSize: 10, color: 'red' }}>{errors.address}</Animated.Text>
                        }
                        <TouchableOpacity
                            disabled={!isValid || loading || isSubmitting}
                            onPress={handleSubmit}
                            style={styles.button}
                        >
                            <Text style={styles.buttonText}>Submit</Text>
                        </TouchableOpacity>
                    </View>
                )}
        </Formik>
    </View>
    )
}
```
Standard `GooglePlacesAutocomple` from the repository:
```js

<GooglePlacesAutocomplete
    placeholder='Search'
    minLength={2} // minimum length of text to search
    autoFocus={false}
    returnKeyType={'search'} // Can be left out for default return key https://facebook.github.io/react-native/docs/textinput.html#returnkeytype
    keyboardAppearance={'light'} // Can be left out for default keyboardAppearance https://facebook.github.io/react-native/docs/textinput.html#keyboardappearance
    listViewDisplayed={false}   // true/false/undefined
    fetchDetails={true}
    renderDescription={row => row.description} // custom description render
    onPress={(data, details = null) => { // 'details' is provided when fetchDetails = true
        console.log(data, details);
    }}
    textInputProps={ }}
    getDefaultValue={() => ''}

    query={{
        // available options: https://developers.google.com/places/web-service/autocomplete
        key: googleAPIKeyForAutocomplete,
        language: 'en', // language of the results
        region: "CA",
        // types: '(cities)' // default: 'geocode'
        types: '',
    }}

   
    currentLocation={true} // Will add a 'Current location' button at the top of the predefined places list
    currentLocationLabel="Current location"
    nearbyPlacesAPI='GooglePlacesSearch' // Which API to use: GoogleReverseGeocoding or GooglePlacesSearch
    GoogleReverseGeocodingQuery={{
        // available options for GoogleReverseGeocoding API : https://developers.google.com/maps/documentation/geocoding/intro
    }}
    GooglePlacesSearchQuery={{
        // available options for GooglePlacesSearch API : https://developers.google.com/places/web-service/search
        rankby: 'distance',
        type: 'food'
    }}

    GooglePlacesDetailsQuery={{
        // available options for GooglePlacesDetails API : https://developers.google.com/places/web-service/details
        fields: 'formatted_address',
    }}

    filterReverseGeocodingByTypes={['locality', 'administrative_area_level_3']} // filter the reverse geocoding results by types - ['locality', 'administrative_area_level_3'] if you want to display only cities
    predefinedPlaces={[]}
    enablePoweredByContainer={false}
    debounce={200} // debounce the requests in ms. Set to 0 to remove debounce. By default 0ms.
    renderLeftButton={() => { }}
    renderRightButton={() => { }}
/>
```

**Comment by amitbravo** [comment]
did you find any solution ?

**Comment by nonstuff** [comment]
yes i found the solution with nestedScrollEnabled={true} add to scrollview
you can see here
https://github.com/nonstuff/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js

**Comment by arsalan-arshad** [comment]
yes because of this module is using scroll view into flatlist.
so i found a solution to creating a new custom autocomplete list :D

**Comment by abhigk** [comment]
> yes because of this module is using scroll view into flatlist.
> so i found a solution to creating a new custom autocomplete list :D

How did you create it?

**Comment by plaporte** [comment]
> yes because of this module is using scroll view into flatlist.
> so i found a solution to creating a new custom autocomplete list :D

No idea what you mean by this. How can I fix the issue, do you have code examples?

**Comment by ansalmishra10** [comment]
still encountering this issue

**Comment by FabrizioCaldarelli** [comment]
@igibliss00 Have you tried to add keyboardShouldPersistTaps in all ancestor ScrollView?

```
<ScrollView keyboardShouldPersistTaps={'handled'}>
     <ScrollView keyboardShouldPersistTaps={'handled'}>
            <GooglePlacesAutocomplete ... >
```

**Comment by rpandey66** [comment]
> @igibliss00 Have you tried to add keyboardShouldPersistTaps in all ancestor ScrollView?
> 
> ```
> <ScrollView keyboardShouldPersistTaps={'handled'}>
>      <ScrollView keyboardShouldPersistTaps={'handled'}>
>             <GooglePlacesAutocomplete ... >
> ```

this works in my case

**Comment by bell-steven** [comment]
Closing, as this is now documented in the readme. Thanks @FabrizioCaldarelli!

**Comment by Hervera** [comment]
I still see the warning when I click the suggested places, and I have added ` keyboardShouldPersistTaps={'handled'}` to the `<ScrollView/> `

**Comment by tusharkhatiwada** [comment]
It's still not working on android. I too have added` keyboardShouldPersistTaps={'handled'}` on the parent `<ScrollView> `component.

**Comment by sytolk** [comment]
For me it works on Android with `keyboardShouldPersistTaps={'handled'}` but on ios onPress() is never called

**Comment by osamasaeed** [comment]
> @igibliss00 Have you tried to add keyboardShouldPersistTaps in all ancestor ScrollView?
> 
> ```
> <ScrollView keyboardShouldPersistTaps={'handled'}>
>      <ScrollView keyboardShouldPersistTaps={'handled'}>
>             <GooglePlacesAutocomplete ... >
> ```

Thanks, @FabrizioCaldarelli. I have wasted so many hours on this to find out the problem.

**Comment by muhammadballak1999** [comment]
guys i tried every thing in written in these comments none of them is working, im still not able to click suggestion

**Comment by muhammadballak1999** [comment]
> > @igibliss00 Have you tried to add keyboardShouldPersistTaps in all ancestor ScrollView?
> > ```
> > <ScrollView keyboardShouldPersistTaps={'handled'}>
> >      <ScrollView keyboardShouldPersistTaps={'handled'}>
> >             <GooglePlacesAutocomplete ... >
> > ```
> 
> this works in my case

it doesnt work

**Comment by KrisLau** [comment]
`keyboardShouldPersistTaps` not working for me

**Comment by KrisLau** [comment]
@bell-steven `keyboardShouldPersistTaps` not working for me. I'm still getting the same error.

**Comment by EmersonGomes21** [comment]
Para mim funionou adiionar a propriedade `keepResultsAfterBlur` para manter a lista aberta e poder selecionar

**Comment by Definence** [comment]
> @bell-steven `keyboardShouldPersistTaps` not working for me. I'm still getting the same error.

same issue

**Comment by Definence** [comment]
> @bell-steven `keyboardShouldPersistTaps` not working for me. I'm still getting the same error.

Same issue. Temporarily disable it by adding in Autocomplete reusable component:
`  useEffect(() => {
    const mockFunction = (error) => {
      if (error === 'VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.') return console.warn(error)
      if (console.originalError) console.originalError(error)
    }

    console.originalError = console.error
    console.error = mockFunction
    return () => { console.error = console.originalError }
  }, [])
`

**Comment by Jamsanz** [comment]
> @igibliss00 Have you tried to add keyboardShouldPersistTaps in all ancestor ScrollView?
> 
> ```
> <ScrollView keyboardShouldPersistTaps={'handled'}>
>      <ScrollView keyboardShouldPersistTaps={'handled'}>
>             <GooglePlacesAutocomplete ... >
> ```

I have tried every option available here and it's not working for me.

**Comment by muhammadballak1999** [comment]
> 



> > @igibliss00 Have you tried to add keyboardShouldPersistTaps in all ancestor ScrollView?
> > ```
> > <ScrollView keyboardShouldPersistTaps={'handled'}>
> >      <ScrollView keyboardShouldPersistTaps={'handled'}>
> >             <GooglePlacesAutocomplete ... >
> > ```
> 
> I have tried every option available here and it's not working for me.

Sir you have to also add keyboardShouldPersistTaps in all direct scrollview parent and non direct scrollview parents also in the other files if exist.

**Comment by Jamsanz** [comment]
> > 
> 
> > > @igibliss00 Have you tried to add keyboardShouldPersistTaps in all ancestor ScrollView?
> > > ```
> > > <ScrollView keyboardShouldPersistTaps={'handled'}>
> > >      <ScrollView keyboardShouldPersistTaps={'handled'}>
> > >             <GooglePlacesAutocomplete ... >
> > > ```
> > 
> > 
> > I have tried every option available here and it's not working for me.
> 
> Sir you have to also add keyboardShouldPersistTaps in all direct scrollview parent and non direct scrollview parents also in the other files if exist.

I just did and everything is still the same. Still showing the VisualizedList error

**Comment by cadecanh** [comment]
SAME. Not works for me. huhuhu

**Comment by malfoych** [comment]
@FabrizioCaldarelli Thanks man, It saved my day 👍🏼

**Comment by astears** [comment]
I have tried setting keyboardShouldPersistTaps={'handled'} for the ancestor KeyboardAwareScrollView's but it's unfortunately still not working for me.

Has anyone been able to figure it out?

**Comment by KrisLau** [comment]
My problem was fixed but I can't remember what fixed it anymore. If you have nested `KeyboardAwareScrollView` try `keyboardShouldPersistTaps={'always'}` for the parent one and `keyboardShouldPersistTaps={'handled'}` for all children ones

**Comment by KrisLau** [comment]
Lmao came back but my own solution doesn't even work for me anymore XD @bell-steven any other suggestions or workarounds?

**Comment by humayunkabir** [comment]
I tried suggested solutions, but It doesn't work. Any workaround?

**Comment by YasirNaeem25** [comment]
<ScrollView keyboardShouldPersistTaps={'handled'}>
     <ScrollView keyboardShouldPersistTaps={'handled'}>
            <GooglePlacesAutocomplete ... >
            
            not Working for me now

**Comment by yudha-dev** [comment]
<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ flexGrow: 1 }}>
  <GooglePlacesAutocomplete />
</ScrollView>

**Comment by yudha-dev** [comment]
> <ScrollView keyboardShouldPersistTaps={'handled'}> <ScrollView keyboardShouldPersistTaps={'handled'}> <GooglePlacesAutocomplete ... >
> 
> ```
>         not Working for me now
> ```

<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ flexGrow: 1 }}>
<GooglePlacesAutocomplete ... >
</ScrollView>

**Comment by YasirNaeemHw** [comment]
> > <ScrollView keyboardShouldPersistTaps={'handled'}> <ScrollView keyboardShouldPersistTaps={'handled'}> <GooglePlacesAutocomplete ... >
> > ```
> >         not Working for me now
> > ```
> 
> <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ flexGrow: 1 }}> <GooglePlacesAutocomplete ... >

My issue resolve after Place Sim Card in Testing Device

**Comment by LucasEsteves2** [comment]
I have the same problem, can someone help me? inside a modalize does not work

**Comment by zainsolat** [comment]
For anyone who is having problems with this, I disabled the scroll inside GooglePlacesAutocomplete
`<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ flexGrow: 1 }}>
    <GooglePlacesAutocomplete
      ref={ref}
      filterReverseGeocodingByTypes={['locality']}
      fetchDetails={true}
      debounce={500}
      placeholder='Search'
      disableScroll={true}`

As per this issue (which does a good job explaining the reason) https://github.com/facebook/react-native/issues/31697

When you do that, the ScrollView can do its job. Hope this helps anyone having issues with this in 2023!

**Comment by Lambertn33** [comment]
@zainsolat God bless you man!
you saved my day!

**Comment by raynox** [comment]
Adding keyboardShouldPersistTaps and disableScroll doesn't work in my case

**Comment by SomGSS** [comment]
@zainsolat Thanks, man. you saved my day!

**Comment by sahilkashyap64** [comment]
@zainsolat Thank you so much, your solution really helped 🤗

**Comment by virajbhosalebbi** [comment]
@zainsolat thank you thank you!

**Comment by gollodev** [comment]
I can't solve this issue, onPress not works!

**Comment by UDsGitHub** [comment]
@gollodev, did you end up figuring this out?

> I can't solve this issue, onPress not works!
