### ISSUE TITLE
version 1.4.0

### ISSUE THREAD

**Issue by gdedieu92** [FaridSafi/react-native-google-places-autocomplete#487]
there is a bug in line
The thing is that as soon as a user tap in list of results, the blur execute and hide the list, but you dont catch the onPress event sooo never search for address... So comment this line make the plugin works in version 1.4.0.

```
//Error:
_onBlur = () => {
    this.triggerBlur();
    this.setState({ listViewDisplayed: false });
  }

//Fine:
_onBlur = () => {
    this.triggerBlur();
  }
```

**Comment by sunwooz** [comment]
Same for me. The onpress function never gets called when selecting a listing.

Doesn't seem to work for me even after commenting out the line, though.
I'm on 1.4.0.

**Comment by malikgenius** [comment]
Same here, had to go back to 1.3.9 version ... and Please update Hooks for 0.60 React, that warning for componentWillReceiveProps has been renamed is bothering ... Thanks

**Comment by malikgenius** [comment]
Remove onBlur from original package file .... GooglePlacesAutocomplete.js

<TextInput
              ref="textInput"
              editable={this.props.editable}
              returnKeyType={this.props.returnKeyType}
              keyboardAppearance={this.props.keyboardAppearance}
              autoFocus={this.props.autoFocus}
              style={[this.props.suppressDefaultStyles ? {} : defaultStyles.textInput, this.props.styles.textInput]}
              value={this.state.text}
              placeholder={this.props.placeholder}
              onSubmitEditing={this.props.onSubmitEditing}
              placeholderTextColor={this.props.placeholderTextColor}
              onFocus={onFocus ? () => {this._onFocus(); onFocus()} : this._onFocus}
              // onBlur={this._onBlur}
              underlineColorAndroid={this.props.underlineColorAndroid}
              clearButtonMode={
                clearButtonMode ? clearButtonMode : "while-editing"
              }
              { ...userProps }
              onChangeText={this._handleChangeText}
            />

**Comment by sunwooz** [comment]
@malikgenius That doesn't seem to work for me. Still can't click on a result unless it overlaps the input field.

**Comment by glintpursuit** [comment]
@sunwooz did you found the solution ?

**Comment by sunwooz** [comment]
@glintpursuit Unfortunately, just had to roll my own autocomplete input.

**Comment by glintpursuit** [comment]
@sunwooz so you created your own version ? 

If I switch off onblur its working.

**Comment by bell-steven** [comment]
It isn't very clear to me what the issue is here. Please open a new issue (please follow the issue template) if you encounter this.
