### ISSUE TITLE
Unable to use in two different pages

### ISSUE THREAD

**Issue by fpolica91** [FaridSafi/react-native-google-places-autocomplete#488]
I am planning to use the autocomplete input in two pages, I do not need a map view, I simply need to provide the user with options upon typing. On my signup page, the google places autocomplete works fine, however if I include this in any other page, nothing appears upon typing. 

```
const GooglePlacesInput = (props) => {

    return (

        <GooglePlacesAutocomplete
            placeholder="Select hometown"
            query={{
                key=APIKEY,
                language: "en",
                types: '(cities)'
            }}
            onPress={data => props.selectTown(data)}
        />
    )
}
```

as I mentioned this works as expected on one file, with no issues. however when including it in any other page I get no results.

**Comment by conor909** [comment]
I'm also getting no results with no errors.  I'm typing text into the input but nothing is happening.

**Comment by bell-steven** [comment]
@fpolica91 or @conor909 
Can you please provide a reproducible example of this by showing more detailed code or better yet, linking to a [snack](https://snack.expo.io)?
