### ISSUE TITLE
Warning: componentWillMount has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by aymkin** [FaridSafi/react-native-google-places-autocomplete#490]
See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: GooglePlacesAutocomplete

**Comment by graham-pyett** [comment]
#442

**Comment by adtm** [comment]
#442 Should address, but it has been been there for 2 months sitting in place.

**Comment by bell-steven** [comment]
Closed with #500
