### ISSUE TITLE
autocomplete is not working but i'm getting the location names

### ISSUE THREAD

**Issue by mehdihussain9** [FaridSafi/react-native-google-places-autocomplete#491]
I'm getting the location names while typing in the search box. but when I clicked or selected one of the locations it not responding and also that clicked or selected location not displaying on the search bar (input field).

**Comment by lukBakTsh** [comment]
+1

**Comment by R1D3** [comment]
same issue .....

**Comment by ranggabadrus** [comment]
same issue. any update?

**Comment by Zainabalhaidary** [comment]
same issue

**Comment by TheWhiteUnicorn** [comment]
In my case it happened when I've put this component into another scroll view. Removing the outer scroll view temporary fixed the problem

**Comment by carlosbpf** [comment]
I was running into the same issue,  setting keyboardShouldPersistTaps='always'  on ALL scroll views you may have surrounding this component, and setting listViewDisplayed='false' did the trick for me!

**Comment by bell-steven** [comment]
I'm closing this as there is no reproducible example and it sounds like the scrollview issue many others are struggling with.  Try [this](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/491#issuecomment-591969185), as mentioned above.  Also see [this](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/478#issuecomment-573344080) issue for reference.
