### ISSUE TITLE
getCurrentPosition is not working, navigator is undefined

### ISSUE THREAD

**Issue by ivp1989** [FaridSafi/react-native-google-places-autocomplete#493]
**GooglePlacesAutocomplete.js:191**
`navigator.geolocation.getCurrentPosition(`

**Comment by prog-24** [comment]
You just need to update your geolocation reference

`yarn add @react-native-community/geolocation`

Then in your main App.js

`navigator.geolocation = require('@react-native-community/geolocation');`

Don't forget `pod install` for iOS

**Comment by Deboracgs** [comment]
> You just need to update your geolocation reference
> 
> `yarn add @react-native-community/geolocation`
> 
> Then in your main App.js
> 
> `navigator.geolocation = require('@react-native-community/geolocation');`
> 
> Don't forget `pod install` for iOS

This is works
