### ISSUE TITLE
Can not read property 'getCurrentPosition' of undefined

### ISSUE THREAD

**Issue by RonakPatel0** [FaridSafi/react-native-google-places-autocomplete#494]
When I press on Current location so i get this error 
![Screenshot_2020-01-20_122122](https://user-images.githubusercontent.com/57698251/72704745-a3032880-3b7f-11ea-8430-fdce9a8c4c62.jpg)

**Comment by chassierPA** [comment]
Hi @RonakPatel0 

I'm also getting this error, and I didn't find a way to make it work !
