### ISSUE TITLE
Update predefinedPlaces

### ISSUE THREAD

**Issue by safeer-ahmed** [FaridSafi/react-native-google-places-autocomplete#495]
Is there any way to update predefinedPlaces? I tried setting predfinedPlaces using state, but upon updating state, it's not updating list.

Code is:
`<GooglePlacesAutocomplete predefinedPlaces={this.state.savedList}
                            //other attributes 
                        />`

**Comment by bell-steven** [comment]
Thanks for the PR!

Closed with 31f98b4
