### ISSUE TITLE
Limit number of row rendered ? 

### ISSUE THREAD

**Issue by MayoudP** [FaridSafi/react-native-google-places-autocomplete#497]
By any chance, can I set a limit concerning the row rendering, for example to display only 3 row max ? 
I already succeed to filter the result a bit like that : 
```  
 renderRow(content) {
        const matching = path(["matched_substrings"], content);
        ...
}
  ```

and if the result doesn't have enough occurence with the textInputField, I'm not displaying it... But it's not limiting the number of row rendered...

Any ideas ?

**Comment by bell-steven** [comment]
There is nothing built in that can give you this. 
You could try and set the height of the component to only have enough space for 3 results.  
You can also try and setting a counter in render row and only render the first 3 results.
