### ISSUE TITLE
Clear text button not showing up in Device but simulator

### ISSUE THREAD

**Issue by amitbravo** [FaridSafi/react-native-google-places-autocomplete#498]
This is a screenshot from a simulator , I do not see this clear text/close list button in device (testing on iOS 13.3 iphone SE) but in simulator . How can I get it in device too ?
![Simulator Screen Shot - iPhone 11 - 2020-02-01 at 17 41 11](https://user-images.githubusercontent.com/16644357/73591937-c7191f00-451a-11ea-9f06-5ba2e0c34520.png)

**Comment by bell-steven** [comment]
The default for the `clearButtonMode` prop (which is only available for iOS), is set to `'while-editing'`. See the React Native [docs](https://reactnative.dev/docs/textinput#clearbuttonmode) for more.

You can override this in `textInputProps`.

I just tested this and it worked for me.  If you believe that this is a bug, please provide reproducible code example, or a snack, and i'll be happy to take a look.
