### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by avishayhajbi** [FaridSafi/react-native-google-places-autocomplete#50]
app crashes... 

view <RCTShadowView: 0x100637400; viewName: RCTTextField; reactTag: 1799; frame: {{8, 8}, {398, 28}}> (tag #1799) is not a descendant of <RCTShadowView: 0x1062935b0; viewName: RCTView; reactTag: 1695; frame: {{0, 0}, {394, 784.66666666666663}}> (tag #1695)

RCTMeasureLayout + 400
    RCTUIManager.m:1269
-[RCTUIManager measureLayout:relativeTo:errorCallback:callback:] + 292
<redacted> + 144
<redacted> + 284
<redacted> + 60
-[RCTModuleMethod invokeWithBridge:module:arguments:] + 1684
-[RCTBatchedBridge _handleRequestNumber:moduleID:methodID:params:] + 712
__33-[RCTBatchedBridge handleBuffer:]_block_invoke.452 + 1144
_dispatch_call_block_and_release + 24
_dispatch_client_callout + 16
_dispatch_queue_drain + 1036
_dispatch_queue_invoke + 464
_dispatch_root_queue_drain + 760
_dispatch_worker_thread3 + 132
_pthread_wqthread + 1092
start_wqthread + 4

**Comment by myaskevich** [comment]
Hi @avishayhajbi 

I'm losing it for now, since the obj-c callstack doesn't sound like a very informative issue description, honestly.

Feel free to reopen if the issue reoccurs, but next time with more info please ;)
