### ISSUE TITLE
PlacesDetailsQuery don't work with multiple fields

### ISSUE THREAD

**Issue by anunes9** [FaridSafi/react-native-google-places-autocomplete#507]
When passing multiple fields to the Details Query the component fails to the a response.

`GooglePlacesDetailsQuery={{ fields: 'formatted_address, geometry' }}`

Any clue on how to request multiple fields?

**Comment by lam3rr** [comment]
just remove the space between the comma and geometry.
it worked for my case 
GooglePlacesDetailsQuery={{ fields: 'formatted_address,geometry' }}
