### ISSUE TITLE
react-native-google-places-autocomplete not working on React native 0.59.9

### ISSUE THREAD

**Issue by aniruddhbhamare** [FaridSafi/react-native-google-places-autocomplete#513]
"react-native-google-places-autocomplete": "^1.4.1",
"react-native": "0.59.9",
 "react": "16.8.3",

Autocomplete does not work,
Not Showing Result lIst

**Comment by jaing** [comment]
Was not working for me either. So i created one by myself:

https://github.com/jaing/react-native-places-input

**Comment by bell-steven** [comment]
@aniruddhbhamare Can you please provide a fully reproducible example of this by showing some code or better yet, linking to a [snack](https://snack.expo.io)?
