### ISSUE TITLE
possibility to get flatlist current height

### ISSUE THREAD

**Issue by Lukashev** [FaridSafi/react-native-google-places-autocomplete#515]
I think flatlist need some stuff to get height, etc. based on quantity of rendering rows or do this with ref maybe. For example, it's usefull if you don't wanna leave the free space in a block and change container element height (modal, etc.) according to flatlist. Maybe, I don't understand something.

**Comment by bell-steven** [comment]
Hi, i'm having a little bit of trouble trying to understand your issue. What are you trying to achieve? Can you provide some sort of code example to illustrate your issue a bit more?

**Comment by bell-steven** [comment]
This doesn't seem to be active. Please open a new issue (please follow the issue template) if this is an issue for you.
