### ISSUE TITLE
Can't select a item inside of ScrollView

### ISSUE THREAD

**Issue by VTSingle** [FaridSafi/react-native-google-places-autocomplete#517]
I can't select a item inside of ScrollView. Sorry for the repetition question, but I can't find solutions for it.
My versions: 
React-Native: "0.61.5",
React-native-google-places-autocomplete: "^1.4.1".

Example of me code: 

`<ScrollView`
      `style={styles.styleContainer}`
     ` keyboardShouldPersistTaps="handled">`
     `   <GooglePlacesAutocomplete`
          `placeholder="Your address"`
          `minLength={1}`
         ` autoFocus={false}`
          `returnKeyType={'default'}`
          `keyboardAppearance={'light'}`
          `listViewDisplayed={false}`
          `fetchDetails={true}`
          `renderDescription={row => row.description}`
          `onPress={(data: any, details = null) => {`
           ` onChangeAddress(data.description);`
          `}}`
          `query={{`
            `key: '***********',`
          `}}`
          `currentLocation={false}`
          `debounce={200}`
        `/>`
`</ScrollView>`

**Comment by faisal-vf** [comment]
This helped: https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/478#issuecomment-573344080

**Comment by nikolajordanovski** [comment]
@VTSingle 
Please add `keyboardShouldPersistTaps="handled"` to your ScrollView component

**Comment by juanlet** [comment]
@nikolajordanovski That worked for me, thanks!

**Comment by nikitph** [comment]
this worked for me too . thanks

**Comment by toplongguodev** [comment]
@nikolajordanovski Thanks, it is wonderful solution.

**Comment by st3rbenn** [comment]
@nikolajordanovski wonderful thanks !

**Comment by manzoorsofi** [comment]
Hello Guys
why aren't the gogle places option of GooglePlacesAutocomplete clickable here
`
import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';
import { ScrollView } from 'react-native-gesture-handler';
const AddLocationPopup = ({ visible, onClose, onSubmit }) => {
  const [formData, setFormData] = useState({
    address: '',
  });
  const handleInputChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };
  return (
    <Modal visible={visible} transparent animationType="slide">
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={styles.modalBackground}
      >
        <View style={styles.modalContainer}>
          <View style={styles.header}>
            <Text style={styles.headerText}>Add Location</Text>
            <CrossIcon onPress={onClose} />
          </View>
          <View style={styles.googlePlacesContainer}>
          <ScrollView>
            <GooglePlacesAutocomplete
              placeholder="Search for an address"
              onPress={(data, details = null) => {
                console.log('Selected Place:', data, details);
                handleInputChange('address', data?.description || '');
              }}
              query={{
                key: 'Maps_Key',
                language: 'en',
                types: 'geocode',
              }}
              fetchDetails={true}
              styles={{
                container: styles.autocompleteContainer,
                textInput: styles.textInput,
                listView: styles.listView,
                row: styles.listRow,
              }}
            />
            </ScrollView>
          </View>
        </View>
      </KeyboardAvoidingView>
    </Modal>
`
