### ISSUE TITLE
How to get it to search for addresses?

### ISSUE THREAD

**Issue by ivankhau** [FaridSafi/react-native-google-places-autocomplete#52]
Seems like it can only retrieve Cities

**Comment by kristina-grujic** [comment]
You have 'types' prop in 'query', where you define by what place type will the search be done. To search by address, you can specify types to 'address'.  For more, see https://developers.google.com/places/web-service/autocomplete
Everything I wrote is already specified in documentation, tho.

**Comment by ivankhau** [comment]
I should've been more clear, I tried changing it to address and it still wasn't working for me. Only cities, I even tried removing the filters and no dice.

**Comment by mjsisley** [comment]
@ivankhau Did you ever figure this out? I am having the same problem.

**Comment by mjsisley** [comment]
Nevermind, #41 covers it. Use 'address' instead of '(address)'

**Comment by ivankhau** [comment]
@kristina-grujic @mjsisley Tried it again and it works great. Must of been user error or bad internet connection earlier.
