### ISSUE TITLE
Postcodes is not given unless input detects a postcode 

### ISSUE THREAD

**Issue by jacky-ew** [FaridSafi/react-native-google-places-autocomplete#520]
is there a way to display postcode in every address even user did not key in the postcodes?

**Comment by bell-steven** [comment]
This is not currently possible, as the [API](https://developers.google.com/places/web-service/autocomplete) we are using does not return this information. You can get the postal code when you press on a result.

This may be added in a future version though.

**Comment by ashokkumar-hub** [comment]
https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/835#issuecomment-1438041017
