### ISSUE TITLE
Can the input component takes in new state instead of default "this.state.text"

### ISSUE THREAD

**Issue by jacky-ew** [FaridSafi/react-native-google-places-autocomplete#524]
Hi, i was trying to pre-fill the input with some text so that `onFocus` of input, the dropdown list will show available results based on pre-filled data.
however after checking your source code, i found out it was hard coded with `this.state.text`, is there any other props that i can overwrite it, rather than i change your source code?

thanks in advance

**Comment by NeenaMishra12** [comment]
Hi @jacky-ew ,
Have you got any solution for this?
I am also looking for the same but, couldn't find any solution.

**Comment by bell-steven** [comment]
Have you tried the `getDefaultvalue` prop? 
```
<GooglePlacesAutocomplete
    query={{
         key: GOOGLE_PLACES_API_KEY,
         language: 'en',
     }}
     getDefaultValue={() => '123 Main St New York, NY 111234'}
/>
```

**Comment by NeenaMishra12** [comment]
> Have you tried the `getDefaultvalue` prop?
> 
> ```
> <GooglePlacesAutocomplete
>     query={{
>          key: GOOGLE_PLACES_API_KEY,
>          language: 'en',
>      }}
>      getDefaultValue={() => '123 Main St New York, NY 111234'}
> />
> ```

I am trying to set it from state but, in that case it is not showing anything although state has value.
>      getDefaultValue={() => this.state.city} //Using state it is not working
>      getDefaultValue={() => city} //Using const it is not working
>      getDefaultValue={() =>'Mumbai'} // it worked

**Comment by bell-steven** [comment]
Can you please provide a reproducible example?  A [snack](https://snack.expo.io) would be great.

**Comment by bell-steven** [comment]
I am closing this, as there hasn't been any response. 

> however after checking your source code, i found out it was hard coded with this.state.text, is there any other props that i can overwrite it, rather than i change your source code?

`the.state.text` gets the result of the `getDefaultValue` prop.  You can also set it using a ref (setAddressText).
