### ISSUE TITLE
On Search - TypeError: undefined is not an object (evaluating '_headers[h].toString')

### ISSUE THREAD

**Issue by durgesh94** [FaridSafi/react-native-google-places-autocomplete#528]
Please ref screenshot for more details.
"react-native": "0.61.5"
"react-native-google-places-autocomplete": "^1.4.1"

![Issue](https://user-images.githubusercontent.com/21127111/78970294-9ced6a00-7b26-11ea-915a-fb2ecec90bd2.png)

**Comment by bell-steven** [comment]
@durgesh94 Can you please provide a fully reproducible example of this by showing some code or better yet, linking to a [snack](https://snack.expo.io)?
