### ISSUE TITLE
Text Search is  not working

### ISSUE THREAD

**Issue by SyedTaha13** [FaridSafi/react-native-google-places-autocomplete#529]
I am trying to get multiple result from an ambiguous text search like food or grocery store by using GooglePlaceSearch but in suggestion i am not getting the search query , Here is the code snippet

query={{
                    key: 'my_api_key',
                    language: 'en',
                    location: this.props.lat+','+this.props.lng,        //specifing the current loc
                    radius:30000,        //search within 0km of your current loc
                    // origin:this.props.lat+','+this.props.lng,
                }}
              
                GooglePlacesSearchQuery={{
                    key: 'my_api_key',
                    location: this.props.lat+','+this.props.lng,        //specifing the current loc
                    radius:30000,        //search within 30km of your current loc
                    
                }}

**Comment by juanlet** [comment]
Did you get to make the radius work with the current location? To me it doesn't complain but it doesn't restrict it to the radius, it shows cities that are at 1000km from the end of the radius

**Comment by bell-steven** [comment]
@SyedTaha13 Can you please provide a full reproducible example of this by showing some code or better yet, linking to a [snack](https://snack.expo.io)?
