### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by FaridSafi** [FaridSafi/react-native-google-places-autocomplete#532]
Hello guys, I am looking for maintainers for this package. Is someone interested ?

**Comment by MuhweziDeo** [comment]
@FaridSafi Intreseted

**Comment by julien9999** [comment]
Hey Farid, would love to help maintain

**Comment by y-manish** [comment]
Hi @FaridSafi 
I am interested but don't have much experience in react-native as of now.

I recently came across this package, its quite helpful for the react-native app I have started building recently.

Also I would like request adding inbuilt support for sessionToken to reduce the cost for autocompletion https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/534 
If this looks good, I can start working on this.

**Comment by FaridSafi** [comment]
alright, I sent you an invitation via GitHub. What is your https://www.npmjs.com/ username?

**Comment by y-manish** [comment]
> alright, thank you! I sent you an invitation via GitHub. What is your https://www.npmjs.com/ username?

Its manishy

**Comment by FaridSafi** [comment]
Thank you @y-manish, I added you as collaborator on this repo and also on npmjs. You are now able publish updates

**Comment by bell-steven** [comment]
I would love to work with @y-manish and whoever else is working on the library.  

I have have been working on react-native full time for over a year and been using this library from the beginning.  Was doing React on the web before that for a couple of years. 

I would like to help out with critical bug fixes and issue management first (there are over 100 open issues and 30 open PR's).

I can also help with refactoring the code to use some of the newer react/react-native features.

My NPM username is `sbell`.

Thank you @FaridSafi for creating the library and seeing it through until now.

**Comment by iqbal-muhammad** [comment]
I am interested for maintaining this awesome package, I always wanted to do something like this and it would be a nice challenge for me.
