### ISSUE TITLE
Does not take any action on onPress inside Flatlist

### ISSUE THREAD

**Issue by NeelakshSharma** [FaridSafi/react-native-google-places-autocomplete#535]
I am generating Google places textfields inside flatlist dynamically. But this stops the onPress function to work(after selecting any place from suggestions does not give any feedback).

**Comment by klichg0ky** [comment]
> I am generating Google places textfields inside flatlist dynamically. But this stops the onPress function to work(after selecting any place from suggestions does not give any feedback).

Its react native problems, check FlatList extraData props

**Comment by anoopnockson** [comment]
for me when placing it on normal view not scroll view working. but extra space showing..

**Comment by NeelakshSharma** [comment]
How can I use it inside Scroll List or Flat List?

**Comment by ferranuap** [comment]
Any workaround for this?

**Comment by NeelakshSharma** [comment]
Yea, I just put the textfields instead of google autocomplete textfield. When the user taps on any of them. it redirects to another screen which has the Google autocomplete textfield. When th user inputs a place, it redirects back to the multple textfield screen. It's completely a workaround but not a solution to it.

**Comment by ferranuap** [comment]
> Yea, I just put the textfields instead of google autocomplete textfield. When the user taps on any of them. it redirects to another screen which has the Google autocomplete textfield. When th user inputs a place, it redirects back to the multple textfield screen. It's completely a workaround but not a solution to it.

I ended up doing the same. I've removed the popup i had and created a new screen. Thanks for answering :)

**Comment by nikitph** [comment]
this should not be closed. this is a problem for me too

**Comment by bell-steven** [comment]
@nikitph I can re-open this if you have some reproducible code to show what the issue is.

**Comment by nikitph** [comment]
I found a workaround. Keyboardshouldpersisttaps= true inside scrollview
containing the Google place text field. It only happens when field is
nested in a scrollview

**Comment by klokie** [comment]
thanks @nikitph - that led me to https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/486#issuecomment-665602257

**Comment by Imtayaz** [comment]
I guess you need this library as well 
npm install react-native-virtualized-view --save
