### ISSUE TITLE
Not getting Address Components from Data

### ISSUE THREAD

**Issue by ankitnb** [FaridSafi/react-native-google-places-autocomplete#536]
I am having an issue with the library, on a method of its **"onPress={(data, details = null) => "**, I was getting address_components using **"details.address_components"**.

But now I am not getting the address component data, what would be the issue? I'm getting only formatted address in details.

**{"formatted_address":"city, state, country"}**

I'm using following version,
**"react-native-google-places-autocomplete": "^1.4.1"**

**Comment by rmethaniya** [comment]
You will get **postal code, country, state, city** and other with using below function. 

    export let placeAddresCompoponent = {
        ZIP_CODE: 'postal_code',
        COUNTRY: 'country',
        STATE: 'administrative_area_level_1',
        CITY: 'administrative_area_level_2',
        TOWN: 'sublocality_level_1',
        AREA: 'sublocality_level_2',
        NEAREST_ROAD: 'route'
    }

Use the below function for getting data from the address component. You will get **address_components** from the result of **Google Place Api**.

    export function getAddressComponent(address_components, key) {
        var value='';
        var postalCodeType = address_components.filter(aComp =>
            aComp.types.some(typesItem => typesItem === key))
        if (postalCodeType != null && postalCodeType.length > 0)
            value = postalCodeType[0].long_name
        return value;
    }

You can get the specific address component using below.

  **addressComponent** = Array of **address_components** from google place api result

    var zipCode = getAddressComponent(addressComponent, placeAddresCompoponent.ZIP_CODE)
    var country = getAddressComponent(addressComponent, placeAddresCompoponent.COUNTRY)
    console.log('zipCode : ', zipCode)
    console.log('country : ', country)

**Comment by bell-steven** [comment]
@ankitnb can you provide a reproducible example of this by showing some code or better yet, lining to a [snack](https://snack.expo.io)?

**Comment by Rc85** [comment]
Using just the `GooglePlacesDetailsQuery` did not return `address_component`. Have to also include the `fetchDetails` prop.
