### ISSUE TITLE
Problem when adding onSubmitEditing

### ISSUE THREAD

**Issue by tankpower1** [FaridSafi/react-native-google-places-autocomplete#537]
Hello, i can't seem to get the onSubmitEditing to work at all. I add it as follows:

<pre>
textInputProps={{
                        onSubmitEditing: (data, details) => console.log(data, details),
                        returnKeyType: 'go',
                        clearButtonMode: 'never'
                    }}
</pre>

It gets the synthetic event data instead of data/details..

**Comment by bell-steven** [comment]
@tankpower1 Can you please provide a full reproducible example of this by showing some code or better yet, linking to a [snack](https://snack.expo.io)?
