### ISSUE TITLE
Expose functions like onFail, onNotFound

### ISSUE THREAD

**Issue by nikolajordanovski** [FaridSafi/react-native-google-places-autocomplete#538]
Hello, would be of great benefit to expose the functions
`onFail` and `onNotFound` as it's an edge case that needs to be handled.

We can see the functions and there are few pull requests as far as I can see. 

Please let us know why its not exposed , I can create a PR if needed be.

**Comment by nikolajordanovski** [comment]
@FaridSafi could you please provide feedback or give us the green light to code it

**Comment by bell-steven** [comment]
@nikolajordanovski  what do you mean by exposing the functions?
I use onFail in [this snack](https://snack.expo.io/@sbell/5e85ed) with no problems.  

PRs always welcome

**Comment by nikolajordanovski** [comment]
@bell-steven Thank you for the feedback, will look into it, tho based on the code I believe the onFail is never triggered
