### ISSUE TITLE
Geolocation umbrella issue

### ISSUE THREAD

**Issue by bell-steven** [FaridSafi/react-native-google-places-autocomplete#541]
Since `navigator.geolocation` was [deprecated in React Native v0.60.0](https://reactnative.dev/docs/geolocation.html), getting a user's current location no longer works.  There are many open (and closed) issues for this, and a few PRs open as well. 

I would like to hear about what you all think about the best path forward for this is.

On a high level, I think there are 2 ways to deal with this.
1) Create a current location prop, similar to predefinedPlaces, where you pass in a lat/long and we use that to set the current location. 
2) Replace `navigator.geolocation` with another library directly, either with the [React Native Community](https://github.com/react-native-community/react-native-geolocation) one, or [this](https://github.com/Agontuk/react-native-geolocation-service) one. 

Whatever we end up doing, it will be a breaking change. 

I personally don't like the idea of going with number 2 for a number of reasons:
- It means adding a location library as a dependency for a feature which is not used by all.
- Right now there is no native code in the library, so therefore there is no need for React Native Linking (or auto-linking).  There are many benefits to not having native code, including not having to rebuild the project when installing or updating the library, potential compatibility on the web, being able to run examples in Expo snack and making the library more friendly towards beginners.
- Using location on iOS requires adding a field to your plist file (otherwise your app will be rejected), and I believe that it would be required even when not actually using the feature, which has privacy implications. 

Related PR's:
#437 #466 #483 #531 

Related Issues:
#365 #447 #456 #473 #493 #494

**Comment by bell-steven** [comment]
For those looking for a quick workaround in the interim:

1) `yarn add @react-native-community/geolocation` or `npm install @react-native-community/geolocation --save`
2) React Native Link or Pod install
3) add `navigator.geolocation = require('@react-native-community/geolocation');` near the top of your App.js file.

**Comment by gypsicoder** [comment]
@bell-steven  It would be better if we had the needed codes in the example project. Because in the example project the currentLocation is given but there is no hint of what you said here.

**Comment by bell-steven** [comment]
@gypsicoder The example folder is very out of date.  Feel free to put in a PR with updates.

**Comment by gypsicoder** [comment]
@bell-steven I wish I could do that some day. Thank you for the quick reply.
