### ISSUE TITLE
I can't see places when i find

### ISSUE THREAD

**Issue by bfraiman** [FaridSafi/react-native-google-places-autocomplete#544]
I don't know if I have bad configurations on maps or I don't know.
I can see the saved places but when I want to search a new one I can't.

**Comment by bell-steven** [comment]
@bfraiman Can you provide some code or a [snack](https://snack.expo.io)?

**Comment by bfraiman** [comment]
I dont know if its an api configuration, because I can see that my usages are 178. Maybe you can describe me how to create the key and give the right permissions?

**Comment by bfraiman** [comment]
i try with a new project and I have the same error.

**Comment by bell-steven** [comment]
Why does your component look like. It is very difficult t know what the issue is without seeing some code.

**Comment by bfraiman** [comment]
I only copy the example, remove renderLeftButton prop and add my key at the query prop:

query={{
        key: 'YOUR API KEY', 
        language: 'en', // language of the results
        types: '(cities)', // default: 'geocode'
      }}

But it doesn’t work. I cant send you my key because it’s private but if you want we can do a call or something like it. I really think that my problem is with the configuration of the api, but I can’t resolve it with the explanation on the readme

**Comment by bfraiman** [comment]
<img width="1262" alt="Screen Shot 2020-05-10 at 9 13 22 PM" src="https://user-images.githubusercontent.com/31390603/81514059-416bf300-9303-11ea-8238-a0b0d1bcb2f1.png">

**Comment by bfraiman** [comment]
As you can see I have 188 usage in last 30 days. But I cant see the places when I search

**Comment by bell-steven** [comment]
I will use my own key.  Can you provide a code sample that show your usage of the `<GooglePlacesAutocomplete />` component?  Something like this:

```
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';
import {GooglePlacesAutocomplete} from 'react-native-google-places-autocomplete';

const GOOGLE_PLACES_API_KEY = 'YOUR_API_KEY'; // never save your real api key in a snack!

const App = () => (
  <View style={styles.container}>
    <GooglePlacesAutocomplete
      query={{
        key: GOOGLE_PLACES_API_KEY,
        language: 'en', // language of the results
      }}
      onPress={(data, details = null) => console.log(data)}
      onFail={error => alert(error)}
    />
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

export default App;
```

Or create a snack like [this](https://snack.expo.io/@sbell/react-native-google-places-autocomplete).

**Comment by bfraiman** [comment]
Thank you for the example. When I try with my key I recive this error
<img width="330" alt="Screen Shot 2020-05-10 at 9 29 50 PM" src="https://user-images.githubusercontent.com/31390603/81514430-78430880-9305-11ea-90e0-558c0a49fb79.png">

**Comment by bell-steven** [comment]
Are you following [this google guide](https://developers.google.com/places/web-service/get-api-key) for getting an api key?

**Comment by bfraiman** [comment]
Yes, I follow this steps. 
I have the same errors 

<img width="329" alt="Screen Shot 2020-05-10 at 9 57 50 PM" src="https://user-images.githubusercontent.com/31390603/81515222-619eb080-9309-11ea-82b0-45004d35ceb5.png">
<img width="330" alt="Screen Shot 2020-05-10 at 9 29 50 PM" src="https://user-images.githubusercontent.com/31390603/81515223-62cfdd80-9309-11ea-8cf0-5bc0a16d7bc1.png">

**Comment by bfraiman** [comment]
Maybe if we can do a 5 minutes call I can show you

**Comment by bell-steven** [comment]
This is an open source project. I help maintain this project, but I don't provide private 1 on 1 support.  As an open source project, there is no SLA, product support etc..  If you are willing to create a snack showing how you use the library code, it would be my pleasure to help you try and figure out what is going on.  
The Github issues are for issues with the library.  I asked you multiple times for a code reproduction, so I can try and help.

**Comment by bfraiman** [comment]
I figured out my issue! I forgot to enable the service, Here I share the URL console.developers.google.com/apis/library


If its posible to add it for future users it will be amaizing. Thank you for your answer

**Comment by bell-steven** [comment]
Feel free to put in a PR.  Glad you got it all figured out.
