### ISSUE TITLE
How can I show some value pre-filled in text input?

### ISSUE THREAD

**Issue by NeenaMishra12** [FaridSafi/react-native-google-places-autocomplete#548]
I am using it in my user profile screen where we ask user to select city from google-places-autocomplete. Once user updates profile and come back to profile screen I would like to show this field with city they have selected earlier. How can I achieve that and using which prop?

**Comment by bell-steven** [comment]
You can use the `getDefaultValue` prop.

```
<GooglePlacesAutocomplete
        query={{
          key: GOOGLE_PLACES_API_KEY,
          language: 'en', // language of the results
        }}
        getDefaultValue={() => '123 Main St New York, NY 111234'}
      />
```

You can also use a ref and set it with setAddressText. 

[Here](https://snack.expo.io/@sbell/react-native-google-places-autocomplete---ref) is an example using a ref.  

If you pass `null` or `undefined` to getDefaultValue you will get an error.

**Comment by gruckion** [comment]
This props has been deleted and is no longer available. `getDefaultValue`
