### ISSUE TITLE
Hi,How can I only show results in a certain country?

### ISSUE THREAD

**Issue by yoilerlp** [FaridSafi/react-native-google-places-autocomplete#551]
### I need that the result of the buquedad only be of a determining country

  I'm using it like this but it doesn't work for me
 `
query={{
      key: '',
      language: 'es',
      types: 'establishment',
      locationbias: {
        lat:4.570868,
        lng:-74.2973328,
      }
    }}
`

some other way to do it?

Thank you

_edited to remove api key_

**Comment by bell-steven** [comment]
Please follow the issue template.

There are multiple issues that answer this ([here](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/509#issuecomment-598714550), [here](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/481#issuecomment-582316741)).
