### ISSUE TITLE
Missing prop predefinedPlacesAlwaysVisible

### ISSUE THREAD

**Issue by Gabrielfcs** [FaridSafi/react-native-google-places-autocomplete#554]
I'm using the `predefinedPlacesAlwaysVisible` support in my project, but upgrading from v1.4.1 to 1.6.0 I received an error saying that the above prop is missing and I believe it was forgotten to add it to the types file, right?

I believe that the correct place to put this type is below the following line:
https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/645ec590e1dd3c6e5da8568b2f566e91970993bc/GooglePlacesAutocomplete.d.ts#L359

**Comment by Gabrielfcs** [comment]
I'm closing this issue because it was added in PR #555

**Comment by bell-steven** [comment]
Just re-opening this until a fix is merged in.
