### ISSUE TITLE
textInputProps Typescript bug

### ISSUE THREAD

**Issue by jamesa3** [FaridSafi/react-native-google-places-autocomplete#559]
#### Describe the bug

textInputProps causes "No overload matches this call" with TS.

#### To Reproduce

Use Typescript and add textInputProps

![Screen Shot 2020-05-19 at 15 09 22](https://user-images.githubusercontent.com/31718549/82287162-e614c180-99e2-11ea-8b1c-65d053445a47.png)

**Comment by bell-steven** [comment]
PR was reverted. See [#560(comment)](https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/560#issuecomment-630942327).
