### ISSUE TITLE
List of places keeps popping up when trying to type on a different textInput

### ISSUE THREAD

**Issue by fbotalla** [FaridSafi/react-native-google-places-autocomplete#567]
```
const GoogleAutocomplete = (props) =>{
    return(
    <GooglePlacesAutocomplete
            placeholder={props.placeholder} 
            minLength={2}
            value = {props.value}
            keyboardAppearance={'light'}
            autoFocus = {false}
            fetchDetails={true} 
            onPress = {props.onPress}
            query={{
                key: 'myKey',
                language: 'en', // language of the results
                }}
            styles={{
                textInputContainer: {
                    backgroundColor: 'rgba(0,0,0,0)', 
                    borderTopWidth: 0,
                    borderBottomWidth:0,
                    paddingLeft: 50,
                    paddingRight: 50,
                    },
                loader:{
                    height:100,
                },
                textInput: {
                    fontSize: 16,
                    fontFamily:'Bellota-Regular'
                    },
                }}/>
    )
}

export default GoogleAutocomplete;
````

Above is my component. Each time I click on different `<TextInput>` and I start to type, the drop-down with all the places that I found previously opens up. How do I disable this behavior?

**Comment by bell-steven** [comment]
Please follow the issue template.  If the information in the template is provided, I can try and help you out.

**Comment by fbotalla** [comment]
@bell-steven Thank you for redirecting me to the documentation. Would this only work with a class component? What if I wanted to only use this as a functional component?

**Comment by bell-steven** [comment]
It doesn't matter what type of component you use, class or functional.  What version of the library are you using?

**Comment by fbotalla** [comment]
I am using  "react-native-google-places-autocomplete": "^1.7.1"

**Comment by bell-steven** [comment]
Can you provide a minimal code reproduction either here or in a [snack](https://snack.expo.io)?

**Comment by fbotalla** [comment]
@bell-steven Never mind, I ran an npm update on the project and it works great now!

**Comment by bell-steven** [comment]
No worries. Glad you got it sorted out.
