### ISSUE TITLE
How to get same auto complete feature to my desired input

### ISSUE THREAD

**Issue by mvnpgh** [FaridSafi/react-native-google-places-autocomplete#57]
@FaridSafi 
I would like to achieve same feature in my navigator page.How we can get this.
Now for me auto complete feature is working fine but it takes 1 min time initially.how to reduce the time.
Thanks

**Comment by myaskevich** [comment]
Hi @mvnpgh 

Can you send a screenshot describing your issue please?

**Comment by mvnpgh** [comment]
i
![screenshot_2016-10-04-15-21-57_com cm](https://cloud.githubusercontent.com/assets/20180149/19069930/a8076abe-8a46-11e6-9ddf-5a617a685ce3.png)
want to get same auto complete feature to the screen shot inputfield

**Comment by myaskevich** [comment]
Hi
Sorry, I may seem stupid to you, but don't quite get where your autocomplete problem is.
Can you be more precise please?

Sincerely,
Maxim Yaskevich




On Tue, Oct 4, 2016 at 12:54 PM +0300, "mvnpgh" <notifications@github.com> wrote:












i



want to get same auto complete feature to the screen shot inputfield

**Comment by myaskevich** [comment]
@mvnpgh Instead of your InputText just put `<GooglePlacesAutocomplete>` component with all required properties.

**Comment by mvnpgh** [comment]
Thx
