### ISSUE TITLE
Android vs iOS erasing system

### ISSUE THREAD

**Issue by fbotalla** [FaridSafi/react-native-google-places-autocomplete#570]
I noticed that in iOS when I type a place I get a little 'x' at the very end of the textarea. When I click on that x, the entire content is erase. When I try to do the same on Android and I do not have the 'x' at the end of the textarea. Therefore, in order for me to erase the content I have to either select all or delete one char at a time. 

Is this a feature that can be implemented on Android also?

**Comment by bell-steven** [comment]
The `clearButtonMode` prop is only available for iOS. See the React Native [docs](https://reactnative.dev/docs/textinput#clearbuttonmode) for more.

You can pass in a custom TextInput component to `textInputProps`.
You can also use the `renderRightButton` prop.
