### ISSUE TITLE
How to populate list when I am using custom TextInput using InputComp inside textInputProps

### ISSUE THREAD

**Issue by Sandipnag** [FaridSafi/react-native-google-places-autocomplete#571]
# Problem

React Native Version: - 0.62.2
react-native-google-places-autocomplete Version: - ^1.7.1
I want to use csutom TextInput Component, so I have used InputComp inside  textInputProps. But when i am using this place list is not populating anymore.

If I am doing something wrong , a little help is needed.
Thanks in advance
#Code -
Here  is my sample code:-
```
<GooglePlacesAutocomplete
    placeholder="Type your location..."
    minLength={1}
    // ref={(instance) => { this.GooglePlacesRef = instance }}
    autoFocus={false}
    returnKeyType={'search'}
    keyboardAppearance={'light'}
    listViewDisplayed={'auto'}
    fetchDetails={true}
    textInputHide={false}
    textInputProps={{
        InputComp: class CustomTextInput extends React.Component {
            constructor(props) {
                super(props);
                this.state = {
                    placeText: ''
                }
            }
            render() {
                return <TextInput
                    placeholder={'Type your location...'}
                    style={{
                        backgroundColor: '#fff',
                        flex: 1,
                        borderRadius: 10,
                        marginVertical: 10,
                        marginHorizontal: 5,
                        justifyContent: 'center'
                    }}
                    value={this.state.placeText}
                    onChangeText={(placeText) => {
                        this.setState({ placeText })
                    }}
                />
            }

        },
        onChangeText: async text => {
            if (text.length === 0) {
                await this.MyCurrentLocation();
                //this.getAllLocationData();
            }
        }
    }}
    renderDescription={row => row.description}

    getDefaultValue={() => ''}
    query={{}}
    disableScroll={false}
    isRowScrollable={true}
    keyboardShouldPersistTaps={'always'}
    enablePoweredByContainer={false}
    styles={{
        textInputContainer: {
            backgroundColor: '#060531',
            height: screenHeight * .1,
            justifyContent: 'center',
            borderColor: '#060531',
        },
        container: {
            position: 'absolute',
            width: screenwidth,
            zIndex: 999,
            justifyContent: 'center',
            backgroundColor: '#060531',
        },
    }}
/>
```
Steps to reproduce the behavior - a minimal reproducible code example, link to a [snack](https://snakc.expo.io) or a repository.

**Comment by bell-steven** [comment]
- your code is not a fully reproducible example.  
- What are you trying to solve here?  If you are looking to style the component differently, there is no need for a custom component. You can style the textInput with in styles. 

Here as an example of the styling you applied in the style prop.  I also removed a bunch of redundant props. 
```js
      <GooglePlacesAutocomplete
        placeholder="Type your location..."
        minLength={1}
        // ref={(instance) => { this.GooglePlacesRef = instance }}
        keyboardAppearance={"light"}
        fetchDetails={true}
        textInputProps={
          {
            // onChangeText: async (text) => {
            //   if (text.length === 0) {
            //     await this.MyCurrentLocation();
            //     //this.getAllLocationData();
            //   }
            // },
          }
        }
        renderDescription={(row) => row.description}
        query={{
          key: GOOGLE_PLACES_API_KEY,
          language: "en",
        }}
        enablePoweredByContainer={false}
        styles={{
          textInputContainer: {
            backgroundColor: "#060531",
            height: 50,
            justifyContent: "center",
            borderColor: "#060531",
          },
          textInput: {
            borderRadius: 10,
            marginVertical: 10,
            marginHorizontal: 5,
            justifyContent: "center",
          },
          container: {
            position: "absolute",
            width: 415,
            zIndex: 999,
            justifyContent: "center",
            backgroundColor: "#060531",
          },
        }}
      />

```

**Comment by yugalkishoregoyal** [comment]
@bell-steven Suggested solution is not what was being asked in the original question.

1) When we are trying to use the Custom Text Input Component using textInputProps prop, it is no more loading the list view, no matter what the component styling is. It is also not triggering the OnFocus and Other Input Methods.

I'm referring to this code here.

<GooglePlacesAutocomplete
        placeholder="Type your location..."
        query={{
          key: GOOGLE_PLACES_API_KEY,
          language: "en",
        }}
        textInputProps={{
          InputComp: TextInput,
          // props for TextInput go here
          onChangeText: (text) => text,
          clearButtonMode: 'always'
        }}
      />

2) When using the Styling for the default Text Component, when can not set Text Input Header or any icon. Now in our case, Let's say I want to use Text Input Header as Start / Destination or Use the Icons on Left/Right Sides.

Please suggest if this library supports custom Text Input or should we plan to build something from scratch using Google's REST APIs.

Thanks.

**Comment by codal-hkrishnani** [comment]
@yugalkishoregoyal I am having same issue any update on it?

**Comment by Bronsky91** [comment]
I was able to get this working with my custom Input Component by including `onChangeText` as a prop of my custom component that links to the base <TextInput /> onChangeText callback. Assuming the Google Places component needs access to it to function.

Example:
Custom Text Component
```
const GooglePlacesInput = ({
  field,
  placeholder,
  style,
  icon,
  onChangeText,
}) => {
  return (
    <View style={[...style]}>
      {icon ? <Ionicons name={icon} size={32} color="gray" /> : null}
      <View style={[styles.inputContainer]}>
        <View style={styles.subInputContainer}>
          <Text style={styles.label}>{field.label}</Text>
          <TextInput
            style={styles.inputBase}
            placeholderTextColor="#C7C7CD"
            placeholder={placeholder}
            onChangeText={onChangeText}
          />
        </View>
      </View>
    </View>
  );
};
```

Parent `GooglePlacesAutocomplete` component
```
 <GooglePlacesAutocomplete
              onPress={(data, details = null) => {
               // Address info from API
              }}
              query={{
                key: "Google Places API Key",
                language: "en",
              }}
              styles={styles}
              textInputProps={{
                InputComp: GooglePlacesInput,
                field: {
                  id: "address",
                  label: "Address (Optional)",
                  type: "textline",
                },
                size: "large",
                placeholder: "Home, Office, Storage Unit, etc",
                style: [{ flex: 1 }],
              }}
            />
            ```

**Comment by fullstackdevelopercoder** [comment]
Hey, If any one still facing this issue, here is how i resolved it:

Code: 

 <View style={{ width: 90%, height: '50%', marginTop: 50, backgroundColor: 'white, padding: 10, 
                  borderRadius:16,alignItems: 'center' }}>

        <GooglePlacesAutocomplete
          ref={searchInputRef}
          debounce={500}
          placeholder="Search"
          minLength={2}
          keyboardShouldPersistTaps={'always'}
          isRowScrollable={false}
          listViewDisplayed={'auto'} // true/false/undefined
          fetchDetails={true}
          reverse
          enableHighAccuracyLocation={true}
          enablePoweredByContainer={false}
          onPress={(data, details = null) => locationItemPress(data, details)}
          suppressDefaultStyles={true}

          textInputProps={{
            InputComp: Input,
            inputContainerStyle: { borderBottomWidth: 0, height: '100%', width: '100%' },
            containerStyle: { height: 55, width: '100%' },
            clearButtonMode: 'never',
            autoFocus: true,
            rightIcon: <Image source={"YOUR IMAGE NAME"} style={"YOUR IMAGE STYLE"} />
          }}

          renderRow={(rowData) =>{ 
    const title = rowData?.structured_formatting?.main_text;
    const address = rowData?.structured_formatting?.secondary_text;
    return (
      <View style={{
        flexDirection: 'row', width: '100%', backgroundColor: 'white',
        borderRadius: 10, overflow: 'hidden', paddingHorizontal: 16,
        paddingVertical:20
      }}>
        <View style={{ width: '14%', height: 30, justifyContent: 'center' }}>
          <Image
            style={{ height: 24, aspectRatio: 1 }}
            // resizeMode="contain"
            source={IMAGENAME}
          />
        </View>
        <View style={{ width: '86%', justifyContent: 'center' }}>
          <Text style={{ fontSize: 14, color:'red' }} numberOfLines={2}>
            {title}
          </Text>
        </View>
      </View>)}}

          query={{ key: "YOUR GOOGLE API KEY", language: 'en' }}
          onFail={error => alert(error)}
          onNotFound={error => alert(error)}
          onTimeout={error => alert(error)}
          currentLocation={true}
          currentLocationLabel="Current location"

          styles={{
            container: {
              width: '100%',
              height: '100%',
              alignItems: 'center'

            },
            textInputContainer: {
              width: '100%',
              height: 60,
              borderRadius: 12,
              borderWidth: 2,
              alignSelf: 'center',
              borderColor: 'grey,
              justifyContent: 'center'
            },
            listView: {
              height: 52,
              width: '95%',
              marginTop: 16
            },
            separator: {
              height:12,
              backgroundColor: 'white',
            },
            // description: {},
            loader: {
              justifyContent: 'flex-end',
              height: 20,
            },
          }}
        />
      </View>

In above code check these props mainly:

 1- textInputProps={{
            InputComp: Input,  
            inputContainerStyle: { borderBottomWidth: 0, height: '100%', width: '100%' },     
            containerStyle: { height: scalerHeight(55), width: '100%' },           
            clearButtonMode: 'never',
            autoFocus: true,
            rightIcon: <Image source={"YOUR IMAGE NAME"} style={"YOUR IMAGE STYLE"} />
          }}

  

    InputComp: Input,    // Pass custom component here. (I’m using Input from “react-native-elements”)

   All others are props like (inputContainerStyle, containerStyle, rightIcon, clearButtonMode, etc) of Input component. You 
  can check more props here: https://reactnativeelements.com/docs/input


2-   textInputContainer: {
              width: '100%',
              height: scalerHeight(60),
              borderRadius: scalerHeight(12),
              borderWidth: 2,
              alignSelf: 'center',
              borderColor: ColorsUI.placeholdertext,
              justifyContent: 'center'
            },


 You can pass design according to your requirement here for textInput Container. This is “GooglePlacesAutocomplete” style prop.

3-  suppressDefaultStyles={true}.     // To remove default styles and customise with full control

4- renderRow          // Check this prop also



Hope this helps
