### ISSUE TITLE
Bug Report - onPress callback is not working

### ISSUE THREAD

**Issue by JavierLaguna** [FaridSafi/react-native-google-places-autocomplete#572]
# Describe the bug

The function callback on onPress prop is not working when I tap on a item result

# Reproduction - (required - issue will be closed without this)

Search an address and select one item of the result list

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click to expand!</summary>
  Search an address and select one item of the result list, the console.log is now printing on the above code

  ```javascript
    <GooglePlacesAutocomplete
            onPress={(data, details = null ) => {
              console.log(data, details);
            }}
            query={{
              key: MAPS_API_KEY,
              language: 'en',
              types: 'address',
            }}
          />
    
  ```
</details>

_Please remember to remove you google API key from the code you provide here_

# Additional context

- Library Version: [1.7.1]
- React Native Version: [0.61.4]

- [x] iOS
- [x] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc
![image](https://user-images.githubusercontent.com/16035941/84278406-0264d380-ab35-11ea-814b-424890aea057.png)

**Comment by itsGabriel** [comment]
i'm facing the same problem, but only happens with IOS. I cant click in none of listview items(except if I click randomly several times over they).I'm not wraping a `scrollview` btw its inside a `safeareaview`

**Comment by bell-steven** [comment]
@itsGabriel can you try using `<SafeAreaView />` from `[react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context)`?

I've run into the same thing before. If you drop a link to a snack i'll be happy to take a look.
