### ISSUE TITLE
support new prop for customized navigator

### ISSUE THREAD

**Issue by kelvin-dev** [FaridSafi/react-native-google-places-autocomplete#574]
![screenshot-2020-06-14_04 27 26 663](https://user-images.githubusercontent.com/19224355/84579368-628a9c80-adf7-11ea-9a5d-f7537cd86ec2.png)

**Comment by bell-steven** [comment]
@kelvin-dev What version of the library are you using? This was removed in v1.6.0.
Take a look at #541 for more context. Always open to new ideas though...
