### ISSUE TITLE
Cannot get search position (lat,lng) - null result

### ISSUE THREAD

**Issue by kelvin-dev** [FaridSafi/react-native-google-places-autocomplete#575]
Please help check the callback onPress={(data, details = null) => { console.log(data, details}; with fetchDetails = true
 
![screenshot-2020-06-16_00 45 47 425](https://user-images.githubusercontent.com/19224355/84689336-0779b680-af6b-11ea-9ca8-2c1caf1d7f16.png)

**Comment by bell-steven** [comment]
Please follow the issue template.
