### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by dakkafex** [FaridSafi/react-native-google-places-autocomplete#576]
The component doesnt work as intended, no search results at all 

**how to recreate:**

Start fresh react native project(not expo) and copy the example code.
Or even easier, check your own [Snack](https://snack.expo.io/@sbell/react-native-google-places-autocomplete)

react-native version: 0.61

**Comment by bell-steven** [comment]
Please follow the issue template. It very much does work. 

_p.s.  Try and use a valid API key, it might do wonders_ 😉
