### ISSUE TITLE
Android clear button missing

### ISSUE THREAD

**Issue by Dimasprog** [FaridSafi/react-native-google-places-autocomplete#581]
**Android clear button missing while on IOS all is gonna work fine!**

When text input is on focus state, then on Android is missing clear text input button, while on IOS is working!

<img width="785" alt="Screen Shot 2020-07-03 at 16 57 09" src="https://user-images.githubusercontent.com/37815085/86475964-46bb4c00-bd4e-11ea-91ef-64d17bc7fec1.png">

- Library Version: [1.4.1]
- React Native Version: [0.61.5]

**Comment by bell-steven** [comment]
As you can see in the React Native docs [here](https://reactnative.dev/docs/textinput#clearbuttonmode), this is a limitation of the React Native `<TextInput />`.  You can always use a custom Input component or the `renderRightButton` prop to display a custom clear content icon.

**Comment by strdr4605** [comment]
Still, I think that will be nice to have it as a default!

**Comment by Dimasprog** [comment]
> Still, I think that will be nice to have it as a default!

Yes, good idea!

**Comment by bell-steven** [comment]
@strdr4605 @Dimasprog having it as a default means writing a custom Input component, and all the issue that can go along with that.  If you can think of a reasonable implementation for this, please do put in a PR, I would be more than happy to review it.

**Comment by Dimasprog** [comment]
> @strdr4605 @Dimasprog having it as a default means writing a custom Input component, and all the issue that can go along with that. If you can think of a reasonable implementation for this, please do put in a PR, I would be more than happy to review it.

@bell-steven ok, i will think about it!

**Comment by cbovis** [comment]
@bell-steven do you have any tips for how a custom clear button could be implemented? I had a crack at this but noticed search results disappear every time the Autocomplete component is re-rendered.

**Comment by bell-steven** [comment]
@cbovis would you mind showing some code? You might need to set listViewDisplayed="false".

**Comment by Dimasprog** [comment]
@cbovis, Here is how I implemented custom clear button for text input:

![Screen Shot 2020-07-07 at 18 10 44](https://user-images.githubusercontent.com/37815085/86801934-32908b00-c07d-11ea-9ae4-f5d427eb18d5.png)

**Comment by cbovis** [comment]
Thanks @Dimasprog this was super useful 👍

**Comment by jamalumusic** [comment]
@cbovis  and @Dimasprog   Here is how I implemented custom clear button:

`
  const googlePlaceAutoCompleteRef = useRef(null)
  
<GooglePlacesAutocomplete
          ref={googlePlaceAutoCompleteRef}
          renderRightButton={() => (
            ( googlePlaceAutoCompleteRef.current?.getAddressText() 
                ? 
                 <TouchableOpacity 
                      style={styles.clearButton}
	              onPress={() => { googlePlaceAutoCompleteRef.current?.setAddressText('')}} >
                           <Ionicons name={'close-circle-outline'} color={'black'} size={20} />
		</TouchableOpacity> 
               :
                null )	)}
/>`

**Comment by rogerrc12** [comment]
I'm doing the same but when I click on the button to clear the address is not dissapearing:

`<GooglePlacesAutocomplete
        ref={autoCompleteRef}
        placeholder={placeholder}
        onPress={(data, details = null) => {
          console.log(data, details);
        }}
....
        textInputProps={{
          placeholderTextColor: "#aaa"
        }}
        renderRightButton={() =>
          autoCompleteRef.current?.getAddressText() ? (
            <TouchableOpacity onPress={handleClearText}>
              <Ionicons name={"close-circle-outline"} color={"black"} size={20} />
            </TouchableOpacity>
          ) : null
        }
        debounce={300}
      />`
