### ISSUE TITLE
AutoFocusText

### ISSUE THREAD

**Issue by MyroslavKoval1999** [FaridSafi/react-native-google-places-autocomplete#589]
Hi everyone, is this have a way for autofocus when input is focused? or can we use textInput inside GooglePlacesAutocomplete? because textInput have a selectTextOnFocus for this

**Comment by bell-steven** [comment]
There is the `autoFocus prop`.  Please check the list of props in the [README](https://github.com/FaridSafi/react-native-google-places-autocomplete#props).

**Comment by MyroslavKoval1999** [comment]
Sorry, I mean automatically select text to delete as selectTextOnFocus in textInput

**Comment by bell-steven** [comment]
You can pass any <TextInput /> props through the `textInputProps` prop.

```
import React from 'react';
import { Image, Text } from 'react-native';
import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';

const GooglePlacesInput = () => {
  return (
    <GooglePlacesAutocomplete
      placeholder='Search'
      onPress={(data, details = null) => {
        // 'details' is provided when fetchDetails = true
        console.log(data, details);
      }}
      query={{
        key: 'YOUR API KEY',
        language: 'en',
      }}
      textInputProps: {{
        selectTextOnFocus: true
     }}
    />
  );
};

export default GooglePlacesInput;
```

**Comment by MyroslavKoval1999** [comment]
textInputProps={{
        selectTextOnFocus: true
     }}
Work! Thank you!
