### ISSUE TITLE
Losing focus when typing

### ISSUE THREAD

**Issue by jojonarte** [FaridSafi/react-native-google-places-autocomplete#59]
Do we get a workaround so we don't lose focus on the search bar when showing new update to listview of results?

**Comment by myaskevich** [comment]
Hi @jojonarte 

It shouldn't unless you tap somewhere outside TextInput element.

**Comment by jojonarte** [comment]
Here is a video of what happens http://www.screencast.com/t/vLl5tsMb1Rc

**Comment by jojonarte** [comment]
Nevermind I've found out the issue was coming from a different component. Thanks for this.

**Comment by papaQwesi** [comment]
where was the problem coming . I have a similar issue
