### ISSUE TITLE
Query "types" is not pulling towns/neighborhoods

### ISSUE THREAD

**Issue by oporter1** [FaridSafi/react-native-google-places-autocomplete#590]
# Describe the problem

A clear and concise description of what you are trying to do and where things are going wrong.

According to the documentation (https://developers.google.com/places/supported_types#table2) I can specify (city) or (regions) to be able to get granular within cities and pull the neighborhoods. But when I enter in the neighborhoods, only the containing major city populates. The sublocality or administrative_area_level_3/4/5 should return the neighborhood/ town name. Furthermore, it is only returning city, state and is not doing a broad search for any of the other types in the table 1 or table 2 collection. Am I writing the query correctly? 

        query={{
          key: API_KEY,
          language: "en", // language of the results
          types: "(regions)",
        }}

# Reproduction - (required - issue will be closed without this)

Steps to reproduce the behavior - a minimal reproducible code example, link to a [snack](https://snakc.expo.io) or a repository.

set up the GooglePlacesAutocomplete with a query of: 

        query={{
          key: API_KEY,
          language: "en", // language of the results
          types: "(regions)",
        }}

or 

        query={{
          key: API_KEY,
          language: "en", // language of the results
          types: "(cities)",
        }}

search in the UI for a town or neighborhood and only major cities will appear. 

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click to expand!</summary>
  
  ```javascript
    return (
      <GooglePlacesAutocomplete
        debounce={200}
        ref={(c) => (googlePlacesAutocomplete = c)}
        listViewDisplayed={false}
        minLength={3}
        placeholder="Search..."
        autoFocus={false}
        returnKeyType={"search"}
        fetchDetails={true}
        keyboardShouldPersistTaps={"handled"}
        query={{
          key: API_KEY,
          language: "en", // language of the results
          types: "(regions)",
        }}
        styles={{
          textInputContainer: {
            backgroundColor: "rgba(0,0,0,0)",
            borderTopWidth: 0,
            borderBottomWidth: 0,
            margin: 10,
          },
          textInput: {
            marginLeft: 0,
            marginRight: 0,
            height: 38,
            color: "#5d5d5d",
            fontSize: 16,
          },
          description: {
            fontWeight: "bold",
            fontSize: 12,
          },
          predefinedPlacesDescription: {
            color: "black",
          },
        }}
        renderDescription={(value) => value.description}
        onPress={(data, details) => {
          updateLocationArray(data, details, timeFrame);
        }}
      />
    );
    
  ```
</details>

_Please remember to remove you google API key from the code you provide here_

# Additional context

- Library Version: [e.g. 1.4.2]
- React Native Version: [e.g. 0.62.2]

    react-native-cli: 2.0.1
    react-native: 0.61.4
    "react-native-google-places-autocomplete": "^1.3.9",

- [ x] iOS
- [ ] Android
- [ ] Web

If you are using expo please indicate here:

- [ x] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by bell-steven** [comment]
I am not sure I fully understand your issue. 
I am having trouble understanding what your desired behavior is when using `types: "(regions)",` or `types: "(cities)",`  in the autocomplete query.  

Would you mind writing, or showing a screenshot/illustration of:
1) the exact information you expect to see back on the autocomplete field,
2) the information you expected to see when you pressed on a result,

This would help me understand what you are trying to fetch from the 2 different APIs (Query autocomplete API vs Place Details API).

**Comment by KrisLau** [comment]
For anyone looking at this now, it is `type` not `types`:
```
query={{
    key: 'YOUR_GOOGLE_ PLACES_API_KEY',
    type: '(cities)',
    language: 'en',
}}
```
