### ISSUE TITLE
Works fine in debug, but not in release mode

### ISSUE THREAD

**Issue by NiloDrumond** [FaridSafi/react-native-google-places-autocomplete#591]
It works fine in debug mode, but not in release mode.

This is the repository: https://github.com/NiloDrumond/weather-app

The component shows, but typing does not autocomplete and submiting does nothing.

When trying both on my phone and on android emulator, the list from the autocomplete appeared, but blank. Everything works fine on debug mode.

- Library Version: [^1.8.0]
- React Native Version: [0.63.1]

- [x ] Android

![image](https://user-images.githubusercontent.com/48765760/88237265-4af3ce80-cc55-11ea-8648-bcae62ef2e2d.png)

**Comment by bell-steven** [comment]
Are you using the same Google API key for debug and release?  That would be my guess, as there is no logic in the library that depends on debug/release.

**Comment by NiloDrumond** [comment]
> Are you using the same Google API key for debug and release? That would be my guess, as there is no logic in the library that depends on debug/release.

It's very possible that the problem is related to the api key. But if that is the case, what should i do? I tried to find anything related to this in the Google Api docs but didn't have much success. I tried protecting the api key with the SHA-1, but that didn't solve the problem.
