### ISSUE TITLE
setAddressText is not working

### ISSUE THREAD

**Issue by NareshNama** [FaridSafi/react-native-google-places-autocomplete#592]
setAddressText is not working

**Comment by bell-steven** [comment]
Please follow the issue template.

**Comment by NareshNama** [comment]
<GoogleAutoCompleteAddress
                    onPress={(data, details = null) => {
                        this.fetchGoogleLocationDetails(details);
                    }}
                    textInputProps={{
                        value:lossAddress,
                        onChangeText={_onChangeTextValue()}
                    }}
                    editable={true}
                    autoFocus={false} />

onChangeText is not working and showing syntax error

**Comment by KrisLau** [comment]
@bell-steven I have followed the example in the docs but the input is showing a blank
