### ISSUE TITLE
How to Style GooglePlacesAutocomplete?

### ISSUE THREAD

**Issue by Aishwarya411** [FaridSafi/react-native-google-places-autocomplete#594]
![Capture](https://user-images.githubusercontent.com/66615402/88663357-1cfd0700-d0f9-11ea-9301-bba16a537add.PNG)

How to style GooglePlacesAutocomplete like this, and also how to style the searchbar?

**Comment by bell-steven** [comment]
Please see the [styling](https://github.com/FaridSafi/react-native-google-places-autocomplete#styling) section of the readme.

**Comment by Aishwarya411** [comment]
@bell-steven But there is no detail information on the link you have provided

**Comment by bell-steven** [comment]
To achieve something similar to what is pictured above, you would need to use the `renderRow` prop (see [this](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/429#issuecomment-574553219) issue for a rough example).  
In terms of styling the search bar, the information is in the styling section of the readme. 

Please keep these Github issues to bugs and feature proposals.

**Comment by alvesadolfo** [comment]
> To achieve something similar to what is pictured above, you would need to use the `renderRow` prop (see [this](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/429#issuecomment-574553219) issue for a rough example).
> In terms of styling the search bar, the information is in the styling section of the readme.
> 
> Please keep these Github issues to bugs and feature proposals.

Not work for me, you have one complete example ?
