### ISSUE TITLE
onChangeText is not working

### ISSUE THREAD

**Issue by NareshNama** [FaridSafi/react-native-google-places-autocomplete#595]
<GoogleAutoCompleteAddress
onPress={(data, details = null) => {
this.fetchGoogleLocationDetails(details);
}}
textInputProps={{
value:lossAddress,
onChangeText:{_onChangeTextValue()}
}}
editable={true}
autoFocus={false} />

onChangeText is not working and showing syntax error

**Comment by bell-steven** [comment]
Please provide a **reproducible** example.
