### ISSUE TITLE
Feature Request: is there a way to use the places api without using the UI component?

### ISSUE THREAD

**Issue by nimrodbens** [FaridSafi/react-native-google-places-autocomplete#599]
**Is your feature request related to a problem? Please describe.**

in one section in my app i use the autocomplete feature and in another section i just need some details about a predefined coordinate.

**Describe the solution you'd like**

**Comment by bell-steven** [comment]
>  i just need some details about a predefined coordinate
Can you elaborate a little more?  
What information are you already getting from the autocomplete.

What kind of solution would you like to see?

**Comment by nimrodbens** [comment]
hi, thanks for answering. something along the way of getting a place object from a coordinate? to provide just a coordinate and get a list of the places close to it from the api without using the UI component. it doesn't need to be the current location of the user. it can be any coordinate.

honestly i was just wondering if it's possible with this library.

**Comment by bell-steven** [comment]
If you don't want to use the UI component, I would recommend calling the appropriate Google APIs directly.  
This is something that I think falls a little out of scope for what this library does.

**Comment by nimrodbens** [comment]
i completely understand. i thought maybe there was a way and i was missing it. 
thank you :)
