### ISSUE TITLE
a second tap is needed when the component is embedded inside a scrollview

### ISSUE THREAD

**Issue by FaridSafi** [FaridSafi/react-native-google-places-autocomplete#6]
The issue occurs when the component is embedded inside a ScrollView.

**Comment by FaridSafi** [comment]
A quick fix is to embed it inside a View

**Comment by kanerogers** [comment]
Yes! I've encountered this issue and didn't know what it was. Thanks! :smile:

**Comment by kanerogers** [comment]
Any update on this one @FaridSafi ?

**Comment by FaridSafi** [comment]
Hello, I'm not experimenting this issue when embedding inside a View.
I think this issue is more related to react-native ScrollView than to this component

**Comment by kanerogers** [comment]
Yeah, that fixed it for me!

Weird. 🤓

**Comment by sodik82** [comment]
not sure if it is same problem as here: http://stackoverflow.com/questions/36476542/react-native-requires-two-taps-to-change-input-focus-when-within-scrollview

**Comment by myaskevich** [comment]
Hi @kanerogers @sodik82 

I'm afraid this issue is RN-specific and is not related to this library in particular.

**Comment by kanerogers** [comment]
Thanks for the reply, Maxim. :)
