### ISSUE TITLE
Always show the list when I click "Search"

### ISSUE THREAD

**Issue by NRech** [FaridSafi/react-native-google-places-autocomplete#602]
# Describe the problem

(Thanks for your amazing work here!)
Sorry if this was already answered, but I could not find anything that helps...

I just need to keep showing the results when the user clicks "Search", but I could not do it. I tried with every prop related (onBlur, onSubmitEditing, listViewDisplayed), I tried to use an external state for listViewDisplayed... Absolutely nothing worked, it seems the inner state always override what I pass.

# Additional context

- Library Version: [e.g. 1.8.0]
- React Native Version: [e.g. 0.62.2]

- [X] iOS
- [ ] Android
- [ ] Web

If you are using expo please indicate here:

- [X] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by bell-steven** [comment]
Your best bet would be using a ref to trigger `triggerFocus`.  See [this](https://snack.expo.io/@sbell/excited-bubblegum) snack for an example.
