### ISSUE TITLE
Hide keyboard but display a adresses list

### ISSUE THREAD

**Issue by AlexeyAZ** [FaridSafi/react-native-google-places-autocomplete#603]
Hello! Can I hide the keyboard but display a adresses list?

**Comment by bell-steven** [comment]
See the `listViewDisplayed` prop. Also checkout the ref mentioned in #602.

**Comment by AlexeyAZ** [comment]
Thank you!

**Comment by McDreamy** [comment]
Hi, listViewDisplayed only works on android but not ios.
I tried to trigged focus onSubmitEnding but not working.
