### ISSUE TITLE
Feature Request: Initial search text

### ISSUE THREAD

**Issue by eyalyoli** [FaridSafi/react-native-google-places-autocomplete#604]
I would like to allow the user to have an initial text filled in for him to edit. This comes handy when I already have an address and the user asked to edit it later.

I suggest to enable passing an initialValue prop so that the state of the search input gets initialized with this value.

Predefined places is a good alternative but have bad user experience (the user should not have to do additional steps in order to have the search input filled for him.

Thnx

**Comment by bell-steven** [comment]
This is possible using `getDefaultValue` or a ref with the `setAddressText` method. 
```js
<GooglePlacesAutocomplete
        ref={ref}
        placeholder="Search"
        minLength={1}
        getDefaultValue={() => "93 john street"}
        onPress={(data, details = null) => {
          // 'details' is provided when fetchDetails = true
        }}
        query={{
          key: GOOGLE_PLACES_API_KEY,
          language: "en",
        }}
      />
```

or 

```js
  useEffect(() => {
    ref.current.setAddressText('93 John Street);
  }, []);

...
<GooglePlacesAutocomplete
        ref={ref}
        placeholder="Search"
        minLength={1}
        onPress={(data, details = null) => {
          // 'details' is provided when fetchDetails = true
        }}
        query={{
          key: GOOGLE_PLACES_API_KEY,
          language: "en",
        }}
      />
```

**Comment by eyalyoli** [comment]
Thank you, it woked fine!
