### ISSUE TITLE
Input will hide behind other inputs

### ISSUE THREAD

**Issue by dakkafex** [FaridSafi/react-native-google-places-autocomplete#605]
# Describe the bug

The input will hide behind other inputs and the list wont show up at all
# Reproduction - (required - issue will be closed without this)

Here is the snack link [snack](https://snack.expo.io/Hql0bqsT5) 

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click to expand!</summary>
  
  ```javascript
    
    import * as React from 'react';
import { View, StyleSheet, TextInput } from 'react-native';
import Constants from 'expo-constants';
import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';

const GOOGLE_PLACES_API_KEY = ''; // never save your real api key in a snack!

const App = () => {
  return (
    <View style={styles.container}>
      <View style={{ height: 100 }}>
        <TextInput
          style={{ height: 40, borderColor: 'gray', borderWidth: 1 }}
        />
        <GooglePlacesAutocomplete
          query={{
            key: GOOGLE_PLACES_API_KEY,
            language: 'en', // language of the results
          }}
          onPress={(data, details = null) => console.log(data)}
          onFail={(error) => console.error(error)}
          requestUrl={{
            url:
              'https://cors-anywhere.herokuapp.com/https://maps.googleapis.com/maps/api',
            useOnPlatform: 'web',
          }} // this in only required for use on the web. See https://git.io/JflFv more for details.
          styles={{
            textInputContainer: {
              backgroundColor: 'rgba(0,0,0,0)',
              borderTopWidth: 0,
              borderBottomWidth: 0,
            },
            textInput: {
              marginLeft: 0,
              marginRight: 0,
              height: 38,
              color: '#5d5d5d',
              fontSize: 16,
            },
            predefinedPlacesDescription: {
              color: '#1faadb',
            },
          }}
        />
        <TextInput
          style={{ height: 40, borderColor: 'gray', borderWidth: 1 }}
        />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

export default App;
  ```
</details>

# Additional context

- Library Version: latest
- React Native Version: 0.62

- [x] iOS
- [x] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc
https://i.imgur.com/zeFDWKL.png

**Comment by bell-steven** [comment]
Because you are limiting the height of the component, it is hiding the list view.  I don't think this is a library bug.  You can leave the component enough space to render the listview, or wrap the component in a view that will overlay the other components.

**Comment by dakkafex** [comment]
yeah but why doesnt the autocomplete input component behave like other input compotnents?

**Comment by bell-steven** [comment]
The input component is fine, it is the listview which is being 'hidden', which is arguably expected behavior. 

You can pass in a custom input component into `textInputProps`:
```js
textInputProps={{
InputComp: <Input />
}}
```

**Comment by dakkafex** [comment]
Well then first off
`InputComp` is not documented anywhere, in this library, or the [docs for TextInput](https://reactnative.dev/docs/textinput)

secondly, if you check https://snack.expo.io/137s9pPUO on android and ios

going with the most basic setup,  no height styles.
```jsx
<TextInput style={{ borderWidth: 1 }} />
<TextInput style={{ borderWidth: 1 }} />
<GooglePlacesAutocomplete />
<TextInput style={{ borderWidth: 1 }} />
<TextInput style={{ borderWidth: 1 }} />
```
this is the result
![image](https://user-images.githubusercontent.com/7563763/89831219-bd254800-db5d-11ea-835d-b378b59adbd2.png)

You can't tell me that that is expected behavior

**Comment by dakkafex** [comment]
And here I managed to dial in on the zIndexing issue when using `position: absolute` on the list style
https://snack.expo.io/Y!lipqP0R
Firstly, it just looks wrong
![image](https://user-images.githubusercontent.com/7563763/89841083-565e5980-db72-11ea-97e6-62be236c5d0a.png)

And any View component behind the results list, will be ontop, sort of, and pressable instead of the result row

**Comment by bell-steven** [comment]
First off, thank you for taking the time to reproduce this and dig into it.

Just so other people reading this know, the correct way to solve this (currently) is to set the `zIndex` in the container style and `position: absolute` or `fixed` in the `listView` style.

<details>
  <summary>Example</summary>
  
```js
import * as React from 'react';
import { View, StyleSheet, TextInput, TouchableOpacity } from 'react-native';
import Constants from 'expo-constants';
import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';

const GOOGLE_PLACES_API_KEY = ''; // never save your real api key in a snack!

const App = () => {
  return (
    <View style={styles.container}>
      <View>
        <TextInput style={{ borderWidth: 1, height: 40 }} />
        <GooglePlacesAutocomplete
          query={{
            key: GOOGLE_PLACES_API_KEY,
            language: 'en', // language of the results
          }}
          onPress={(data, details = null) => console.log(data)}
          onFail={(error) => console.error(error)}
          requestUrl={{
            url:
              'https://cors-anywhere.herokuapp.com/https://maps.googleapis.com/maps/api',
            useOnPlatform: 'web',
          }} // this in only required for use on the web. See https://git.io/JflFv more for details.
          styles={{
            container: {
              zIndex: 99,
            },
            listView: {
              backgroundColor: 'white',
              position: 'absolute',
              marginTop: 40,
            },
          }}
        />
        <TouchableOpacity onPress={() => alert('taco')}>
          <TextInput
            placeholder="Press here and you wil get an alert"
            style={{ borderWidth: 1, borderColor: 'red', height: 40 }}
          />
        </TouchableOpacity>
        <View style={{ height: 30, backgroundColor: 'orange' }} />
        <TextInput style={{ borderWidth: 1, height: 40 }} />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

export default App;
```
</details>

> Well then first off
InputComp is not documented anywhere, in this library, or the docs for TextInput, its also not in the d.ts file

You are right.  Feel free to put in a PR

> You can't tell me that that is expected behavior...

If you take out all the styles it would have fit in the box. 

If you feel there is a better approach to this (or anything), I would be more than happy to discuss and/or review/merge a PR.

**Comment by arulp3** [comment]
There is a simple solution to this, Jus create a separate view and put the Googleautocomplete tag inside the view.

**Comment by diklou** [comment]
When I do that, the suggestions don't appear at all.
