### ISSUE TITLE
Bias search does not work

### ISSUE THREAD

**Issue by diegothucao** [FaridSafi/react-native-google-places-autocomplete#607]
Hi @FaridSafi ,
I am using your library for my projects to search google places. The library is very nice and helpful for me.
In order to priority the places that is near my location, i use `location` properties but seems it does not work.

```
   query={{
              key: setting.GOOGLE_PLACES_API_KEY,
              language: 'en',
              radius: 10000,
              location: {
                latitude: 21.028511,
                longitude: 105.804817
              }
            }}
```
When i tap `A` to search , it does not show the places that is near the above location, it shows some places they are so far from above one.

Could you support me what is my issue and how to fix it.

Thanks in advance,
Thu

**Comment by namthan** [comment]
Hi,

I'm facing the same issue. I've tried to use:
```
GooglePlacesSearchQuery={{
              location: {
                latitude: 53.958332,
                longitude:  -1.080278,
              },
              radius: 5000
            }}
```
But it still doesn't work.
Could someone please help to fix?

**Comment by bell-steven** [comment]
Location needs to be a string. 

I changed the definitions file to an object a few releases ago, not sure why.  The docs clearly say it needs to be string. 
![image](https://user-images.githubusercontent.com/13405567/90277404-81c39b80-de33-11ea-99bd-d8c716974a4b.png)

I am going to update the definitions file right now. 

```js
 query={{
              key: setting.GOOGLE_PLACES_API_KEY,
              language: 'en',
              radius: 10000,
              location: "21.028511,105.804817"
            }}
```

**Comment by diegothucao** [comment]
Thanks so much @bell-steven. It works now. 
I really appreciate.

**Comment by DusanSpasojevic98** [comment]
@bell-steven Do you know is there any way to say that we always want to prioritise current location without passing our location values?
