### ISSUE TITLE
Limiting the search to specific countries

### ISSUE THREAD

**Issue by pmusole2** [FaridSafi/react-native-google-places-autocomplete#608]
# Describe the problem
I am trying to set a limit for the countries to search for places from. 

# Reproduction
As per the documentation, I added the "query" prop which has an object where I specify my API key, language and I also added the components key with the value of a string as follows: 
query={{
        key: 'YOUR API KEY',
        language: 'en',
        components: 'country:zm', // zm is for Zambia and I also interchanged with the full country name
      }}

After typing in the search field it didn't bring any results regardless of the country I indicate, even US.

- "react-native-google-places-autocomplete": "^1.8.0"
- React Native Version: [sdk-38.0.2]

- [ ] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo version ~38.0.8

![image](https://user-images.githubusercontent.com/51131803/90408431-19c9bb00-e0a8-11ea-89b8-cd9cef375efa.png)

**Comment by bell-steven** [comment]
This query is correct. 
```
query={{
key: 'YOUR API KEY',
language: 'en',
components: 'country:zm',
}}
```

I just tested it, and it worked fine for me. 

> After typing in the search field it didn't bring any results regardless of the country I indicate, even US

My best guess is that your API key isn't configured with the proper api permissions or billing is not setup yet.

**Comment by pmusole2** [comment]
> This query is correct.
> 
> ```
> query={{
> key: 'YOUR API KEY',
> language: 'en',
> components: 'country:zm',
> }}
> ```
> 
> I just tested it, and it worked fine for me.
> 
> > After typing in the search field it didn't bring any results regardless of the country I indicate, even US
> 
> My best guess is that your API key isn't configured with the proper api permissions or billing is not setup yet.

It was the space. Thanks a lot. I had been stuck for hours
