### ISSUE TITLE
Controlled text input

### ISSUE THREAD

**Issue by tonygriv** [FaridSafi/react-native-google-places-autocomplete#61]
Hi.

Fox example, I would like to control the value of textInput manually. But as I understand It is not possible.

**Comment by tonygriv** [comment]
If you share this idea, I would be glad to do pull request.

**Comment by myaskevich** [comment]
Hi @tonygriv 

Tricky idea, I'd say. 

What is your use case?

**Comment by tonygriv** [comment]
More common. I have you component (as search) and google map. If user use uses TextInput thats not a problem. I receive lat lng and update the marker on the map. But where user drags the map and get new lat lng continuously. I would like to make reverse geocoding and set received address in to TextInput.

**Comment by myaskevich** [comment]
@tonygriv Check out `setAddressText` component method that you can trigger using refs.
