### ISSUE TITLE
Selected predefined place does not have all the information

### ISSUE THREAD

**Issue by soullivaneuh** [FaridSafi/react-native-google-places-autocomplete#610]
# Describe the bug

When I select a predefined place, lot of information such as `data.structured_formatting.main_text` or `details` are missing making the app behavior different following the case.

# Reproduction - (required - issue will be closed without this)

I don't have a fully producible example, but the description is quite clear and reproducable IMO.

Here is my `onPress` function:

```typescript
(data, details = null) => {
        const place: Place = {
          description: data.description,
          mainText: data.structured_formatting.main_text,
          location: details.geometry.location,
          postalCode: extractAddressComponentInfo(details.address_components, 'postal_code'),
          locality: extractAddressComponentInfo(details.address_components, 'locality'),
          country: extractAddressComponentInfo(details.address_components, 'country'),
        };

        navigation.navigate(callbackRouteName, { place });
      }
```

All the fetched data is present for a "classic" selection, only `data.description` is available for a predefined place selection.

I supposed this is because we are currently limited to the information we can give to the predefined place list:

```typescript
const predefinedPlaces: Place[] = accountAddressSuggestion
  ? user.addresses.map((address) => ({
    description: address.label,
    geometry: {
      location: {
        lat: address.place.location.lat,
        lng: address.place.location.lng,
      },
    },
  }))
  : [];
```

The solution would be to allow more details to give to the predefined place or play with the Google API to do some reverse information fetching.

# Additional context

- Library Version: 1.7.2
- React Native Version: expo-sdk-36.0.0

- [x] iOS
- [x] Android
- [ ] Web

If you are using expo please indicate here:

- [x] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by bell-steven** [comment]
A pre-defined place, for the purpose of this library, means that we don't need to hit the google apis to get any more information. 

I don't see why this is a bug.
