### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by BryanEnid** [FaridSafi/react-native-google-places-autocomplete#615]
# Describe the bug
Cannot select the suggested address. This only happens when the react-native-google-places-autocomplete component is inside a ScrollView. I'm pretty sure that's because the component was made with a FlatList. 

# Reproduction - (required - issue will be closed without this)
```js
import React from "react";
import { ScrollView } from 'react-native'
import { GooglePlacesAutocomplete } from "react-native-google-places-autocomplete";

export default function App() {
const createPlacesAutocompleteSessionToken = (a) =>
  a
    ? (a ^ ((Math.random() * 16) >> (a / 4))).toString(16)
    : ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, createPlacesAutocompleteSessionToken);

return (
<ScrollView>
    <GooglePlacesAutocomplete
      onSubmitEditing={() => console.log("asd")}
      onPress={(data, details = null) => console.log(data, details)}
      currentLocation={true}
      enablePoweredByContainer={false}
      styles={{container: {marginTop: 100}}}
      query={{
        // key: "YOUR_KEY",
        language: "en",
        types: "address",
        rankby: "distance",
        sessionToken: createPlacesAutocompleteSessionToken(),
      }}
    />
</ScrollView>
  );
}
```
https://snack.expo.io/4F1BKnunK

# Additional context

- Library Version: 1.8.1
- React Native Version: 37.0.1 (https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz)

- [x] iOS
- [x] Android
- [x] Web

If you are using expo please indicate here:

- [x] I am using expo

Add any other context about the problem here, screenshots, etc

**Comment by bell-steven** [comment]
Thanks for the reproduction. As you guessed, it is because you have the component within a scrollview and the library uses a flatlist to render its results. 
The solution is to add `keyboardShouldPersistTaps={'handled'}` to your scroll view. See [this](https://github.com/FaridSafi/react-native-google-places-autocomplete#compatibility) section of the Readme.
