### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ankurmaheshsingh** [FaridSafi/react-native-google-places-autocomplete#618]
# Describe the bug

GooglePlacesAutocomplete works fine on iOS, but doed not work for android devices.
No results are fetched.
Is this package only centric to iOS devices ?
 

# Reproduction - (required - issue will be closed without this)

Try to execute the same code on Android device.
There are lot many bugs such as.
1. There is no clear button for textInput
2. Place search not working.

Steps to reproduce the behavior - a minimal reproducible code example, link to a [snack](https://snack.expo.io) or a repository.

<GooglePlacesAutocomplete
        placeholder="Search"
        minLength={2}
        autoFocus={false}
        returnKeyType={'search'}
        listViewDisplayed="auto"
        fetchDetails={true}
        renderDescription={(row) => row.description}
        onPress={(data, details = null) => {
          console.log(data, details);
        }}
        getDefaultValue={() => ''}
        query={{
          key: 'YOUR API KEY',
          language: 'en',
          types: '(cities)',
        }}
        styles={{
          textInputContainer: {
            width: '100%',
          },
          description: {
            fontWeight: 'bold',
          },
          predefinedPlacesDescription: {
            color: '#1faadb',
          },
        }}
        currentLocation={true}
        currentLocationLabel="Current location"
        nearbyPlacesAPI="GooglePlacesSearch"
      />

# Additional context

- Library Version: 1.8.2
- React Native Version: 0.63

- [x] iOS
- [ ] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo - Not using expo

Add any other context about the problem here, screenshots etc

**Comment by bell-steven** [comment]
> There is no clear button for textInput
>
This is a limitation of React Native's `<TextInput/>`.  
![image](https://user-images.githubusercontent.com/13405567/93490685-ccbf4b80-f8d6-11ea-81dd-f691c5c72237.png)
You can always define your own input `textInputProps` or use the `renderRightButton` prop.


> Place search not working
>
Please provide a reproducible example, the code you provided works fine when I search for an address.
