### ISSUE TITLE
Error With Dark mode

### ISSUE THREAD

**Issue by amen160** [FaridSafi/react-native-google-places-autocomplete#619]
![Simulator Screen Shot - iPhone 8 - 2020-09-18 at 21 23 55](https://user-images.githubusercontent.com/6201829/93608819-477e8880-f9f5-11ea-8b94-4e4daeb3cea2.png)

**Comment by bell-steven** [comment]
Can you please provide a full reproduction (following the issue template)?  When I turn on dark mode, it all looks fine for me.  

![IMG_7D3A0B5612DF-1](https://user-images.githubusercontent.com/13405567/93881924-7f175a00-fcad-11ea-96fb-ed25919a2936.jpeg)
