### ISSUE TITLE
Custom ListView row renderer

### ISSUE THREAD

**Issue by tonygriv** [FaridSafi/react-native-google-places-autocomplete#62]
I think it's good to give the possibility to set custom renderer for ListView rows.

**Comment by tonygriv** [comment]
If you share this idea, I would be glad to do pull request.

**Comment by myaskevich** [comment]
Hi @tonygriv 

Using
- `props.styles.row`
- `props.styles.description`
- `props.styles. predefinedPlacesDescription`
is not enough for you?

I'm curious, what's your use case?

**Comment by tonygriv** [comment]
I use 

```
query={{
key: 'my_api_key',
language: config.LANG,
types: 'address',
}}
```

For example I would like to display only name of the street, but not the hole formatted_address

**Comment by myaskevich** [comment]
Ok, I just added a `renderDescription` prop for this.

https://github.com/FaridSafi/react-native-google-places-autocomplete/commit/1353de50215fb26cfed291ce41765ff0c07431c0

**Comment by myaskevich** [comment]
@tonygriv 

`rowData` passed to it has the following structure:

```
{
  "description": "Times Square, New York, NY, United States",
  "id": "81e2bb1d8297281ef1da7fe4f3f3d17c06ef0421",
  "matched_substrings": [
    {
      "length": 5,
      "offset": 0
    }
  ],
  "place_id": "EilUaW1lcyBTcXVhcmUsIE5ldyBZb3JrLCBOWSwgVW5pdGVkIFN0YXRlcw",
  "reference": "CjQtAAAAn4_hv2vzZFmn7O8BhTI5WORL-1rV9tO5QwY4andzWPLIGplv21bh0XcDIlIqdqhaEhDCBL9TYX4_BredscSE24MSGhRPvrBEPUF_lcxJjCPspbVYOrm4Jw",
  "terms": [
    {
      "offset": 0,
      "value": "Times Square"
    },
    {
      "offset": 14,
      "value": "New York"
    },
    {
      "offset": 24,
      "value": "NY"
    },
    {
      "offset": 28,
      "value": "United States"
    }
  ],
  "types": [
    "route",
    "geocode"
  ]
}
```

**Comment by tonygriv** [comment]
Thanks!

**Comment by myaskevich** [comment]
I'll let you know when it bones avail in the next version
Sincerely,
Maxim Yaskevich




On Sat, Oct 15, 2016 at 5:08 PM +0300, "Anton Sivogrivov" <notifications@github.com> wrote:












Thanks!

**Comment by myaskevich** [comment]
Available in `v1.2.5`

**Comment by tonygriv** [comment]
I didn't pay attention to the fact that renderDescription is called in the <Text></Text> block :( 
I need to format rows for example like this:

<View>
   <View>{street}</View>
   <View>{someOtherLocationData}</View>
</View>

Is it possible to make these improvements?

**Comment by tonygriv** [comment]
I look forward :)

**Comment by myaskevich** [comment]
@tonygriv `renderRow` props was exclusively added in `v1.2.6`

**Comment by tonygriv** [comment]
Awesome! Thanks a lot :)

**Comment by brascene** [comment]
I'm using renderRow prop to modify list, but I'm not able to change the height of single list item. Any ideas?

Thanks!

**Comment by myaskevich** [comment]
Use `props.styles.description` prop

**Comment by brascene** [comment]
Isn't that prop for text style? 
In renderRow I return View whose height I want to change, but it's not being applied.

**Comment by brascene** [comment]
Found it, this is the prop I've been looking for: "row" : { height: 50 }

**Comment by GerardCasadevall** [comment]
I need to format rows for example like this:

<View>
<Icon
	type="MaterialIcons"
	name="location-on"
	style={[
		Styles.smallIcons,
		{ color: Theme.darkGrayColor }
	]}
/>
   <Text>{row.structured_formatting.main_text}</Text>
   <Text>{row.structured_formatting.secondary_text}</Text>
</View>

Is it possible ?
