### ISSUE TITLE
Please add `strictbounds` property to types

### ISSUE THREAD

**Issue by victorwpbastos** [FaridSafi/react-native-google-places-autocomplete#620]
Typescript complains about `strictbounds` property:

![image](https://user-images.githubusercontent.com/1017515/93842684-19f04400-fc6e-11ea-9afe-6e7b0ea84647.png)

**Comment by bell-steven** [comment]
Would you be willing to create a PR?  There are actually a few missing and incorrect types.

**Comment by victorwpbastos** [comment]
PR #621 created!

**Comment by MaxInMoon** [comment]
Issue still exists
