### ISSUE TITLE
Setting a predefined place in the search text box 

### ISSUE THREAD

**Issue by Jaafar-abusair** [FaridSafi/react-native-google-places-autocomplete#63]
Hi,

Is't possible to set a predefined place in the search text box, 

Why i need this?

If the user want to edit his choice of picking place, I want to load the old place in the search text box, I can load the old option to the list like current location, but i prefer to add it to the search text box.

Thanks

**Comment by myaskevich** [comment]
Hi @Jaafar-abusair 

Check out `predefinedPlaces` prop.

**Comment by Jaafar-abusair** [comment]
Hi @myaskevich 

As i mentioned in the description above, this is what I'm using right now, but this not loading the location to the search text box, It does adding places to the list beneath it.

Thanks

**Comment by myaskevich** [comment]
Hi @Jaafar-abusair 

Check out `setAddressText` method on the component.

**Comment by Jaafar-abusair** [comment]
I'm using it inside Modal, I tried to set ref parameter to like addressPicker,
 then I tried to this.refs.addressPicker.setAddressText(address)
 this.refs.addressPicker undefined, any idea why?

It will be great to have initial search text, as simple as that.

**Comment by myaskevich** [comment]
You may want to use `getDefaultValue` prop:

```js
getDefaultValue={() => {
  return ''; // text input default value
}}
```

**Comment by myaskevich** [comment]
Please also take a look at the example https://github.com/FaridSafi/react-native-google-places-autocomplete#example
