### ISSUE TITLE
Does not work in version 2.0.0

### ISSUE THREAD

**Issue by rafaelsevla** [FaridSafi/react-native-google-places-autocomplete#634]
I upgraded the library from version 1.9.0 to 2.0.3 and just don't find any more places when I type some text in the input
I saw the changelog and there was no change from one version to the other that asks me to change something in the code

my use is nothing more than that 👇

```
<GooglePlacesAutocomplete
      placeholder='Search'
      onPress={(data, details = null) => {
        // 'details' is provided when fetchDetails = true
        console.log(data, details);
      }}
      query={{
        key: 'YOUR API KEY',
        language: 'en',
      }}
    />
```

# Additional context

- React Native Version: [0.63.3]

- [x] iOS
- [x] Android
- [ ] Web

**Comment by bell-steven** [comment]
Can you confirm you are on version 2.03 and not 2.0.0 or 2.0.1?  I can't reproduce your issue.

**Comment by rafaelsevla** [comment]
@bell-steven yes.. was version 2.0.3
I clean cache and works kkkkk sorry

**Comment by bell-steven** [comment]
No worries. Figured that was the issue...
