### ISSUE TITLE
Module Not Found Bug 

### ISSUE THREAD

**Issue by acexode** [FaridSafi/react-native-google-places-autocomplete#635]
# Module not found: Can't resolve 'react-native-web/dist/exports/ActivityIndicator'

Module not found: Can't resolve 'react-native-web/dist/exports/ActivityIndicator' in 'C:\Dev\React Native\taxi\node_modules\react-native-google-places-autocomplete'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'

- [ *] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by bell-steven** [comment]
Closing. No reproduction.
