### ISSUE TITLE
Get geolocation

### ISSUE THREAD

**Issue by esganzerla** [FaridSafi/react-native-google-places-autocomplete#64]
I'm trying to get the geolocation for the selected place, but it seems I'm not receiving it.

Can anyone give me a help with that?

Thanks!

**Comment by myaskevich** [comment]
Hi @esganzerla 

Sure!

Please paste in some code here ;)

**Comment by esganzerla** [comment]
I'm doing the same way I do online with javascript, and the API return seems just ok, except that it's not returning the geolocation for the place I'm setting.

Anyway, the way I'm doing is this:

```javascript
            <GooglePlacesAutocomplete
             enablePoweredByContainer={false}
             autoFocus={true}
             onPress={(data1, data2) => { alert(JSON.stringify(data2, null, '\t')); this.setState({ modal: false }) } }
             query={{
                key: '...',
                language: 'pt',
                types: '(cities)',
                components: 'country:br'
             }}
            />
```

**Comment by esganzerla** [comment]
Seems it was solved by including the ```fetchDetails={true}``` parameter.

Thanks!
