### ISSUE TITLE
ref,current.blur() not working

### ISSUE THREAD

**Issue by haris523** [FaridSafi/react-native-google-places-autocomplete#641]
# Describe the bug

blur method doesn't even exist in the ref object

# Reproduction - (required - issue will be closed without this)

![image](https://user-images.githubusercontent.com/33039018/96861370-47dec900-1464-11eb-9e45-ef3dc9d5cc0c.png)

**Comment by spyshower** [comment]
Can confirm

**Comment by bell-steven** [comment]
@haris523 @spyshower can you confirm if #650 fixes this for you?
