### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by lokomass** [FaridSafi/react-native-google-places-autocomplete#645]
Hi,
How can we use Google Maps restriction key please ?

**Comment by bell-steven** [comment]
Short answer, no.  It is in the [README](https://github.com/FaridSafi/react-native-google-places-autocomplete#compatibility).

https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/612#issue-690357980 is a clever solution if you are concerned.
