### ISSUE TITLE
Feature Request  - Custom Current Location Button

### ISSUE THREAD

**Issue by QuintonC** [FaridSafi/react-native-google-places-autocomplete#646]
**Is your feature request related to a problem? Please describe.**

No, this is a new feature request only aimed at enhancing the component. I'd like to have the ability to customize the Current Location button. 

**Describe the solution you'd like**

E.g:

```
currentLocationButtonStyle={styles.myCustomButton}
currentLocationButtonContent={() => return (
    {customButtonContentHere}
)}
```

**Describe alternatives you've considered**

I've not considered any alternatives aside from not using the current location feature.

**Additional context**

I'd like to be able to add icons to the custom location button (e.g. FontAwesome Location Icon), as well as being able to customize the appearance (style) of the button.

**Comment by bell-steven** [comment]
You should be able to do this with the render row prop. 

Similar to https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/484#issuecomment-631220610
```js
<GooglePlacesAutocomplete
      query={{
        key: GOOGLE_PLACES_API_KEY,
        language: 'en', // language of the results
        }}
      renderRow={results => {
        if (results.isPredefinedPlace) { // log to see what results returns, but I believe it has an isCurrentLocation property 
          return (
            <>
              <Image source="https://i.ya-webdesign.com/images/transparent-pin-google-2.png" style={{ width: 15, height: 25 }} />
              <Text>{results.description}</Text>
            </>
          );
        } else {
          return <Text>{results.description}</Text>
        }  
      }}	
      onPress={(data, details = null) => console.log(data)}
/>
```

**Comment by bell-steven** [comment]
Closing, because this can already be done.
