### ISSUE TITLE
How to return current location?

### ISSUE THREAD

**Issue by wafisher** [FaridSafi/react-native-google-places-autocomplete#65]
Given the lack of explicit documentation, I would _expect_ that when a user clicks on the Current Location item, the module would return, calling `this.props.onPress`, just like it does with predefined and autocomplete'd rows. Instead what [happens](https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L373) is that it refreshes the list with new data.

I don't get this. Isn't the user clicking on Current Location to use that as the "place"? More to the point, how can I get the module to do what I want — should I just fork the project and use my own version or perhaps, if you like this functionality, I could write it in a way suitable to be incorporated.

**Comment by myaskevich** [comment]
Hi @wafisher 

You can set `currentLocation={false}` and add YOUR current location to the list of `predefinedPlaces` prop.

**Comment by wafisher** [comment]
I ended up forking the module and modifying it. Thank you.
