### ISSUE TITLE
How to restrict the google key?

### ISSUE THREAD

**Issue by dftaher** [FaridSafi/react-native-google-places-autocomplete#652]
# Describe the problem

If I restrict the google key to ios/android specific namespace or build, then the API request would not work unless I open the key for all requests. Can you guide me how to restrict my key for my apps?

**Comment by bell-steven** [comment]
As stated in the readme, the library is not compatible with a restricted key.

https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/612#issue-690357980 has a clever workaround. 
![image](https://user-images.githubusercontent.com/13405567/98557717-8d780000-2272-11eb-951d-7e1e2476c020.png)

**Comment by dftaher** [comment]
thank you
