### ISSUE TITLE
Multiline behaviour

### ISSUE THREAD

**Issue by BayCo** [FaridSafi/react-native-google-places-autocomplete#657]
How we can achieve the same behaviour of TextInput multiline prop, using custom input?

**Comment by bell-steven** [comment]
Have you tried
```
...
textInputProps={{
        InputComp: Input,
        multiline: true
 }}
...
```

**Comment by BayCo** [comment]
@bell-steven yeah, that approach is working, later i discovered that documentation was updated about custom input, thanks

**Comment by sleekLancelot** [comment]
> Have you tried
> 
> ```
> ...
> textInputProps={{
>         InputComp: Input,
>         multiline: true
>  }}
> ...
> ```
> 
> All of the `textInputProps` get passed to the TextInput. If the Input component supports a prop, you can put it in `textInputProps`.

Not sure this works anymore. Didn't work for me, although i use the default input
