### ISSUE TITLE
@bell-steven CUSTOM TEXT INPUT - Suggested solution is not what was being asked in the original question.

### ISSUE THREAD

**Issue by yugalkishoregoyal** [FaridSafi/react-native-google-places-autocomplete#658]
@bell-steven Suggested solution is not what was being asked in the original question.

1) When we are trying to use the Custom Text Input Component using textInputProps prop, it is no more loading the list view, no matter what the component styling is. It is also not triggering the OnFocus and Other Input Methods.

I'm referring to this code here.

`
                    <GooglePlacesAutocomplete
                      placeholder="Type your location..."
                      query={{
                        key: GOOGLE_PLACES_API_KEY,
                        language: 'en',
                      }}
                      textInputProps={{
                        InputComp: TextInput,
                        // props for TextInput go here
                        onChangeText: (text) => text,
                        clearButtonMode: 'always',
                      }}
                    />
`

2) When using the Styling for the default Text Component, when can not set Text Input Header or any icon. Now in our case, Let's say I want to use Text Input Header as Start / Destination or Use the Icons on Left/Right Sides.

Please suggest if this library supports custom Text Input or should we plan to build something from scratch using Google's REST APIs.

Thanks.

_Originally posted by @yugalkishoregoyal in https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/571#issuecomment-725890240_

**Comment by bell-steven** [comment]
Please do not spam the issues.
