### ISSUE TITLE
@display full address in listView

### ISSUE THREAD

**Issue by AkiraY523** [FaridSafi/react-native-google-places-autocomplete#66]
Hi,

I can't get full address in listView.
How can I get it via this package?
Thank you

**Comment by myaskevich** [comment]
@AkiraY523 

Full address should be returned by default. Can you paste in a screenshot describing what you see?

You can customize list view item by providing custom `renderDescription` or `renderRow` props.

**Comment by AkiraY523** [comment]
Hi myaskevich,

Thank you for your interesting for me.
As you let me know, the reason is that I used it as following code.

***************
renderDescription={(row) => {row.terms[0].value; }} 

So I rewrite like this, I solved this issue
***************
renderDescription={(row) => row.description}

Thanks myaskevich.
