### ISSUE TITLE
Autocomplete - list of items are not selectable - expo

### ISSUE THREAD

**Issue by rudsonramon** [FaridSafi/react-native-google-places-autocomplete#667]
# Describe the problem

I implemented the google places autocomplete, to search some address, but when I try to select one suggestion it is not working. Do you know how to fix or make an workaround? https://stackoverflow.com/questions/65031936/expo-google-places-autocomplete-listview-not-clicable
# Reproduction - (required - issue will be closed without this)

- [ ] iOS
- [X] Android
- [ ] Web

If you are using expo please indicate here:

- [X] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by bell-steven** [comment]
Please follow the issue template and provide a full reproduction.
