### ISSUE TITLE
Warning from passing listViewDisplayed={true} 

### ISSUE THREAD

**Issue by Hatko** [FaridSafi/react-native-google-places-autocomplete#668]
# Describe the bug

The types from `GooglePlacesAutocomplete.d.ts` define `listViewDisplayed` as `listViewDisplayed?: 'auto' | boolean;`. When `true` is supplied, we get the warning `Warning: Failed prop type: Invalid prop `listViewDisplayed` of value `true` supplied to `ForwardRef`, expected one of ["auto",null].`

# Reproduction - (required - issue will be closed without this)

1. Install the library
2. Render `GooglePlacesAutocomlete` with `listViewDisplayed={true}` like this:

```
<GooglePlacesAutocomplete
        placeholder='City, street or gym'
        keyboardShouldPersistTaps={'handled'}
        listUnderlayColor={'transparent'}
        minLength={1}
        listViewDisplayed={true} // Here is the line
        fetchDetails={true}
        renderDescription={row => row.description}
        query={{
          key: googleAPIKey,
          language: 'en',
        }}
        nearbyPlacesAPI='GooglePlacesSearch'
        GooglePlacesSearchQuery={{
          rankby: 'distance',
          types: 'gym',
        }}
        // currentLocation={true}
        currentLocationLabel='Current location'
        filterReverseGeocodingByTypes={['locality', 'administrative_area_level_3']}
        debounce={200}
      />
```

# Additional context

- Library Version: "react-native-google-places-autocomplete": "2.1.1",
- React Native Version: [e.g. 0.63.3]

- [x] iOS
- [ ] Android
- [ ] Web

**Comment by bell-steven** [comment]
I am not very proficient at typescript. Would you be willing to put in a PR?

**Comment by Aryk** [comment]
It's not related to typescript...TS doesn't throw errors....its related to PropTypes
