### ISSUE TITLE
[Help] GoogleAutoComplete avoid keyboard

### ISSUE THREAD

**Issue by devbriguy** [FaridSafi/react-native-google-places-autocomplete#67]
Hi @FaridSafi great component. I have the component inside a form in a ListView. I am wanting to push the component above the keyboard on iOS. I've tried using the KeyboardAvoidingView with no luck. Any advice on accomplishing this? Thanks

react-native 0.35.0
react-native-google-places-autocomplete 1.2.6

**Comment by myaskevich** [comment]
hi @devbriguy 

You can try https://github.com/Andr3wHur5t/react-native-keyboard-spacer

Anyway, feel free to paste in some code here, maybe we'll figure it out ;)

**Comment by devbriguy** [comment]
Hi @myaskevich 

I tried that but did not get desired results. It helps to fix the view layout but does not push the TextInput above the keyboard. 

I'd like to get a ref of the TextInput inside this component. Perhaps a prop onFocus?

**Comment by raziboy939** [comment]
@devbriguy I am having a similar issue and agree that an onFocus prop would be magnificent!

**Comment by devbriguy** [comment]
Hi @raziboy939 

I know this is delayed but in case you are still stuck. I figured it out by using `ref` of the googleautocomplete component. Then use scroll responder:

```javascript
  scrollToResponder(ref, offset) {
    var self = this
    setTimeout(() => {
      if (self.scrollView != null) {
        self.scrollView.getScrollResponder().scrollResponderScrollNativeHandleToKeyboard (
          findNodeHandle(ref), // import {findNodeHandle} from 'react-native'
          offset,
          true
        )
      }
    }, 15)
  }
```

**Comment by ademcan** [comment]
Hi @devbriguy, I would like to fo the same thing, but I cannot get it to work.
Could you please give some more details about how to do that? Thank you very much.

**Comment by devbriguy** [comment]
Hi @ademcan I actually abandon usage I mentioned earlier. I actually went on to use [KeyboardAwareScrollView](https://github.com/APSL/react-native-keyboard-aware-scroll-view) as it was cleaner and handled this use case without all the hassle of managing the ref and ScrollView. Hope this helps.

```javascript
<KeyboardAwareScrollView extraScrollHeight={75}>
<GooglePlacesAutocomplete /> 
</KeyboardAwareScrollView>

**Comment by ademcan** [comment]
Oh, thank you @devbriguy , very nice solution, I really appreciate your help. I got the result I was looking for by changing extraScrollHeight to extraHeight.
