### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by rainst** [FaridSafi/react-native-google-places-autocomplete#670]
# Describe the bug

I'm using this component inside a modal view, it can search, display the results but the `onPress` event is not firing when I press any of the results, I have been looking for solutions on google but it appears none are working for me

# Reproduction - (required - issue will be closed without this)

I think my implementation is pretty basic, the component is able to search but when i tap on any of the results the listview closes but the onpress function is not called.
Note that `Screen` is just a SafeAreaView that wraps all my apps screens, I tried removing it from the component and it's still not working

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click to expand!</summary>
  
  ```javascript
  
import React from "react";
import { Modal, View } from "react-native";
import { GooglePlacesAutocomplete } from "react-native-google-places-autocomplete";
import Button from "./Button";
import Screen from "./Screen";

type Props = {
  isVisible: boolean;
  onClose: () => void;
  countryCode?: string;
};

const AddressAutocompleteModal: React.FC<Props> = ({
  isVisible,
  onClose,
  countryCode = ""
}) => {
  return (
    <Modal visible={isVisible} style={{ backgroundColor: "#eee" }}>
      <Screen style={{ backgroundColor: "yellow" }}>
        <Button label="Close" onPress={onClose} kind="dark" />
        <View style={{ flex: 1, backgroundColor: "red" }}>
          <GooglePlacesAutocomplete
            placeholder="Search"
            onPress={(res) => {
              console.log("pressed", res);
            }}
            query={{
              key: "abcd",
              language: "en",
              components: countryCode ? `country:${countryCode}` : undefined
            }}
            enablePoweredByContainer={false}
          />
        </View>
      </Screen>
    </Modal>
  );
};

export default AddressAutocompleteModal;

    
  ```
</details>

_Please remember to remove you google API key from the code you provide here_

# Additional context

- Library Version: 2.1.1
- React Native Version: 0.63.2

- [X] iOS
- [ ] Android
- [ ] Web

If you are using expo please indicate here:

- [X] I am using expo

I am using managed expo (SDK 39, the latest)

screenshot of the ios simulator and the javascript console with no logs :(
![Screen Shot 2020-11-30 at 10 59 21 am](https://user-images.githubusercontent.com/1917543/100557139-1e367e80-32fb-11eb-8a97-0dd74f3075bb.png)

**Comment by ErnestGrey** [comment]
Also having the same issue with `onPress` not firing while wrapped in a `Modal`.

**Comment by ErnestGrey** [comment]
> Also having the same issue with `onPress` not firing while wrapped in a `Modal`.

Actually found my issue. I was using a third party component that wrapped my `<GooglePlacesAutocomplete>` component and didn't realize it inherited from a `ScrollView`. Setting `keyboardShouldPersistTaps="always"` on that third party component did the trick. 

I don't know what's in your `Screen` component but if there is a parent scroll view anywhere in the hierarchy make sure that prop is set.

**Comment by rainst** [comment]
Hi thanks for pointing that out..
Eventually I wrote my own component to do the query, so going back now to check what was wrong after 3 weeks on commits doesn't make sense.. :) 

I'm closing this issue

**Comment by komod0** [comment]
@ErnestGrey Thanks!, had the same issue when using the component inside a Modal or a react-native-elements Overlay, setting the `keyboardShouldPersistTaps="always"` did the trick

**Comment by dinakar17** [comment]
It's better to write your component instead of relying on the library. I've written the following to replace the library:

import React, { useState, useEffect } from 'react';
import { View, Text, TextInput, TouchableOpacity, ActivityIndicator, FlatList, Modal } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';

interface Location {
  address: string;
  latitude: number;
  longitude: number;
}

interface LocationPickerProps {
  visible: boolean;
  onClose: () => void;
  onSelect: (location: Location) => void;
}

interface PlacePrediction {
  place_id: string;
  description: string;
  structured_formatting: {
    main_text: string;
    secondary_text: string;
  };
}

const LocationPicker = ({ visible, onClose, onSelect }: LocationPickerProps) => {
  const [searchText, setSearchText] = useState('');
  const [predictions, setPredictions] = useState<PlacePrediction[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!visible) {
      setSearchText('');
      setPredictions([]);
      setError(null);
    }
  }, [visible]);

  const searchPlaces = async (query: string) => {
    if (!query.trim()) {
      setPredictions([]);
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const response = await fetch(
        `https://maps.googleapis.com/maps/api/place/autocomplete/json?input=${encodeURIComponent(
          query
        )}&components=country:in&key=${process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY}`
      );

      const data = await response.json();
      console.log('Places API response:', data);

      if (data.status === 'OK') {
        setPredictions(data.predictions);
      } else {
        setError('Failed to fetch locations. Please try again.');
        setPredictions([]);
      }
    } catch (err) {
      console.error('Error fetching predictions:', err);
      setError('Something went wrong. Please check your connection.');
      setPredictions([]);
    } finally {
      setLoading(false);
    }
  };

  const getPlaceDetails = async (placeId: string) => {
    try {
      const response = await fetch(
        `https://maps.googleapis.com/maps/api/place/details/json?place_id=${placeId}&fields=formatted_address,geometry&key=${process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY}`
      );

      const data = await response.json();
      console.log('Place Details response:', data);

      if (data.status === 'OK' && data.result) {
        const location: Location = {
          address: data.result.formatted_address,
          latitude: data.result.geometry.location.lat,
          longitude: data.result.geometry.location.lng,
        };
        onSelect(location);
        onClose();
      } else {
        setError('Failed to get location details. Please try again.');
      }
    } catch (err) {
      console.error('Error fetching place details:', err);
      setError('Failed to get location details. Please try again.');
    }
  };

  return (
    <Modal
      visible={visible}
      animationType="slide"
      transparent={true}
      onRequestClose={onClose}
    >
      <View className="flex-1 bg-[#0B0F18]/95">
        <View className="flex-1 mt-20">
          {/* Header */}
          <View className="flex-row justify-between items-center px-4 mb-4">
            <Text className="text-white text-lg font-semibold">Select Location</Text>
            <TouchableOpacity onPress={onClose}>
              <MaterialIcons name="close" size={24} color="white" />
            </TouchableOpacity>
          </View>

          {/* Search Input */}
          <View className="px-4 mb-4">
            <View className="flex-row items-center bg-[#1C2237] rounded-xl px-4">
              <MaterialIcons name="search" size={20} color="#818CF8" />
              <TextInput
                className="flex-1 py-4 px-2 text-white"
                placeholder="Search for a location"
                placeholderTextColor="#4B5563"
                value={searchText}
                onChangeText={(text) => {
                  setSearchText(text);
                  searchPlaces(text);
                }}
                autoFocus
              />
              {loading && <ActivityIndicator size="small" color="#818CF8" />}
            </View>
          </View>

          {/* Error Message */}
          {error && (
            <View className="mx-4 mb-4 p-4 bg-red-500/20 rounded-xl">
              <Text className="text-red-500">{error}</Text>
            </View>
          )}

          {/* Results */}
          <FlatList
            data={predictions}
            keyExtractor={(item) => item.place_id}
            contentContainerStyle={{ padding: 16 }}
            ItemSeparatorComponent={() => (
              <View className="h-[1px] bg-[#2D3748] my-2" />
            )}
            renderItem={({ item }) => (
              <TouchableOpacity
                className="py-3"
                onPress={() => getPlaceDetails(item.place_id)}
              >
                <View className="flex-row items-start">
                  <MaterialIcons name="location-on" size={20} color="#818CF8" />
                  <View className="flex-1 ml-2">
                    <Text className="text-white text-base">
                      {item.structured_formatting.main_text}
                    </Text>
                    <Text className="text-gray-400 text-sm mt-1">
                      {item.structured_formatting.secondary_text}
                    </Text>
                  </View>
                </View>
              </TouchableOpacity>
            )}
          />
        </View>
      </View>
    </Modal>
  );
};

export default LocationPicker;
