### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by cojoc07** [FaridSafi/react-native-google-places-autocomplete#680]
# Describe the bug

Wherever I try to use GooglePlacesAutocomplete, I get a the error below, even without searching for anything. Results appear to be retrieved successfully though:

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
- node_modules\react-native\Libraries\LogBox\LogBox.js:173:8 in registerError
- node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
- node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
- node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:106:4 in printWarning
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:75:16 in error
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19152:9 in warnAboutUpdateOnUnmountedFiberInDEV
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17093:40 in scheduleUpdateOnFiber
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:11003:16 in dispatchAction
* [native code]:null in dispatchAction
- node_modules\react-native-google-places-autocomplete\GooglePlacesAutocomplete.js:522:6 in _request
- node_modules\lodash.debounce\index.js:159:21 in invokeFunc
- node_modules\lodash.debounce\index.js:206:20 in trailingEdge
- node_modules\lodash.debounce\index.js:194:20 in timerExpired
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:383:16 in callTimers
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

# Reproduction - (required - issue will be closed without this)

Steps to reproduce the behavior - a minimal reproducible code example, link to a [snack](https://snack.expo.io) or a repository.

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click to expand!</summary>
  
I am using it inside a view but using it directly has the same effect.

  <View style={{ width: "100%", height: 300 }}>
        <GooglePlacesAutocomplete
          placeholder="Search"
          onPress={(data, details = null) => {
            // 'details' is provided when fetchDetails = true
            console.log(data, details);
          }}
          query={{
            key: "mykey",
            language: "en",
          }}
        />
      </View>
    
    
  ```
</details>

_Please remember to remove you google API key from the code you provide here_

# Additional context

- Library Version: 2.1.2
- React Native Version: 0.63.2

- [ ] iOS
- [X] Android
- [ ] Web

If you are using expo please indicate here:

- [X] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by bell-steven** [comment]
Cannot reproduce.

**Comment by mak12** [comment]
Were u able to fix this? @stcojo  i am facing this issue too
