### ISSUE TITLE
Example doesn't give results with working key

### ISSUE THREAD

**Issue by fabyeah** [FaridSafi/react-native-google-places-autocomplete#682]
# Describe the problem

Nothing happens in my app when I type in the search field, so I tested the provided example snack: https://snack.expo.io/@sbell/react-native-google-places-autocomplete with an unrestricted key, billing enabled, Google Places API enabled. No results. Console shows the following errors upon loading the example snack (no further errors when typing into the search field):

<img width="393" alt="Screenshot 2021-01-05 at 17 05 29" src="https://user-images.githubusercontent.com/4738527/103669747-06e15580-4f79-11eb-962c-68246ea71c2e.png">

<img width="547" alt="Screenshot 2021-01-05 at 17 20 21" src="https://user-images.githubusercontent.com/4738527/103671159-d6022000-4f7a-11eb-866c-2f891f7c802a.png">

<img width="456" alt="Screenshot 2021-01-05 at 17 20 49" src="https://user-images.githubusercontent.com/4738527/103671197-e0bcb500-4f7a-11eb-88c1-207bfeb9dd5b.png">

<img width="843" alt="Screenshot 2021-01-05 at 17 25 19" src="https://user-images.githubusercontent.com/4738527/103671434-32653f80-4f7b-11eb-8f2b-73f847df8347.png">

Feel like I'm crazy, as all others with no results seem to have had a problem with their key, and I don't know how there can still be a problem with my key...   😟

# Reproduction - (required - issue will be closed without this)

Go to https://snack.expo.io/@sbell/react-native-google-places-autocomplete, put in your key and try to search.

**Comment by fabyeah** [comment]
I could not get this to work. I have since switched to `react-native-google-places` which works for me with the same key. 🤷🏻‍♂️

**Comment by daee-kang** [comment]
I couldn't get this to work, I used the onFail prop to see if it was failing but it wasn't failing at all. Manually entering the api link for autocomplete gives me proper json results but for some reason i can't show results here.

**Comment by bell-steven** [comment]
The snack was broken. I updated it.
