### ISSUE TITLE
Search result disappeared when close keyboard.

### ISSUE THREAD

**Issue by llfk** [FaridSafi/react-native-google-places-autocomplete#685]
I put a header by using renderHeaderComponent, so due to it, I can't see search results on the small phone because they are behind a keyboard. When I close the keyboard, the result disappeared, so I can't select anything.
How can I keep the search result even if I close the keyboard?

**Comment by doctorrokter** [comment]
The same issue with me. 

# Describe the bug
While text input is focused (keyboard visible) - search results are visible. Once text input blurs (keyboard hides) - search results erases from screen.

# Reproduction - (required - issue will be closed without this)
- Provide custom `renderDescription` function to `GooglePlacesAutocomplete` field.
- Type request to the input.
- See scrollable suggestion list.
- Tap `return` (or `done`) button on `Keyboard` (iOS) to hide keyboard and blur the field.
### Expected result
- Result list should be visible and user able to select an item
### Actual result
- Result list hides as Keyboard hides

# My look and feel
We want to provide custom large items
![image](https://user-images.githubusercontent.com/8337018/108532690-26de9580-72e9-11eb-832c-aa8e4f450653.png)

**Comment by bell-steven** [comment]
Would you be willing to put in a PR?

**Comment by rmn183** [comment]
Facing same issue, pls resolve it

**Comment by bell-steven** [comment]
@rmn183 please do not spam the issues.  
This is an open-source library. You are more than welcome to propose a solution and submit a PR.

**Comment by jordangrant** [comment]
Assuming we have similar issues, keyboardShouldPersistTaps={'handled'}  on my parent ScrollView did the trick

**Comment by vizFlux** [comment]
Having the same issue in `"react-native-google-places-autocomplete": "^2.2.0",`

**Comment by rmn183** [comment]
> @rmn183 please do not spam the issues.
> This is an open-source library. You are more than welcome to propose a solution and submit a PR.

Will look for it

**Comment by rmn183** [comment]
> Having the same issue in `"react-native-google-places-autocomplete": "^2.2.0",`

Hi, don't customize your rowDescription method!

**Comment by doctorrokter** [comment]
Cloned that repo in order to make a fix, but looks like fix already exists. There is a new boolean prop `keepResultsAfterBlur` which should do the trick (I have the same solution in my app `patch`). But version from npm has no such property. Repo master version and version in npm the same - `2.2.0`.

![image](https://user-images.githubusercontent.com/8337018/115993200-6e7be900-a5da-11eb-9562-adb1a1a72254.png)

Will continue to use local patch, until that flag will appear in npm :)

**Comment by xaviserrag** [comment]
Any news on this? I updated to the last version and `keepResultsAfterBlur` still doesn't do the trick

**Comment by bell-steven** [comment]
`keepResultsAfterBlur` is part of `v2.3.0`, which was just published.
