### ISSUE TITLE
Feature does not meet requirements for background location access

### ISSUE THREAD

**Issue by dhavaljardosh** [FaridSafi/react-native-google-places-autocomplete#688]
# Problem:
Can't publish on Google Play Store with their Google Play Policies

# Reproduction
If we try to publish this application and wait for 2 days, we will get this message from them.
> Your app is not compliant with Google Play Policies

<img width="749" alt="Screen Shot 2021-01-22 at 3 59 37 AM" src="https://user-images.githubusercontent.com/18078687/105476489-4f319080-5c66-11eb-95fc-dde40abbefeb.png">

# Questions:
1. Can we remove the "LOCATION IN BACKGROUND" request from the package somehow?
2. If not, how can we overcome this problem? Our app don't use the location too much at the moment, but it's a required addition.

**Comment by bell-steven** [comment]
Hi, 
Are you sure that this package is the source of this?  This is a pure JS package, and we don't request any permissions.

**Comment by dhavaljardosh** [comment]
Yes it has to be this one.
As apart from this I don't have any other package which is asking for location.

Also why I think it's this is, when I start typing the suggested locations are from my nearby location.

**Comment by bell-steven** [comment]
The package does not have an android manifest file. Google uses your IP address to show you nearby places. Can you point to a place in the code where we are requesting permission?  We would ask for _current_ location, not _background_ location...

**Comment by dhavaljardosh** [comment]
Let me do a quick check.

**Comment by bell-steven** [comment]
@dhavaljardosh did you find the issue?

**Comment by dhavaljardosh** [comment]
Yes I found the issue, I had to manually provide the permissions as Expo by default provides ALL the permissions.

So I think this isn't an issue because of this package, but configuration with expo itself.
