### ISSUE TITLE
Timeout on android

### ISSUE THREAD

**Issue by scerelli** [FaridSafi/react-native-google-places-autocomplete#69]
It seems that android has some problems while getting current position. iOS has no problems but android goes in timeout.

**Comment by shraddha1704** [comment]
I am facing the same issue

**Comment by myaskevich** [comment]
@scerelli @shraddha1704 see https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/70

**Comment by Grundmanis** [comment]
i have the same issue, but when i end typing any address
