### ISSUE TITLE
returnKeyType does not work

### ISSUE THREAD

**Issue by hugoh59** [FaridSafi/react-native-google-places-autocomplete#691]
adding returnKeyType={'go'} prop to GooglePlacesAutocomplete does not do anything.

```
<GooglePlacesAutocomplete
          returnKeyType={'next'}
...
```

**Comment by bell-steven** [comment]
This was moved in [v2](https://github.com/FaridSafi/react-native-google-places-autocomplete/releases/tag/v2.0.0) to `textInputProps`. 

In the future, please follow the issue template. Knowing which version you are on etc would have been helpful.

**Comment by FraserMuir** [comment]
Would be good to update the readme props definition table to reflect v2 breaking changes
