### ISSUE TITLE
use Back-end to secure apiKey

### ISSUE THREAD

**Issue by lokomass** [FaridSafi/react-native-google-places-autocomplete#692]
# Describe the problem

Actually, there is no way to use restriction API Key.
My first idea to limit problem is get API Key by fetch at the app launch.
But a user man in the middle can get request and decode api key...
So I have a question.

My idea is to use my back-end to request google maps autocomplete.
Instead of request to googlemaps.api..., request to my back-end.
On my back, I check user is logged, and I do the request, and I return response to user autenticated.
The problem is, my request is twice : RN => backend => googlemaps api

# Additional context

- Library Version: [2.1.3]
- React Native Version: [0.63.2]

- [X ] iOS
- [X ] Android
- [ ] Web

If you are using expo please indicate here:

- [X ] I am using expo

**Comment by bell-steven** [comment]
If you use this library, you can either proxy your requests or not use a restricted key.

I suggest you look for a library that uses the native Google Maps SDKs. The only one that I know of is [react-native-google-places](https://github.com/tolu360/react-native-google-places).

**Comment by lokomass** [comment]
Thanks for your reply.
I'm using managed Expo so I can't use this library...

**Comment by bell-steven** [comment]
These are the limitations of the library, as stated in the README [here](https://github.com/FaridSafi/react-native-google-places-autocomplete#compatibility).

**Comment by lokomass** [comment]
Yes I've seen
Finally I have created my own API on my backend with restricted key IP.
And I have created a simple component with flatlist.
It's secure
