### ISSUE TITLE
Ask permission from user for current location

### ISSUE THREAD

**Issue by Debarshi-Chaudhuri** [FaridSafi/react-native-google-places-autocomplete#693]
![Screenshot_20210212_172428](https://user-images.githubusercontent.com/52458702/107765282-8b34ae80-6d57-11eb-9ded-a72295996e34.jpg)

If my app does not have location access initially.
Now on pressing current location, it shows an alert saying location permission not granted.

So can there be a feature where instead of showing an alert, it requests the user to grant location permission when current location is pressed.

Thank You.

**Comment by bell-steven** [comment]
Do you have anything type of implementation in mind? We removed the libraries ability to request location after React Native upgraded to v0.60.

**Comment by Debarshi-Chaudhuri** [comment]
@bell-steven can any kind of prop be provided for passing the functionality to handle the task of requesting permission, because currently I am overriding the method getCurrentLocation and there I am adding the function to request for permission when it fails to get the current location.

```javascript
ref.current?._disableRowLoaders();
    if (
      error?.message === 'Location permission not granted.' ||
      error?.message === 'Location permission denied'
    ) {
      const locationPermission = await handlePermission('location');
      if (!locationPermission) {
        showAlert(
          'Permission',
          'We need your location access permission to access your location'
        );
        return;
      } else {
        getCurrentLocation();
      }
    }
```

**Comment by bell-steven** [comment]
I don't think I would want this to be added into the library. I think that this can be handled outside of the library.
