### ISSUE TITLE
How to add icons on every suggestion result row?

### ISSUE THREAD

**Issue by giovankabisano** [FaridSafi/react-native-google-places-autocomplete#697]
# Problem

I want to customize auto complete suggestion row to be similar with this design (it have `chevron` icon on every row)
<img src="https://user-images.githubusercontent.com/37267184/109636356-10a0c700-7b7e-11eb-8ac5-0aaded0ab823.png" width="300" height="450"/>

Currently, my code already able to show auto-complete suggestions, and I just need to add icon inside the auto-complete suggestion row.
<img src="https://user-images.githubusercontent.com/37267184/109637112-ed2a4c00-7b7e-11eb-8d0b-61d2f1df6c2f.png" width="260" height="450"/>

# Reproduction

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click here to see my code implementation!</summary>
  
  ```javascript
    
    function index({ placeholder, onPress }) {
  return (
    <GooglePlacesAutocomplete
      styles={{
        textInput: {
          height: 40,
          color: "#04070c",
          fontSize: 16,
          borderBottomColor: "#dfe4e8",
          borderBottomWidth: 1,
        },
        predefinedPlacesDescription: {
          color: "#04070c",
        },
        listView: {
          backgroundColor: "#f0f3f5"
        },
        row: {
          paddingVertical: 16,
          flexDirection: 'row',
        },
      }}
      enablePoweredByContainer={false}
      minLength={2}
      debounce={300}
      autoFocus={true}
      placeholder={placeholder}
      onPress={onPress}
      fetchDetails={true}
      query={{
        key: process.env.REACT_APP_XXXXXXXXXXXXXX,
        language: 'id',
        components: 'country:id'
      }}
    />
  )
}

export default index

  ```
</details>

# Additional context

I saw in the documentation that you have `renderRow` property, I've try to use that but I'm sure that I use that wrong.
```
<GooglePlacesAutocomplete
      styles={{
        textInput: {
          height: 40,
          color: "#04070c",
          fontSize: 16,
          borderBottomColor: "#dfe4e8",
          borderBottomWidth: 1,
        },
        predefinedPlacesDescription: {
          color: "#04070c",
        },
        listView: {
          backgroundColor: "#f0f3f5"
        },
        row: {
          paddingVertical: 16,
          flexDirection: 'row',
        },
      }}
      renderRow={(rowData) => {
        <View>
          <Text>{rowData.description}</Text>
          {/* Todo: Add chevron icon here */}
        </View>
      }}
      ...
    />
```
with that code above, it give me blank auto suggestion result
<img src="https://user-images.githubusercontent.com/37267184/109637828-e5b77280-7b7f-11eb-9e93-7a3dabf018dd.png" width="260" height="450"/>

- Library Version: 2.1.1
- React Native Version: 0.63.3

- [ ] iOS
- [X] Android
- [ ] Web

I am NOT USING expo.

I think sample code regarding "how to use renderRow?" is very useful for the one who new to react native like me.

**Comment by bell-steven** [comment]
You aren't returning the <View> in renderRow, that is why the results aren't showing. Otherwise you seem to be on the right track. 

```
...
renderRow={(rowData) => {
        return <View>
          <Text>{rowData.description}</Text>
          {/* Todo: Add chevron icon here */}
        </View>
      }}
...
```

**Comment by giovankabisano** [comment]
Thanks @bell-steven for providing me solution! Yes, it answer my question.
