### ISSUE TITLE
Placeholder color on iphone gen 12

### ISSUE THREAD

**Issue by flmandrei** [FaridSafi/react-native-google-places-autocomplete#708]
# Placeholder color on iphone gen 12 is white and on iphone gen 8 is gray can u help me?
![google auto complete (1)](https://user-images.githubusercontent.com/44380064/112964277-dca2cc80-9150-11eb-89f1-147cd976601d.png)

#Code
```
<GooglePlacesAutocomplete
      ref={inputRef}
      placeholder={placeholder || i18n.placeholders.deliveryAddressPlaceholder}
      fetchDetails={true}
      enablePoweredByContainer={false}
      onPress={onPressAddressRow}
      GooglePlacesDetailsQuery={{
        fields: ['address_components', 'formatted_address']
      }}
      query={{
        key: MAPS_KEY,
        language: 'xxx',
        components: 'country:xxx',
        types: ['address']
      }}
      listUnderlayColor={colors.white}
      styles={{
        textInputContainer: {
          borderColor: colors.brownishGrey,
          borderWidth: 0.4,
          backgroundColor: colors.white,
          borderRadius: 5,
          paddingHorizontal: spacing.xxsmall,
          height: 46,
          fontSize: fontSize.regular,
          marginBottom: spacing.small
        },
        textInput: {
          fontSize: fontSize.regular
        },
        row: {
          borderBottomColor: colors.white
        },
        predefinedPlacesDescription: {
          color: colors.black
        }
      }}
      renderRow={renderRow}
      renderLeftButton={() => renderLeftInputIncon()}
    />
```
# Additional context

- Library Version: [e.g. 2.2.0]
- React Native Version: [e.g. 0.63.3]

- [x] iOS
- [ ] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by EduardoPereiraBoares** [comment]
In android 11 too

**Comment by CristinaCST** [comment]
It is happening to me too. iPhone 12.

**Comment by jretamalc** [comment]
In android 8 and 9 too, is there any other way to modify the placeholder color?

**Comment by coreybrown89** [comment]
@jretamalc you can update the placeholder color by passing in the option to `textInputProps` 

e.g.
```jsx
textInputProps={{
   placeholderTextColor: Colors.primary,
}}
```

Check out the `TextInput` props section for reference to other props you can use. https://reactnative.dev/docs/textinput#props
