### ISSUE TITLE
Can't select search result list on iphone 8 - 14.4

### ISSUE THREAD

**Issue by longman0512** [FaridSafi/react-native-google-places-autocomplete#709]
I am using this component in expo project that is last version now.

It works well on Android but I can't select a list of results.

Please help me.
Thanks

![Screenshot_2](https://user-images.githubusercontent.com/76522588/113968240-5f0b4a80-983b-11eb-981f-369af30a267a.png)

**Comment by bell-steven** [comment]
Please follow the issue template
