### ISSUE TITLE
I doubt about prices for using the Autocomplet and Google Places APi

### ISSUE THREAD

**Issue by luigbren** [FaridSafi/react-native-google-places-autocomplete#710]
friends, I have a question, I was trying this addon and I was quite useful, I only use this addon to get the address and placeid, to use it I had to affiliate my credit card, then I was doing some research and according to the information of the Google platform, they give a credit of 300$ to new users to use them in maximum 90 days, after that period they were going to charge my card, I don't know why but the automatic payment was already configured (I didn't configure it), I am confused because in the pricing information there are parts that say Autocomplet is free of charge (0$) and there are other parts that say Autocomplet has a price according to the requests. . now my question is: the people that are using this add-on, has Google Colud billed them for any charges? Do you have to pay Google to use the Autocomplet of this add-on?

**Comment by dblooman** [comment]
Autocomplete is always charged for, 2.83 for 1000 requests, there is no "free" API, there is only data that is included at no extra cost to requests to certain endpoints.  If you are your app will do a million requests, then i suggest setting a billing alert email once you hit $28, at least then you will know when you hit above what you think is acceptable.

**Comment by RyanMan56** [comment]
@dblooman isn't strictly correct - it's recommended that you include a `sessionkey` in your query prop which is a string that uniquely identifies that session, such as a uuid v4. If you include this, then you won't be charged for the autocomplete requests as long as they're followed by a Place Details request with the same `sessionkey`.

From the billing documentation [here](https://developers.google.com/maps/documentation/places/web-service/usage-and-billing#ac-with-details-session):

> ### SKU: Autocomplete (included with Places Details) – Per Session
>
> An Autocomplete (included with Places Details) – Per Session SKU is charged for an Autocomplete session that includes a Places Details request. The autocomplete request is free, and the subsequent Places Details call gets charged based on regular Places Details pricing (described below).
>
> #### Example
> If your application issues the following three calls in a single session:
>
> Places Autocomplete Request (input=”par”, sessiontoken=”XYZ”)
> Places Autocomplete Request (input=”paris”, sessiontoken=”XYZ”)
> Places Details (place_id=”place_id”, sessiontoken=”XYZ”, fields:formatted_address)
> On your bill, you will see the following SKUs listed (when viewing your bill by SKU):
>
> Autocomplete (included with Places Details) – Per Session (billed at 0.00 USD)
> Places Details (price starting at 0.017 USD per session)
> Basic Data (billed at 0.00 USD)

Even though it doesn't seem to be documented, this library does support it. E.g:

```
<GooglePlacesAutocomplete
    query={{
        key: googlePlacesApiKey,
        language: 'en',
        sessiontoken: '5e8c4cab-e717-45f9-9036-e21d1453389a',
    }}
/>
```

I'm personally using [this package](https://www.npmjs.com/package/uuid) to generate a new uuid every time the component mounts.

**Comment by bell-steven** [comment]
I'm going to close this, as this seems to be resolved.
