### ISSUE TITLE
autoFocus not working

### ISSUE THREAD

**Issue by Dhanraj-Naik** [FaridSafi/react-native-google-places-autocomplete#723]
# autoFocus parameter is not handled inside the package.

Please handle the prop **autoFocus** inside the package also.

# Reproduction 
-Just pass prop **autoFocus** and check if component autofocus .

# Additional context

- react-native-google-places-autocomplete: 2.2.0
- React Native: 0.62.2

- [* ] iOS
- [* ] Android
- [ *] Web
- 
- @FaridSafi please look into this.

**Comment by bell-steven** [comment]
Please provide a reproducible example

**Comment by azhararmar** [comment]
I have one installed in RN 0.61 and the other in 0.64, it works in 0.61 but does not work in 0.64

**Comment by azhararmar** [comment]
Here is what I found out.

This does not work

```
<GooglePlacesAutocomplete
    placeholder='Search'
    autoFocus={true}
/>
```

This works

<GooglePlacesAutocomplete
    placeholder='Search'
    textInputProps={{
        autoFocus={true}
    }}
/>
