### ISSUE TITLE
Can we do something like Google maps on Android?

### ISSUE THREAD

**Issue by filippobarcellos** [FaridSafi/react-native-google-places-autocomplete#727]
Hey guys. I was checking google maps on Android and came across this feature to add the number. I was wondering if it is possible to do something like this with this package? Does any of you have implemented something like this?

https://user-images.githubusercontent.com/56128203/119577294-44247380-bdb2-11eb-81ea-db09521c6606.mov

**Comment by bell-steven** [comment]
This is possible, with a little bit of work.  You would need to check the address in `renderRow` and show the button to add the address. You can then set the input text using `setAddressText` with a `ref`.
Note: `setAddressText` doesn't trigger the search again until another character is typed.
