### ISSUE TITLE
Access to XMLHttpRequest at 'https://maps.googleapis.com/maps/api/place/autocomplete/json

### ISSUE THREAD

**Issue by sandeepvishnu** [FaridSafi/react-native-google-places-autocomplete#729]
Getting CORS exception. Testing on local computer on localhost:19001.

Access to XMLHttpRequest at 'https://maps.googleapis.com/maps/api/place/autocomplete/json?&input

This is how I have implemented it
      <GooglePlacesAutocomplete
        placeholder='Enter Location'
        minLength={6}
        query={{
          key: GOOGLE_PLACES_API_KEY,
          language: 'en', // language of the results
          components: 'country:uk',
          type: "address"
        }}
        onPress={(data, details = null) => console.log(data, details)}
        onFail={(error) => console.error(error)}
        fetchDetails = {true}
        debounce={2000}
        textInputProps={{
            InputComp: Input,
            leftIcon: { type: 'font-awesome', name: 'chevron-left' },
            errorStyle: { color: 'red' },
          }}
        requestUrl={{
          url:
            'https://maps.googleapis.com/maps/api',
          useOnPlatform: 'web',
        }} // this in only required for use on the web. See https://git.io/JflFv more for details.
      />
      
      Please advice if I am doing anything wrong. Thanks

**Comment by bell-steven** [comment]
Please follow the issue template. I am guessing that you are using this on the web. Please see the [Web Support](https://github.com/FaridSafi/react-native-google-places-autocomplete#web-support) section in the readme.
