### ISSUE TITLE
Can we restrict result to specific instead of generic ? 

### ISSUE THREAD

**Issue by ismailkhan89** [FaridSafi/react-native-google-places-autocomplete#730]
*Can we restrict result to specific instead of generic ? **

For example in Austrailia if we are looking for an address it should only show addresses with sepecific name or number 

Burton Street, Cannington WA, Australia    //this is a generic address user don't know where this position actually is so we need to identify a street number as well or a places name on this street . map should not allow to select this kind of specific address.

it should allow addresses like below.
12 Burton Street, Cannington WA, Australia
or 
abc police station, Burton Street, Cannington WA, Australia
or 
ABC Coffee Shop, Burton Street, Cannington WA, Australia

if some has worked on this or any success story kindly share your code example . TIA

**Comment by bell-steven** [comment]
As per the Google Autocomplete [docs](https://developers.google.com/maps/documentation/places/web-service/autocomplete#types), you can't specify more than one _type_ in a query. 
You can try and filter the results manually in `renderRow` depending on your requirements.
