### ISSUE TITLE
Sessiontoken not working for me

### ISSUE THREAD

**Issue by Creik** [FaridSafi/react-native-google-places-autocomplete#737]
# Describe the problem

I am trying to add a sessiontoken in the query, but in the same way it marks each character typed in Google Cloud.

I am new to this library.

How to make it work properly?

# Reproduction - (required - issue will be closed without this)

[snack google-place-autocomplete-test](https://snack.expo.io/@ericgoodgame/google-place-autocomplete)

# Additional context

- Library Version: [2.2.0]
- React Native Version: [0.64.1]
- Uuid: [8.3.2]
- React-native-get-random-values: [1.7.0]

- [x] iOS
- [x] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by bell-steven** [comment]
Sorry for the delay looking into this @Creik.  I just used you snack and it is working for me. 
Just one comment, it looks like you are resetting the sessiontoken after an address is selected. I think that it might defeat the purpose of using a session token altogether. See the docs [here](https://developers.google.com/maps/documentation/places/web-service/autocomplete#sessiontoken). 

P.S. Thanks for creating a model issue - followed the template perfectly, making it quick and easy for me to investigate.

**Comment by bcbcbcbcbcl** [comment]
@bell-steven 
From the docs, it mentioned 
> Once a session has concluded, the token is no longer valid; your app must generate a fresh token for each session. If the sessiontoken parameter is omitted, or if you reuse a session token, the session is charged as if no session token was provided (each request is billed separately).

Could you please clarify why we should not resetting the sessiontoken after an address is selected? Thanks in advance.
