### ISSUE TITLE
Xcode Build

### ISSUE THREAD

**Issue by Pitbi** [FaridSafi/react-native-google-places-autocomplete#74]
Hello,

i have the following error in Xcode when i build to the device or when a try to create an archive:

```
ld: library not found for -lRNGooglePlaces
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is there not a `rnpm link` to do?

Thx.

**Comment by Pitbi** [comment]
Hello,

I'm so stupid... I had this error because I did not have correctly purge an other module.


Sorry

++

**Comment by awhitford** [comment]
@Pitbi How did you fix this?  (I am plagued by this too.) :frowning_face:
