### ISSUE TITLE
How to protect google map key?

### ISSUE THREAD

**Issue by arshidkv12** [FaridSafi/react-native-google-places-autocomplete#740]
I am confused. How to protect api key?

**Comment by prox2** [comment]
use  `react-native-dotenv`

**Comment by IrvingGuerra** [comment]
just use Config.GOOGLE_API_KEY with envirotment variables

**Comment by bell-steven** [comment]
As mentioned in the Readme, you cannot use the 'application restrictions' that google provides in the console. One solution that has been mentioned here a few times is using a proxy server. See #612.
