### ISSUE TITLE
Why i enabled Place API and add API key to my code but there wasn't list suggest from text i input

### ISSUE THREAD

**Issue by Bim1604** [FaridSafi/react-native-google-places-autocomplete#741]
# Describe the problem

A clear and concise description of what you are trying to do and where things are going wrong.

# Reproduction - (required - issue will be closed without this)

Steps to reproduce the behavior - a minimal reproducible code example, link to a [snack](https://snack.expo.io) or a repository.

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click to expand!</summary>
  
  ```javascript
    
    
  ```
</details>

_Please remember to remove you google API key from the code you provide here_

# Additional context

- Library Version: [e.g. 1.4.2]
- React Native Version: [e.g. 0.62.2]

- [ ] iOS
- [x] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by iamabdulhaseeb** [comment]
Did you find any solution?

**Comment by Bim1604** [comment]
> Did you find any solution 
not yet, i'm still find. Do u know how to fix that?

**Comment by dontbmh** [comment]
I have the same issue where I could get the query result successfully through https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522,151.1957362&radius=500&types=food&name=harbour&key=YOUR_API_KEY but not on my iphone simulator.

**Comment by bell-steven** [comment]
Closing, as there is no reproducible code here.
