### ISSUE TITLE
Add a TextInput autoCorrect boolean option

### ISSUE THREAD

**Issue by shellbear** [FaridSafi/react-native-google-places-autocomplete#743]
We should add a `TextInput` `autoCorrect` boolean, so we can control either we want to enable this feature or not.

In some big apps like Instagram, the `autoCorrect` is disabled when adding a Location to a post. 

From now, it's impossible to control this behavior.

**Comment by bell-steven** [comment]
This is configurable through the `textInputProps` prop. It is on by default, and can be disabled.
```js
<GooglePlacesAutocomplete
      placeholder='Search'
      onPress={(data, details = null) => {
        // 'details' is provided when fetchDetails = true
        console.log(data, details);
      }}
      query={{
        key: 'YOUR API KEY',
        language: 'en',
      }}
      textInputProps={{
        autoCorrect: false,
      }}
    />
```
See the React Native [docs](https://reactnative.dev/docs/textinput#autocorrect) for more.
