### ISSUE TITLE
Support for EU not available while it is working for UK   

### ISSUE THREAD

**Issue by MudassirAziz** [FaridSafi/react-native-google-places-autocomplete#748]
Support for EU is not available while it is working for UK  

it is working for UK if you use like

    `<GooglePlacesAutocomplete
        placeholder="Search your address"
        query={{
          key: "",
          language: 'en', // language of the results
          components: 'country:gb',
          fetchDetails:true
        }}
       onPress={(data, details = null) => _handleAddress(data)}
       onFail={(error) => console.error(error)}
    />`

**Comment by bell-steven** [comment]
As per the [Google Places docs](https://developers.google.com/maps/documentation/places/web-service/autocomplete#place_autocomplete_requests), only [2 letter ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
 country codes are supported.  Being that the EU is region and not a country, I doubt google, and in turn this library, will support this anytime soon.
