### ISSUE TITLE
Bug Report - Text input change but dont' show search result

### ISSUE THREAD

**Issue by TuanPhong15** [FaridSafi/react-native-google-places-autocomplete#754]
#  Search bar change the text but don't show a search result

I'm using ref like your example but when the onChangeSearch function trigger, text input in your search bar change likely what I want, but I can't see your search result. No log and bug found I retype this text and then it shows me the result. What I want is search bar show result when text input change both by typing and using ref. Someone have an idea, please help me. Thank you.

<details>
  <summary>Click to expand!</summary>
  
  ```
import SearchBar from 'react-native-paper';

  const onChangeSearch = text => {
    refText.current?.setAddressText(text);

  };
  return (
    <>
        <GooglePlacesAutocomplete
          placeholder="Tìm kiếm địa điểm"
          fetchDetails
          ref={refText}
          onPress={(data, details) => {
           
          }}
          GooglePlacesDetailsQuery={{fields: 'geometry'}}
          query={{
            key: 'xxx',
       
          }}
          textInputProps={{
            InputComp: SearchBar,
             clearButtonMode: 'never',
          }}
          styles={{
            container: styles.searchContainer,
            textInput: {
              height: 38,
              color: 'red',
              fontSize: 12,
            },
          }}
        />
        <Suggest
              detail="abc"
              onPress={() => onChangeSearch('abc')}
              description="xyz"
            />
    </>
    
  ```
</details>

# Additional context

- Library Version: [2.2.0]
- React Native Version: [0.64.2]

- [ ] iOS
- [ ] Android

**Comment by bell-steven** [comment]
Closing this, because there is already an open feature request for this in #654.
