### ISSUE TITLE
Some of the addresses not returning post code in UK

### ISSUE THREAD

**Issue by BerkD145** [FaridSafi/react-native-google-places-autocomplete#757]
Some of the addresses its not returning postal codes in uk. For example  : 251 Menlove Avenue Liverpool ,UK. Some of the addresses only returns first part of the post code. The main problem is that the zip code is not returning.

These are the response i get : 
`[
    {
        "long_name": "251",
        "short_name": "251",
        "types": [
            "street_number"
        ]
    },
    {
        "long_name": "Menlove Avenue",
        "short_name": "Menlove Ave",
        "types": [
            "route"
        ]
    },
    {
        "long_name": "Liverpool",
        "short_name": "Liverpool",
        "types": [
            "postal_town"
        ]
    },
    {
        "long_name": "Merseyside",
        "short_name": "Merseyside",
        "types": [
            "administrative_area_level_2",
            "political"
        ]
    },
    {
        "long_name": "England",
        "short_name": "England",
        "types": [
            "administrative_area_level_1",
            "political"
        ]
    },
    {
        "long_name": "United Kingdom",
        "short_name": "GB",
        "types": [
            "country",
            "political"
        ]
    }
]`

In this one i only get some part of the post code : 
`[
    {
        "long_name": "Wendover Street",
        "short_name": "Wendover St",
        "types": [
            "route"
        ]
    },
    {
        "long_name": "High Wycombe",
        "short_name": "High Wycombe",
        "types": [
            "postal_town"
        ]
    },
    {
        "long_name": "Buckinghamshire",
        "short_name": "Buckinghamshire",
        "types": [
            "administrative_area_level_2",
            "political"
        ]
    },
    {
        "long_name": "England",
        "short_name": "England",
        "types": [
            "administrative_area_level_1",
            "political"
        ]
    },
    {
        "long_name": "United Kingdom",
        "short_name": "GB",
        "types": [
            "country",
            "political"
        ]
    },
    {
        "long_name": "HP11",
        "short_name": "HP11",
        "types": [
            "postal_code_prefix",
            "postal_code"
        ]
    }
]`

When i type that address to google its shows me the post code : 
<img width="712" alt="Screen Shot 2021-09-07 at 10 42 45" src="https://user-images.githubusercontent.com/89341559/132304877-21c8ebc8-dd63-4583-991b-15431b1a405f.png">

 
<details>
  <summary>Click to expand!</summary>
  
  ```
    <GooglePlacesAutocomplete
            placeholder="Search address"
            fetchDetails={true}
            styles={{textInput: styles.textInput}}
            keepResultsAfterBlur={false}
            onPress={(data, details) => {
              onPlaceSelected(data, details);
              props.onClose();
            }}
            renderLeftButton={() => <BackButton />}
            query={{
              key: config.googlePlacesApiKey.key,
              language: 'en',
              type: 'address',
              components: 'country:gb',
            }}
          />
    
  ```
</details>

# Additional context

- Library Version: 2.4.1
- React Native Version: 0.64.1

- [x] iOS
- [x] Android
- [ ] Web

Thanks

**Comment by bell-steven** [comment]
This seems to be limitation of the Google Places API for this particular address.  I checked other addresses in Liverpool and throughout the UK, and they returned the Postal Code appropriately.
Not much can be done on the library end of things here.
