### ISSUE TITLE
Unable to get geometry details in response

### ISSUE THREAD

**Issue by varora1406** [FaridSafi/react-native-google-places-autocomplete#758]
# Describe the bug

Trying to fetch geometry details, but not receiving them.
`GooglePlacesDetailsQuery` prop has the value of `fields: "geometry"`

# Reproduction - (required - issue will be closed without this)

Repo - https://github.com/varora1406/uber-clone
Start the app as per `README` instructions and try selecting any response from search field on top

# Additional context

- Library Version: ^2.4.1
- React Native Version: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz

- [ ] iOS
- [x] Android
- [ ] Web

If you are using expo please indicate here:

- [x] I am using expo

**Comment by bell-steven** [comment]
You left out the `fetchDetails` prop, and you have `details = null`.

https://github.com/varora1406/uber-clone/pull/1
