### ISSUE TITLE
Cannot set the value of `placeholderTextColor`

### ISSUE THREAD

**Issue by scgough** [FaridSafi/react-native-google-places-autocomplete#759]
I want to be able to set a specific colour for `placeholderTextColor` but it doesn't seem to allow this at the moment. 

# The issue:
The placeholder text color doesn't change. 

# Code Example:
```
    <GooglePlacesAutocomplete
        placeholder="MY PLACEHOLDER VALUE"
        ...
        onPress={(data, details = null) => {
          //do stuff
        }}
        query={{
          key: MY_API_KEY,
          language: 'en',
        }}
        styles={styles}
        keyboardShouldPersistTaps="always"
        textInputProps={{
          ...
          placeholderTextColor: {MY_COLOR},
          ...
        }}
      />
```

# Additional context

- Library Version: 2.4.1
- React Native Version: 0.63.3

- [x] iOS

If you are using expo please indicate here:

- [ ] I am using expo

**Comment by staham-punosmobile** [comment]
It works on my setup. I guess there are 2 reasons for this:
- I'm not sure what you meant by `{MY_COLOR}`. Are you using an object with a property named `MY_COLOR` and its value. In that case, just replace it by using `MY_COLOR` value only, so `placeholderTextColor: MY_COLOR`
- You're using a custom input component through `InputComp` that pre-sets the `placeholderTextColor`. In that case, set the `placeholderTextColor` in the custom input component instead.

**Comment by scgough** [comment]
@staham-punosmobile  - apologies , i meant to close this as I sorted it already! It was the former issue. Sorry for the waste of time!
