### ISSUE TITLE
Cant remove text input underline on Android 

### ISSUE THREAD

**Issue by Grundmanis** [FaridSafi/react-native-google-places-autocomplete#76]
Did not found anything in issues and in docs..

**Comment by JesperLekland** [comment]
@Grundmanis simply us the prop `textInputProps={{underlineColorAndroid:'white'}}`

**Comment by Grundmanis** [comment]
@JesperLekland Thanks, it worked!

**Comment by brascene** [comment]
Where can I find other options for textInputProps?
Thanks!

**Comment by myaskevich** [comment]
Hi @brascene 

See https://facebook.github.io/react-native/docs/textinput.html#props

**Comment by brascene** [comment]
Silly me.. 
Thanks!
