### ISSUE TITLE
Getting this error when i start typing in input box- Trying to remove a view index above child count 0

### ISSUE THREAD

**Issue by sandeepkumarmishra354** [FaridSafi/react-native-google-places-autocomplete#760]
When I type a single letter I get the list of places. But as soon as I remove / or add a new letter, app crashes with error- Trying to remove a view index above child count 0.

----------------------------------------------------------
"react": "17.0.2",
"react-native": "0.65.1"

I'm not using Expo.

**Comment by tonydatw** [comment]
Getting this very same error too, it works fine on Expo snack but when i try on my terminal with the very same code, it crashes and shows this error. I'm going crazy. The error for me will show if i try to tap on a location result.

**Comment by bell-steven** [comment]
Can either of you please provide a proper reproduction of this?

**Comment by tonydatw** [comment]
@bell-steven 
"react": "17.0.2",
"react-native": "0.65",
"react-native-gesture-handler": "^1.10.3",
"react-native-reanimated": "2.3.0-alpha.3",
"react-native-google-places-autocomplete": "^2.4.1",

Device: Pixel 3 XL API 29 Android 10

Steps to reproduce:

Enter this code:

```
import * as React from 'react';
import { View, StyleSheet, TextInput } from 'react-native';
import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';

const GOOGLE_PLACES_API_KEY = ''; // never save your real api key in a snack!

const App = () => {
  return (
    <View style={styles.container}>
      <GooglePlacesAutocomplete
        placeholder="Search"
        query={{
          key: GOOGLE_PLACES_API_KEY,
          language: 'en', // language of the results
        }}
        onPress={(data, details = null) => console.log(data)}
        onFail={(error) => console.error(error)}
        requestUrl={{
          url:
            'https://cors-anywhere.herokuapp.com/https://maps.googleapis.com/maps/api',
          useOnPlatform: 'web',
        }} // this in only required for use on the web. See https://git.io/JflFv more for details.
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
    backgroundColor: '#ecf0f1',
  },
});

export default App;

```
After entering 2 or 3 characters, the list of locations will appear. However, if i click on one of them in the emulator, it will do nothing, and after a few trials it will just launch the error. If i select a location with arrows UP and DOWN, the list disappears instantly and also throws this error. 

Android Logcat:

```
2021-09-17 11:14:34.941 1730-3606/? E/ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
2021-09-17 11:14:36.950 1730-3607/? E/ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
2021-09-17 11:14:38.972 1730-3608/? E/ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
2021-09-17 11:14:40.981 1730-3609/? E/ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
2021-09-17 11:14:41.299 1816-1816/? E/netmgr: Failed to open QEMU pipe 'qemud:network': Invalid argument
2021-09-17 11:14:43.001 1730-3610/? E/ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
2021-09-17 11:14:45.022 1730-3611/? E/ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
2021-09-17 11:14:45.866 1822-1822/? E/wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
2021-09-17 11:14:47.045 1730-3612/? E/ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
```
![Screenshot_1631869288](https://user-images.githubusercontent.com/54851722/133758468-a392d6f6-3e06-45f0-973e-bc5ca95894b5.png)

**Comment by piaskowyk** [comment]
Hey, your issue is caused by Reanimated - we are working on a sollituion at this moment - https://github.com/software-mansion/react-native-reanimated/issues/2393

**Comment by piaskowyk** [comment]
Fixed here: https://github.com/software-mansion/react-native-reanimated/pull/2437
Fix will be available in the next release - probably this week.

**Comment by bell-steven** [comment]
Thanks for keeping us updated here @piaskowyk, I really appreciate it!
