### ISSUE TITLE
Storing selected location

### ISSUE THREAD

**Issue by KrisLau** [FaridSafi/react-native-google-places-autocomplete#761]
# Describe the problem
I'm trying to decide on how to store the location that the user selects in my database. I'd rather not store it as a JSON as I would like to be able to easily search for the location. I was thinking that I would be able to use the `place_id` but I have no idea how I would go about querying the location details using that id. Is that possible? 

I'm not sure how I would query any of the locations from the backend. What would be the best way to store this?

# Reproduction - (required - issue will be closed without this)
N/A

# Additional context

- Library Version: 2.4.1
- React Native Version: 0.64.2

- [x] iOS
- [x] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by bell-steven** [comment]
A few options I could think of off the top of my head that could make sense. 

1. Store the place ID.  See which Google APIs we use in the readme [here](https://github.com/FaridSafi/react-native-google-places-autocomplete#a-word-about-the-google-maps-apis).
2. store a json object with only a few keys (e.g. lat, long, formatted_address, place id). You can use the `GooglePlacesDetailsQuery`  prop to specify which fields you want to return from the places api to trim the size of the object.

**Comment by KrisLau** [comment]
@bell-steven I'm kind of partial towards the first option but I guess what I'm confused about is how do I go about interfacing with the Google API in the frontend of react native? Is there a library I should be using to call the API or would I have to figure out how to interface with on my own?

Sorry if these are dumb questions I'm new to React Native haha

**Comment by KrisLau** [comment]
Decided to store the latitude and longitude
