### ISSUE TITLE
Bug Report Search text field is always initial with empty, even when pass textInputProps={{defaultValue: 'inital location description text',}}

### ISSUE THREAD

**Issue by ngocnv** [FaridSafi/react-native-google-places-autocomplete#778]
# Describe the bug

The search text field is always initial with empty , we can not specify a default value to initial 

# Reproduction - (required - issue will be closed without this)

Steps to reproduce the behavior - a minimal reproducible code example, link to a [snack](https://snack.expo.dev/) or a repository.

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click to expand!</summary>
  
  ```javascript
    
    
  ```
</details>

_Please remember to remove you google API key from the code you provide here_

# Additional context

- Library Version: [e.g. 1.4.2]
- React Native Version: [e.g. 0.62.2]

- [ ] iOS
- [ ] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by bell-steven** [comment]
I don't understand what you are trying to achieve here.  See the available [props](https://github.com/FaridSafi/react-native-google-places-autocomplete#props), including `placeholder`.

Please follow the issue template.
