### ISSUE TITLE
Feature Request, show zip code

### ISSUE THREAD

**Issue by jliukai** [FaridSafi/react-native-google-places-autocomplete#781]
**Is your feature request related to a problem? Please describe.**
when searching for a street address ie. "54234 Terrace Lane, South Bend, IN, USA" , it does not return zip code.

A clear and concise description of what the problem is.
Ex. I'm always frustrated when... or I would like the ability to be able to...
i would like to see zip code in the data or details.

**Describe the solution you'd like**
show zip code in response

**Describe alternatives you've considered**
send a fetch request directly curl -L -X GET 'https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJd209nH3SFogRgodxBD62aTk&key=<api key>'

**Additional context**
```
 <GooglePlacesAutocomplete
          placeholder='Search'
          onPress={(data, details = null) => {
                     console.log('data: ', data).    //.  <--- i want to see zip code in there. its not there.
                   console.log('details: ',details)   //.  <--- i want to see zip code in there. its not there.
      }
             query={{
              key: Config.key,
              language: 'en',
              components: 'country:us',
              type: 'geocode'.  // i also tried 'address'
            }}
  />   
```

**Comment by bell-steven** [comment]
Google doesn't return the zipcode in the autocomplete results, however they do return it in place details. if you were to add the `fetchDetails` prop, you would see it where you log 'details'.
