### ISSUE TITLE
Using an api key in frontend is it a good idea ?

### ISSUE THREAD

**Issue by juno-97** [FaridSafi/react-native-google-places-autocomplete#787]
# If I use api key directly in the front end will it not be dangerous ? Idk if some one reverse engineer the app or something ?

so, I enabled api key to use from a specefic domain from google console and google restricted api key since api request is from the client not from my domain

I'm using expo
installed 
react-native-google-places-autocomplete
created api key for google places web services

- Library Version: [2.4.1]
- React Native Version: [0.64]

- [ ] iOS
- [x] Android
- [ ] Web

[x] I am using expo

**Comment by mariomurrent-softwaresolutions** [comment]
Well that's always the problem with API Keys in the source code.

**Comment by mariomurrent-softwaresolutions** [comment]
Sure, you just need to request (securely) the API Key and fill it in

**Comment by bell-steven** [comment]
See #612. I'm going to close this, as there are many similar issues that have already been opened regarding this.

**Comment by matijagrcic** [comment]
Like @bell-steven said or you can use the following if you're protecting the key by iOS bundle identifiers and 
Android package name and SHA-1 signing-certificate fingerprint 

[Android Ref](https://github.com/googlemaps/google-maps-services-java/blob/e17af6bce91f0678e8eef4b744cce0cca773cafe/src/main/java/com/google/maps/android/AndroidAuthenticationInterceptor.java#L24)

```jsx

import { getBundleId } from 'react-native-device-info';
requestUrl={{
            useOnPlatform: 'all',
            url: 'https://maps.googleapis.com/maps/api', 
            headers: Platform.select({
              ios: {
                'X-Ios-Bundle-Identifier': getBundleId(),
              },
              android: {
                'X-Android-Package': getBundleId(),
                'X-Android-Cert': 'SHA1',
              },
            }),
}}
```

**Comment by derekmurawsky** [comment]
> 

Shouldn't the library support this kind of functionality? Is this a feature request we can raise? They key itself is semi-sensitive and the google recommended way of handling this is by restrictions on the key itself.

**Comment by sameretto** [comment]
so whats the solution for now just make sure to add restrictions on the key itself?

**Comment by francesco-clementi-92** [comment]
Hi @matijagrcic could you explain better your solution?

**Comment by luks7n1** [comment]
`
import { getBundleId } from 'react-native-device-info';
requestUrl={{
            useOnPlatform: 'all',
            url: 'https://maps.googleapis.com/maps/api', 
            headers: Platform.select({
              ios: {
                'X-Ios-Bundle-Identifier': getBundleId(),
              },
              android: {
                'X-Android-Package': getBundleId(),
                'X-Android-Cert': 'YOUR_SHA1',
              },
            }),
}}`

Firstly, thanks for the explanation! But I don't know if I get it right. 
Calling the API as described above providing only the header information (not the API key itself) is enough for the API to authenticate? Considering it was previously restricted on google console.
Also providing the SHA1 couldn't be considered another risk?

**Comment by luks7n1** [comment]
> ```js
> import { getBundleId } from 'react-native-device-info';
> requestUrl={{
>             useOnPlatform: 'all',
>             url: 'https://maps.googleapis.com/maps/api', 
>             headers: Platform.select({
>               ios: {
>                 'X-Ios-Bundle-Identifier': getBundleId(),
>               },
>               android: {
>                 'X-Android-Package': getBundleId(),
>                 'X-Android-Cert': 'YOUR_SHA1',
>               },
>             }),
> }}
> ```

Firstly, thank you all for the explanations! But I don't know if I get it right.
Calling the API as described above providing only the header information (not the API key itself) is enough for the API to authenticate? Considering it was previously restricted on google console.
Also providing the SHA1 couldn't be considered another risk?

**Comment by matijagrcic** [comment]
The only way you can truly protect the key is thru the proxy https://developers.google.com/maps/api-security-best-practices#proxy-server, anything else is a workaround.

**Comment by aminta** [comment]
@matijagrcic why the refs to [google-maps-services-java](https://github.com/googlemaps/google-maps-services-java) and https://github.com/cloudendpoints/endpoints-management-python/tree/f67427d7fe3529b2f0c90a769c3a6b241a9d963a ? They are not dependencies of this library... So how can I apply your patch?

**Comment by ARIPRASATH4664** [comment]
> > ```
> > import { getBundleId } from 'react-native-device-info';
> > requestUrl={{
> >             useOnPlatform: 'all',
> >             url: 'https://maps.googleapis.com/maps/api', 
> >             headers: Platform.select({
> >               ios: {
> >                 'X-Ios-Bundle-Identifier': getBundleId(),
> >               },
> >               android: {
> >                 'X-Android-Package': getBundleId(),
> >                 'X-Android-Cert': 'YOUR_SHA1',
> >               },
> >             }),
> > }}
> > ```
> 
> Firstly, thank you all for the explanations! But I don't know if I get it right. Calling the API as described above providing only the header information (not the API key itself) is enough for the API to authenticate? Considering it was previously restricted on google console. Also providing the SHA1 couldn't be considered another risk?

requestUrl={{
  useOnPlatform: 'all',
  url: 'https://maps.googleapis.com/maps/api', 
  headers: Platform.select({
    ios: {
      'X-Ios-Bundle-Identifier': getBundleId(),
    },
    android: {
      'X-Android-Package': getBundleId(),
      'X-Android-Cert': 'YOUR_SHA1', // this should be in the format XXXXXX... instead of XX:XX:XX...
    },
  }),
}}
