### ISSUE TITLE
Google Places API keys with restricted domain Google Console configuration cannot be used

### ISSUE THREAD

**Issue by wtomaszewski-applause** [FaridSafi/react-native-google-places-autocomplete#789]
# Describe the bug

If Google Places API Key is configured to allow using Api Key inside restricted domain, not open access, then library is not working and the error is returned from `onFail` handler:
`API keys with referer restrictions cannot be used with this API`.
I'm not sure if that is a possibility to fix that but if that is true that should be described in `readme` as that library cannot be used in such cases.

# Reproduction - (required - issue will be closed without this)
1) Update Google Places API Key restriction in APIs & Services page of the Google Cloud console to restrict to some domain instead of global access.
2) Observe error from `onFail` handler inside `GooglePlacesAutocomplete`. Autocompletion is not worming anymore. 

# Additional context

- Library Version: [2.4.1]
- React Native Version: [e.g. 0.62.2]

- [x] iOS
- [ ] Android
- [ ] Web

If you are using expo please indicate here:

- [x] I am using expo

**Comment by bell-steven** [comment]
This is documented in the [Readme](https://github.com/FaridSafi/react-native-google-places-autocomplete#compatibility). See #612. 
I'm going to close this, as there are many similar issues that have already been opened regarding this.
