### ISSUE TITLE
rankBy distance not working

### ISSUE THREAD

**Issue by Jaafar-abusair** [FaridSafi/react-native-google-places-autocomplete#79]
```
 GooglePlacesSearchQuery={{ 
                                rankby: 'distance', 
                                types: 'street_address',
                                location: 34.8083336+','+32.1579631,
                            }} 
```
Not working, Also I have traced your code, _requestNearby never called on change text which support to get ranked result

**Comment by myaskevich** [comment]
According to [the docs](https://developers.google.com/places/web-service/search#PlaceSearchRequests), `rankby` requires some other parameters to be provided:
> If rankby=distance (described under Optional parameters below) is specified, then one or more of keyword, name, or type is required.
Try using `type` parameter instead of `types`

**Comment by Jaafar-abusair** [comment]
I have no idea why Im using types sice its deprecated, I thought Im using type but i will check it tonorrow. Thank you
One note, in your js file do you have this condition? Because the function not getting invoked any way "_requestNearby"

**Comment by avishkar2k** [comment]
https://stackoverflow.com/a/50817579/8646587

If rankby=distance (described under Optional parameters below) is specified, then one or more of keyword, name, or type is required. 

rankby — Specifies the order in which results are listed. Note that rankby must not be included if radius (described under Required parameters above) is specified.
