### ISSUE TITLE
Custom Text Input

### ISSUE THREAD

**Issue by aliwaqar981** [FaridSafi/react-native-google-places-autocomplete#801]
**Is your feature request related to a problem? Please describe.**

I want to display an icon on the start of the text input

**Describe the solution you'd like**

Give option to render custom text input.

**Comment by bell-steven** [comment]
You can add a component to the side of the component, or use a custom text input.
See the [Props](https://github.com/FaridSafi/react-native-google-places-autocomplete#props) section of the readme, `renderLeftButton` and `textInputProps`.

**Comment by aliwaqar981** [comment]
@bell-steven can you please guide me to any example that how can I pass custom text input. I'm not able to find out that from anywhere.

**Comment by aliwaqar981** [comment]
@bell-steven I've tried below code but getting error:

**Code**:
`<GooglePlacesAutocomplete
        placeholder="Search a place"
        fetchDetails
        textInputProps={{
          InputComp: <Search placeholder="Search a place" />,
        }}`
        
   **Getting below error**
   
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object`

**Comment by official-bharat** [comment]
textInputProps={{
                    InputComp: TextInput,
                    // InputComp: TextInput,
                    placeholderTextColor: '#8A8E99',
                    onblur: () => setFieldTouched('pick_up'),
                    value: values.pick_up,
                    onChangeText: handleChange('pick_up'),
                    label: 'Pick Up Date & Time',
                    mode: 'outlined',
                    style: [
                      TextInputStyle.containerStyleWithMargin,
                      {width: wp(90)},
                    ],
                  }}
                  
                  
                  You can Use the above code for custom components with props as well.
