### ISSUE TITLE
How to set an initial prefilled location?

### ISSUE THREAD

**Issue by KrisLau** [FaridSafi/react-native-google-places-autocomplete#802]
# Describe the problem
I'm storing the location (using the lat/long or placeID) that users selected in the autocomplete component. Then, I would like to be able to display that location in the autocomplete component again

# Reproduction - (required - issue will be closed without this)
N/A

# Additional context

- Library Version: `^2.2.0`
- React Native Version: `^0.67.3`

- [x] iOS
- [x] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by haridevks** [comment]
there is a property called textInput props in the autocomplete. You can use that.

textInputProps={{placeholderTextColor:'#96989b',
     value: this.state.cityStateCountry20,
 onChangeText:(text) =>this.setState({cityStateCountry20:text})
    }}

**Comment by haridevks** [comment]
I had tried this but this causes another issue, that when we try to remove the text which is filled in autocomplete it will push the same  state value again.( cursor moves when we backspace,,but the value will be there)

**Comment by erickgtzh** [comment]
Were you able to do it??

**Comment by KrisLau** [comment]
@erickgtzh Sorry I forgot to close this! I set it using the value prop in the `textInputProps`
