### ISSUE TITLE
Setting input text from outside the return() block

### ISSUE THREAD

**Issue by burakkbilginn** [FaridSafi/react-native-google-places-autocomplete#811]
# Describe the problem

I want to set the input text of autocomplete from reactjs, not inside the return() block, but outside of it. Is this possible? I mean:

```
const App = () => {
**here how can I set the text of the input box?

return (
<GooglePlacesAutocomplete

                    placeholder='....'

                    onPress= ....
                    ....
/>
}

```
# Reproduction - (required - issue will be closed without this)

Steps to reproduce the behavior - a minimal reproducible code example, link to a [snack](https://snack.expo.io) or a repository.

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click to expand!</summary>
  
  ```javascript
    
    
  ```
</details>

_Please remember to remove you google API key from the code you provide here_

# Additional context

- Library Version: [e.g. 1.4.2]
- React Native Version: [e.g. 0.62.2]

- [ ] iOS
- [ x ] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by bell-steven** [comment]
See the [Methods](https://github.com/FaridSafi/react-native-google-places-autocomplete#methods) section of the readme.

**Comment by burakkbilginn** [comment]
> See the [Methods](https://github.com/FaridSafi/react-native-google-places-autocomplete#methods) section of the readme, the `setAddressText` method will probably do the trick.

Thank you very much, yes it did the trick man!
