### ISSUE TITLE
Double tap to select place

### ISSUE THREAD

**Issue by salilbajaj** [FaridSafi/react-native-google-places-autocomplete#82]
Upon tapping on any place say new York,keyboard gets closed first and the placed is selected when you tap again. Basically it takes double tap to select a place. First hides the keyboard.Second selects the place.

**Comment by aindeev** [comment]
Hey I am experiencing the same issue, did you find a way around this?

**Comment by salilbajaj** [comment]
No.. I haven't yet

**Comment by myaskevich** [comment]
I've faced this issue before, it's mostly related to using the component inside a ScrollView.

When doing so, look at [keyboardShouldPersistTaps](https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps) ScrollView prop.

**Comment by salilbajaj** [comment]
Had already tried that.. But dint work.. And yes it is inside scrollview.. but even if I take it out of scrollview,issue persists

**Comment by ssomnoremac** [comment]
I get a warning

```
 Failed prop type: Invalid prop `keyboardShouldPersistTaps` of type `string` supplied to `RCTScrollView`, expected `boolean`.
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ListView)
    in ListView (created by GooglePlacesAutocomplete)
```
when using inside this
```
<KeyboardAwareScrollView style={ Styles.container } keyboardShouldPersistTaps={true}>
  <GooglePlacesAutocomplete ...
```
solved it by adding `keyboardShouldPersistTaps={true}` in the GPAutocomplete component as well as @myaskevich suggests

**Comment by sonnguyenit** [comment]
@ssomnoremac use: `keyboardShouldPersistTaps={'always'}` instead 'cuz deprecated.

**Comment by salilbajaj** [comment]
Getting the same warning upon using keyboardShouldPersistTaps={'always'} ..  Invalid prop `keyboardShouldPersistTaps` of type `string` supplied to `RCTScrollView`, expected `boolean`.

**Comment by myaskevich** [comment]
@salilbajaj it means you're using an older version of RN. Either upgrade RN version or use `keyboardShouldPersistTaps={true}`.

**Comment by jjm340** [comment]
I'm stilling seeing this issue not in a ScrollView, but rather inside a modal.  Any ideas?
