### ISSUE TITLE
remove autocorrect?

### ISSUE THREAD

**Issue by timurridjanovic** [FaridSafi/react-native-google-places-autocomplete#83]
Do you have a way of removing autocorrect from the TextInput?

**Comment by myaskevich** [comment]
Hi @timurridjanovic 

Use `textInputProps` prop.

```
<GooglePlacesAutocomplete
  ...
  textInputProps={{
    autoCorrect: false
  }}
/>
```

**Comment by lelup** [comment]
hi @myaskevich I can't fix auto correct in my app:
![screen shot 2016-12-26 at 10 15 08](https://cloud.githubusercontent.com/assets/19283388/21475076/90c424e2-cb59-11e6-85ba-f718b4340d70.png)

<GooglePlacesAutocomplete
        placeholder='Nhập....'
        minLength={2} // minimum length of text to search
        autoFocus={true}
        fetchDetails={false}
        onPress={this._onPress.bind(this)}
        onCancelPress={this._onCancelPress.bind(this)}
        getDefaultValue={() => {
          return ''; // text input default value
        }}
        textInputProps={{
            autoCorrect: false
        }}
        styles={{
          description: {
....
/>
