### ISSUE TITLE
how to change text in the TextInput

### ISSUE THREAD

**Issue by timurridjanovic** [FaridSafi/react-native-google-places-autocomplete#84]
Can we use the setAddressText method somehow to set the address in the search box?

**Comment by myaskevich** [comment]
Hi @timurridjanovic 

Yes, you can use `setAddressText` method.

Assign the Component a ref and call it from your parent component. Check out refs example https://facebook.github.io/react/docs/refs-and-the-dom.html

**Comment by jaspal747** [comment]
The ref attribute in the textInput field is a string. The latest React recommends using a callback. 
Can you please look into updating it if that is feasible?
https://facebook.github.io/react/docs/refs-and-the-dom.html#legacy-api-string-refs

Thanks
