### ISSUE TITLE
Current Location tap doesn't trigger onPress callback

### ISSUE THREAD

**Issue by timurridjanovic** [FaridSafi/react-native-google-places-autocomplete#85]
When I tap on Current Location the onPress callback doesn't get called.

**Comment by myaskevich** [comment]
Hi @timurridjanovic 

We do not currently fire `onPress` callback on Current Location item press.

I'm just wondering, what is your use-case?

**Comment by timurridjanovic** [comment]
![image](https://cloud.githubusercontent.com/assets/1295621/21456839/fb8dca16-c8f8-11e6-9710-df48204ef9cd.png)

Here is a screenshot, it's in French but I thought it would be useful for you to see. Emplacement actuel means Current location. When I press on it, I want the map and the orange location pin to move to the users current location.

**Comment by myaskevich** [comment]
Hi @timurridjanovic 

I don't have enough time to hop on on this issue, but it looks like a trivial change. Would you like to add it yourself? Priority PR review guaranteed! ;)

**Comment by waterfoul** [comment]
It looks like the current code does exactly this, see df61a3c5a640ee1726ea3731d3a23e44048cdcb7

**Comment by myaskevich** [comment]
Hey @timurridjanovic 

`nearbySearchAPI={'None'}` now does what you want. Thanks @waterfoul
