### ISSUE TITLE
Add Search Icon in the Input box

### ISSUE THREAD

**Issue by somya-wittybrains** [FaridSafi/react-native-google-places-autocomplete#861]
# Description

@FaridSafi I have been trying to add an SVG search icon on the left of the input box. But I am facing trouble in implementing that. 
```
const SearchIcon = () => (
  <SvgIcon name="Search" width={24} height={24} color="#A7A9AC" />
);
```

```
<GooglePlacesAutocomplete
          placeholder="Search"
          onPress={(data, details = null) => {
            // 'details' is provided when fetchDetails = true
            console.log(data, details);
          }}
          query={{
            key: 'API_KEY',
            language: 'en'
          }}
          requestUrl={{
            useOnPlatform: 'all', // or "all"
            url: 'https://cors-anywhere.herokuapp.com/https://maps.googleapis.com/maps/api' // or any proxy server that hits https://maps.googleapis.com/maps/api
          }}
          renderLeftButton={SearchIcon}
          textInputProps={{
            onChangeText: handleLocationChange,
           // left: { SearchIcon },
            placeholderTextColor: '#737373',
            selectionColor: "#3B2DB0"
          }}
          styles={{
            textInput: searchBox
          }}
  />
```
When I add the icon in `renderLeftButton` props it goes outside the input box.
![image](https://user-images.githubusercontent.com/99490105/204833399-50b04eab-4fc0-4338-9e1e-feecb65bb000.png)
![image](https://user-images.githubusercontent.com/99490105/204831814-b4ae2156-d9c3-46de-8996-b8ccc3f45fb4.png)

What prop or method I can use to add the icon inside the search box?

**Comment by thinktapper** [comment]
@somya-wittybrains did you figure it out??

**Comment by Rakxhit** [comment]
do one thing give border to container instead of textinput like this: 

styles={{
              container: {
                borderRadius: scaleWidth(14),
                backgroundColor: 'grey',
              },
              textinput: {
              //
              }
}
