### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ChaseK30** [FaridSafi/react-native-google-places-autocomplete#878]
# Describe the bug

After upgrading to expo 48.0.9 (latest) the part of the application that has the google places autocomplete component crashes every time a User types anything in the box and the only logs that get thrown are **TypeError: undefined is not an object (evaluating 'e.getItem')**

# Reproduction - (required - issue will be closed without this)

Cannot give a link to repo because it is confidential but here is the component setup we are using

`<GooglePlacesAutocomplete
      placeholder="Type here..."
      minLength={1}
      autoFocus
      returnKeyType="default"
      fetchDetails
      styles={{
        container: {
          flex: 1,
        },
        textInputContainer: {
          flexDirection: 'row',
        },
        textInput: {
          backgroundColor: theme.colors.primaryBackgroundGreen,
          color: theme.colors.primaryText,
          height: 44,
          borderRadius: 21.5,
          paddingVertical: 5,
          paddingHorizontal: 20,
          fontSize: 15,
          flex: 1,
        },
        poweredContainer: {
          justifyContent: 'flex-end',
          alignItems: 'center',
          borderBottomRightRadius: 5,
          borderBottomLeftRadius: 5,
          borderColor: '#c8c7cc',
          borderTopWidth: 0.5,
        },
        powered: {},
        listView: {},
        row: {
          backgroundColor: '#FFFFFF',
          padding: 13,
          height: 44,
          flexDirection: 'row',
        },
        separator: {
          height: 0.5,
          backgroundColor: '#c8c7cc',
        },
        description: {},
        loader: {
          flexDirection: 'row',
          justifyContent: 'flex-end',
          height: 20,
        },
      }}
      onPress={(data, details = null) => {
        try {
          const zipCode = details?.address_components.find((addressComponent) =>
            addressComponent.types.includes('postal_code')
          )?.short_name;
          setAddress(
            // eslint-disable-next-line no-useless-concat
            `${data.description} ,${details.address_components[6].long_name}` + ` ,${zipCode}`
          );
        } catch (error) {
          alert.alert(error);
        }
      }}
      query={{
        key: ',
        language: 'en',
        types: 'geocode',
      }}
    />`

The crash happens as soon as something gets typed into the text input

Steps to reproduce the behavior - a minimal reproducible code example, link to a [snack](https://snack.expo.dev/) or a repository.

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click to expand!</summary>
  
  ```javascript
    
    
  ```
</details>

_Please remember to remove you google API key from the code you provide here_

# Additional context

- Library Version: [e.g. 1.4.2]
- React Native Version: [e.g. 0.62.2]

- [x] iOS
- [ ] Android
- [ ] Web

If you are using expo please indicate here:

- [x] I am using expo

Add any other context about the problem here, screenshots etc

**Comment by aravi365** [comment]
@ChaseK30  / @khenry10  Did you guys found any workaround for this issue? I am facing the same issue and stucked on this!
