### ISSUE TITLE
Current location issue

### ISSUE THREAD

**Issue by brascene** [FaridSafi/react-native-google-places-autocomplete#88]
Hi there, what could go wrong with getting the current location? If I press on "current location" label, it goes loading and report location request time out..

**Comment by myaskevich** [comment]
Hi @brascene 

Please paste in some code so we could have a closer look at your issue. ;)

**Comment by brascene** [comment]
Sorry for late answer, issue was related with GPS, solved

**Comment by bosquig** [comment]
@brascene How did you resolve this issue ? Currently having the same problem.

**Comment by brascene** [comment]
@bosquig Well, I'm not sure, because sometimes it works normally but throws error on 'data.terms' as undefined, and sometimes it doesn't work at all and gives error message 'location request timed out'.

**Comment by GrishmaM** [comment]
in IOS when i click on current location it pops out saying unable to retrieve location.
Any suggestions
