### ISSUE TITLE
Add option to remove Powered by Google Logo

### ISSUE THREAD

**Issue by jacquesdev** [FaridSafi/react-native-google-places-autocomplete#894]
**Describe the solution you'd like**

Is it possible to add props to turn off Powered By Google? It doesn't look great visually, but can of course understand why Google would prefer for it to be displayed.

Is there perhaps any requirement for it to be displayed that I am unaware of? We are already paying Google for the search traffic so this seems like (unwarranted?) free promotion

**Comment by mariusgaciu** [comment]
@jacquesdev you can already remove it. Please see link to [documentation](https://github.com/FaridSafi/react-native-google-places-autocomplete#:~:text=enablePoweredByContainer). 

In regards to its requirement, you'll need to read their T&Cs.

**Comment by jacquesdev** [comment]
@mariusgaciu, thank you, I will now close this
