### ISSUE TITLE
Location text 

### ISSUE THREAD

**Issue by brascene** [FaridSafi/react-native-google-places-autocomplete#91]
How can I change result text inside text box after click on location? e.g. if selected location has long text (street, city, district, federation etc.), can I update it on click to be only street + city or similar? 
If that is not possible, is there an option to set that text to start from left, so first part of result will be visible. Currently, if result string is long, it is placed somewhere from the middle.

Thanks!

**Comment by myaskevich** [comment]
Hi @brascene 

See https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/84
