### ISSUE TITLE
Giving style but customized

### ISSUE THREAD

**Issue by Marcelrama** [FaridSafi/react-native-google-places-autocomplete#92]
Hello apology again bothering to write I want to customize a little Google-places like the next picture I leave attached.
I do not know if it is possible to add another input inside <GooglePlacesAutocomplete> tag or I have to create another like:

<GooglePlacesAutocomplete
......
.....
....
....
/>
 <googleplacesautocomplete
.......
.....
......
.....
/>
As well as also leave the text stored after performing the search in my input
![4 home solicitar servicio ahora 2](https://cloud.githubusercontent.com/assets/22013703/21617075/cb8ed894-d1ba-11e6-81c5-c0cb22b2c23d.jpg)

So far I've only succeeded in having something like the next catch

![simulator screen shot 3 ene 2017 1 46 47 p m](https://cloud.githubusercontent.com/assets/22013703/21617128/15236132-d1bb-11e6-96b8-b32ccb251ec7.png)

**Comment by myaskevich** [comment]
Hi
No problem at all ;)
Interesting. I have never seen someone using it in this way, so good luck!
So far I see using two separate components to be the best option.Have a look at styling options available in readme.

Sincerely,
Maxim Yaskevich




On Tue, Jan 3, 2017 at 8:47 PM +0300, "Marcelrama" <notifications@github.com> wrote:












Hello apology again bothering to write I want to customize a little Google-places like the next picture I leave attached.

I do not know if it is possible to add another input inside  tag or I have to create another like:


<GooglePlacesAutocomplete

......

.....

....

....

/>

<googleplacesautocomplete

.......

.....

......

.....

/>

As well as also leave the text stored after performing the search in my input




So far I've only succeeded in having something like the next catch

**Comment by Marcelrama** [comment]
ok thanks, I thought that the component had some method my intention was to save me some lines of code, now the other as I can leave the location obtained in my search box.

**Comment by Marcelrama** [comment]
I do not know if you understand what I mean the data of the search as well as I can mark on the map I would also like to mark them in the input as the name.
Please let me know to be a little more specific

**Comment by myaskevich** [comment]
Hi

Didn't quite catch that.

I guess you'll save departure and destination location in the parent component state.

Use `setAddressText` to set your custom location when moving the marker around. Also get location details using `onPress` prop when selecting one of suggested values.

**Comment by Marcelrama** [comment]
Ok thank you very much for the contribution and reply. Best regards

**Comment by Marcelrama** [comment]
Hello sorry for disturbing the idea raised was not possible due to the design to perform the search the list that shed the localities was not very nice for my design, choose to go to another window where I fully deploy the list and do not affect the design . When I press my textinput I go to my window `onSelectionChange = {this._GoToPlaces}` then I get the search, I want that at the end of the search I automatically return to my main window where I have the maps and the data obtained are passed to that window and shown as The image I put in my first post
```
 GetDefaultValue = {() => {
            Return Actions.Menu ({type: 'back'})
               }}

```
I thought that I could serve here but notice that it is executed before starting the window which has nothing to do when doing the search.

If it is not much annoyance you could give me a little more detail on how to perform in case it is possible to save that data and execute my Actions.Menu ({type: 'back'})

**Comment by myaskevich** [comment]
HI @Marcelrama 

Did you hear about Redux? Try it out, I think it can help you with this issue. ;)

**Comment by myaskevich** [comment]
I'm closing this GH issue as not relevant to the library, but feel free to drop me an email if you have further questions (see profile).
