### ISSUE TITLE
listView not displaying

### ISSUE THREAD

**Issue by DJSrA** [FaridSafi/react-native-google-places-autocomplete#93]
Hey, 

I decided to try this out with 0.39.2 and even though data is being returned appropriately the listView is not displaying.

This is literally just the example. Here is my code:

```
import React, { Component } from 'react';
import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';

class Example extends Component {
  render() {
    return (
      <GooglePlacesAutocomplete
        placeholder='Search'
        minLength={3}
        autoFocus={false}
        listViewDisplayed='auto'
        fetchDetails
        renderDescription={(row) => row.terms[0].value}
        onPress={(data, details = null) => {
          console.log(data);
          console.log(details);
        }}
        getDefaultValue={() => {
          return '';
        }}
        query={{
          key: 'API_KEY',
          language: 'en',
        }}
        styles={{
          description: {
            fontWeight: 'bold',
          },
          predefinedPlacesDescription: {
            color: '#1faadb',
          }
        }}
        nearbyPlacesAPI='GooglePlacesSearch'
        GoogleReverseGeocodingQuery={{
        }}
        GooglePlacesSearchQuery={{
          rankby: 'distance',
          types: 'address',
        }}
        filterReverseGeocodingByTypes={['locality', 'administrative_area_level_3']}
      />
    );
  }
}

export default Example;
```

Here is what I see:

<img width="378" alt="screen shot 2017-01-09 at 3 01 23 pm" src="https://cloud.githubusercontent.com/assets/4030510/21781400/260bb988-d67d-11e6-919a-c549f520eb62.png">

Here is what is being returned when I console.log the `row`

<img width="955" alt="screen shot 2017-01-09 at 3 02 02 pm" src="https://cloud.githubusercontent.com/assets/4030510/21781412/34343b52-d67d-11e6-9d4b-1723c49edeca.png">

I can't get anything to show even by massively editing the `listView` styling.

Is anyone else having/have had this problem or does anyone have a solution?

Side notes, the `minLength` property does not keep anything from firing before that length and using `predefinedPlaces` causes an un-traceable `getHostNode` of `null` error.

**Comment by myaskevich** [comment]
Hi @DJSrA 

See https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/75

**Comment by DJSrA** [comment]
See @jnrepo comment on #75 

```
const windowSize = require('Dimensions').get('window')
const deviceWidth = windowSize.width;
const deviceHeight = windowSize.height;

        styles={{
          listView: {
            position: 'absolute',
            height: deviceHeight,
            width: deviceWidth
          }
        }}
```

Closing as repeat
