### ISSUE TITLE
Which Google Places API to use? Places API or Places API (New) ?

### ISSUE THREAD

**Issue by LagoonProject** [FaridSafi/react-native-google-places-autocomplete#938]
# Describe the problem

I'm using this library for the first time, and enabling Google Places API for the first time in the Google Cloud Console. 

I see two APIs for Google Places : Places API and Places API (New), I'm not sure which one I should enable to work with react-native-google-places-autocomplete

# Reproduction - (required - issue will be closed without this)

In Google Cloud Console, under APIs & Services there is two Places API that can be enabled : Places API and Places API (New)

# Additional context

- Library Version: [e.g. 1.4.2] Not installed yet
- React Native Version: ["0.73.6"]

- [x] iOS
- [x] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc
![Capture d’écran 2024-04-08 à 12 44 32](https://github.com/FaridSafi/react-native-google-places-autocomplete/assets/42693834/a7ef1a96-af06-4ef1-af20-e607f37e3253)

**Comment by brandonzalcman** [comment]
@LagoonProject My understanding is that both will work. On my latest project i have opted to using the new places API and can confirm it works.

**Comment by LagoonProject** [comment]
After further use, it seems this library makes a request to `https://maps.googleapis.com/maps/api/place/details/json` 
which corresponds to the legacy Places API.

```
      request.open(
        'GET',
        `${url}/place/details/json?` +
          Qs.stringify({
            key: props.query.key,
            placeid: rowData.place_id,
            language: props.query.language,
            ...props.GooglePlacesDetailsQuery,
          }),
      );
```

The Places API (New) uses `https://places.googleapis.com/v1/places/`

As per the docs : https://developers.google.com/maps/documentation/places/web-service/overview#places-api-new

So from my understanding, the Places API (New) is not used. But maybe I missed something.

**Comment by brandonzalcman** [comment]
Yep you are right, if you use the Google Places New API key it will still return values but will return the values from the old endpoint. If i get time i might work on a fork to push the option to use the new one but got a lot of work to finish.

**Comment by LagoonProject** [comment]
From my understanding, if you enable legacy Google Places API in Google Maps Platform, this library will work. 

But if you disable it, and enable Google Places API (New) instead, it will throw an error `This API project is not authorized to use this API`

The API key can be used for both, it's just that the library doesn't make the request to the right endpoint which should be `https://places.googleapis.com/v1/places/`

**Comment by hashhirr** [comment]
@LagoonProject Have you found any solution for this yet?
in my cloud console the old places api is not visible and the autocomplete library is not working.

**Comment by LagoonProject** [comment]
> [@LagoonProject](https://github.com/LagoonProject) Have you found any solution for this yet? in my cloud console the old places api is not visible and the autocomplete library is not working.

No sorry, I think I ended up doing my own component, I haven't used this library in a while.
