### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by parveenkumar94123** [FaridSafi/react-native-google-places-autocomplete#957]
(NOBRIDGE) ERROR  Warning: Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported

This error is located at:
    in GooglePlacesAutocomplete (created by BookNowFillDetailsScreen)
    in RCTView (created by View)
    in View (created by BookNowFillDetailsScreen)
    in RCTView (created by View)
    in View (created by BookNowFillDetailsScreen)
    in RCTView (created by View)
    in View (created by BookNowFillDetailsScreen)
    in RCTView (created by View)
    in View (created by KeyboardAvoidingView)
    in KeyboardAvoidingView (created by BookNowFillDetailsScreen)
    in BookNowFillDetailsScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by AppStackNavigator)
    in AppStackNavigator (created by Router)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by Router)
    in Router (created by App)
    in SocketProvider (created by App)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer

**Comment by Paul2022-app** [comment]
Same Issue

**Comment by hdoublin** [comment]
I got same issue.

**Comment by AqibIqbal1** [comment]
I got same issue.

**Comment by roshan-ican** [comment]
this

> I got same issue. But it was solved after trying followings:
> 
> I installed manually these 2 packages, `uuid` `react-native-get-random-values`. And edited it like this in `node_modules/react-native-google-places-autocomplete/GooglePlacesAutocomplete.js`.
> 
> ```
> import 'react-native-get-random-values';
> import { v4 as uuidv4 } from 'uuid';
> ```
> 
> I followed these guide: https://github.com/uuidjs/uuid#getrandomvalues-not-supported Please check at the bottom of the ReadMe:
> 
> ![Screenshot 2024-10-29 at 1 06 34 PM](https://private-user-images.githubusercontent.com/53872946/381255267-25a21ffa-9db0-437b-bb1e-937ab2367c98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0OTIyMDYsIm5iZiI6MTczMDQ5MTkwNiwicGF0aCI6Ii81Mzg3Mjk0Ni8zODEyNTUyNjctMjVhMjFmZmEtOWRiMC00MzdiLWJiMWUtOTM3YWIyMzY3Yzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDIwMTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZjM3MmI5NDBjZDQwYTdmNDNhNTJlNmNjZDJhMzVhOWE3NjBlZjhjMTgzZDRhZjZhNmFkNGY2MWNkOTMwODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b5x6RR4GSLj1q0yLCCuyVTBVRzWBMGA5446nxHsCVqY)

this steps did not solve the issue for me

**Comment by dev-simpleplan** [comment]
Just install the package 

`npm I react-native-get-random-values `   

and import it in the main file as App.js

`import 'react-native-get-random-values'`

**Comment by AqibIqbal1** [comment]
> Just install the package
> 
> `npm i react-native-get-random-values `
> 
> and import it in the main file as App.js
> 
> `import 'react-native-get-random-values'`

It has resolved my issue.

**Comment by Pranabemed** [comment]
> 2.5.1.
You can add also in index.js

**Comment by Pranabemed** [comment]
> Hi, @parveenkumar94123, I got same error. I followed @hdoublin 's solutions at first. That worked at that time. But I got error in the next time. That's why I downgrade the package "react-native-google-placecs-autocomplete" to 2.5.1.
> 
> Finally it worked.

I need for crash solution when user search in multiple field then going to crash ...if you have solution you can give it kindle

**Comment by Shahzaib-thebytecrew** [comment]
do the following steps:

**yarn add react-native-get-random-values** or **npm i react-native-get-random-values**

and add the following import in **App.tsx** or **App.jsx**

import 'react-native-get-random-values'
