### ISSUE TITLE
Focus should be at the start of text inside a textBox 

### ISSUE THREAD

**Issue by jvarshaprdxn** [FaridSafi/react-native-google-places-autocomplete#98]
I'm using React-Native (^0.35.0) for making Android application.
Using  *GooglePlacesAutocomplete* 
Step1: I've selected address from list provided by GooglePlacesAutocomplete.
Step2: I'm Showing this selected address in my next scene using GooglePlacesAutocomplete textfield, *problem is:*  Inside the textBox cursor appears at the end of the text(Because of that I'm facing problem: if address is too long then I need to horizontally scroll back which is not a better UX) Its a default behaviour. I need the cursor to be appear at the start.

**Comment by myaskevich** [comment]
Hi @jvarshaprdxn 

`TextInput` component has [`selection` prop](https://facebook.github.io/react-native/docs/textinput.html#selection) which can be used to set cursor position on text.

Additional props can be passed to the `TextInput` component from in this library using `textInputProps` prop.

I also wanted to point out that the issue you're experiencing is not related to the library.

So try to play around with this prop and see how it works.

**Comment by jvarshaprdxn** [comment]
@myaskevich 
I have passed, **selection: {start: 1, end: 1}** to textInputProps of GooglePlacesAutocomplete.

**code is below:**
`<GooglePlacesAutocomplete
  textInputProps={
     selection: {start: 1, end: 1}
  }
/>`
but its giving me a error:  **Error while updating property 'selection' of view managed by AndroidTextInput**

**Comment by myaskevich** [comment]
The syntax is not correct. Try
```jsx
<GooglePlacesAutocomplete
  textInputProps={{ selection: { start: 1, end: 1 } }}
  ...
/>
```

**Comment by jvarshaprdxn** [comment]
@myaskevich: Actually my syntax was correct **textInputProps={ { selection: { start: 1, end: 1 } } }**  but I missed out here while posting. Still has a same error.

**Comment by bhavna18** [comment]
@jvarshaprdxn  did you found any work around as i'm too facing the same issue

**Comment by edrichhans** [comment]
> ohhh my bad!!!
> @myaskevich: Actually my syntax was correct **textInputProps={ { selection: { start: 1, end: 1 } } }** but I missed out here while posting. Still has a same error.

What's the solution? Why was this closed?
