### ISSUE TITLE
keyboardShouldPersistTaps warnings

### ISSUE THREAD

**Issue by niros001** [FaridSafi/react-native-google-places-autocomplete#99]
Hi i got this warning:
Warning: Failed prop type: Invalid prop `keyboardShouldPersistTaps` of type `string` supplied to `RCTScrollView`, expected `boolean`.

**Comment by myaskevich** [comment]
Hi @niros001 

Yes, this is because we had to align to the latest RN version, which uses string values rather than booleans.

You have two options here
* either upgrade to the latest RN version
* or supply default `keyboardShouldPersistTaps={true}` prop to the component
